import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';

@Component({ selector:'gr-metric', template:`<div class="label">{{label}}</div><strong>{{value}}</strong>@if(detail){<small>{{detail}}</small>}`, styles:[`:host{display:grid;gap:var(--space-1)}.label,small{font-size:.75rem;color:var(--color-text-muted)}strong{font-size:1.5rem;line-height:1.15;letter-spacing:-.035em;font-variant-numeric:tabular-nums}`], changeDetection:ChangeDetectionStrategy.OnPush })
export class MetricComponent { @Input({required:true})label='';@Input({required:true})value='';@Input()detail=''; }

@Component({ selector:'gr-status-indicator', template:`<span [class]="tone"><i aria-hidden="true"></i><ng-content /></span>`, styles:[`span{display:inline-flex;align-items:center;gap:var(--space-2);color:var(--color-text-secondary);font-size:.8125rem}i{width:.5rem;height:.5rem;border-radius:50%;background:var(--color-text-muted)}.success i{background:var(--color-success);box-shadow:0 0 0 3px var(--color-success-subtle)}.warning i{background:var(--color-warning);box-shadow:0 0 0 3px var(--color-warning-subtle)}.danger i{background:var(--color-danger);box-shadow:0 0 0 3px var(--color-danger-subtle)}`], changeDetection:ChangeDetectionStrategy.OnPush })
export class StatusIndicatorComponent { @Input() tone:'neutral'|'success'|'warning'|'danger'='neutral'; }

@Component({ selector:'gr-avatar', template:`<span [attr.aria-label]="name">{{initials}}</span>`, styles:[`span{width:2rem;height:2rem;display:grid;place-items:center;border:1px solid var(--color-border);border-radius:50%;color:var(--color-primary);background:var(--color-primary-subtle);font-size:.6875rem;font-weight:750;letter-spacing:.03em}`], changeDetection:ChangeDetectionStrategy.OnPush })
export class AvatarComponent { @Input() name='Usuário';get initials():string{return this.name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join('').toUpperCase()||'US';} }

@Component({ selector:'gr-table', template:`<div class="scroll" tabindex="0"><table><ng-content /></table></div>`, styles:[`.scroll{max-width:100%;overflow:auto;border:1px solid var(--color-border);border-radius:var(--radius-md);background:var(--color-surface)}table{width:100%;border-collapse:collapse;font-size:.8125rem}:host ::ng-deep th,:host ::ng-deep td{height:2.75rem;padding:0 var(--space-4);border-bottom:1px solid var(--color-border);text-align:left;white-space:nowrap}:host ::ng-deep th{color:var(--color-text-muted);background:var(--color-surface-soft);font-size:.6875rem;letter-spacing:.045em;text-transform:uppercase}:host ::ng-deep tbody tr:last-child td{border-bottom:0}:host ::ng-deep tbody tr:hover{background:color-mix(in srgb,var(--color-surface-soft) 55%,transparent)}`], changeDetection:ChangeDetectionStrategy.OnPush })
export class TableComponent {}

@Component({ selector:'gr-pagination', template:`<nav aria-label="Paginação"><span>Página {{page+1}} de {{totalPages||1}}</span><div><button type="button" [disabled]="page<=0" (click)="pageChange.emit(page-1)">Anterior</button><button type="button" [disabled]="page>=totalPages-1" (click)="pageChange.emit(page+1)">Próxima</button></div></nav>`, styles:[`nav{display:flex;align-items:center;justify-content:space-between;gap:var(--space-4);color:var(--color-text-muted);font-size:.75rem}div{display:flex;gap:var(--space-2)}button{min-height:2rem;padding:0 var(--space-3);border:1px solid var(--color-border);border-radius:var(--radius-sm);color:var(--color-text-secondary);background:var(--color-surface);cursor:pointer}button:disabled{opacity:.45;cursor:not-allowed}`], changeDetection:ChangeDetectionStrategy.OnPush })
export class PaginationComponent { @Input()page=0;@Input()totalPages=0;@Output()pageChange=new EventEmitter<number>(); }

@Component({ selector:'gr-filter-bar', template:`<section aria-label="Filtros"><ng-content /></section>`, styles:[`section{display:flex;align-items:flex-end;flex-wrap:wrap;gap:var(--space-3);padding:var(--space-3);border:1px solid var(--color-border);border-radius:var(--radius-md);background:var(--color-surface)}`], changeDetection:ChangeDetectionStrategy.OnPush })
export class FilterBarComponent {}
