import { ChangeDetectionStrategy, Component, DestroyRef, effect, inject, signal } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { GroupPickerComponent } from './group-picker.component';
import { PaginationComponent } from '../../design-system/data-display/data-display';
import { FormsModule } from '@angular/forms';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { forkJoin } from 'rxjs';
import { ContextStore } from '../../core/context/context.store';
import { localDateOnly } from '../../core/date/date-only';
import { PermissionService } from '../../core/permissions/permission.service';
import { ErrorStateComponent, SkeletonComponent, ToastService } from '../../design-system/feedback/feedback';
import { DialogComponent } from '../../design-system/surfaces/surfaces';
import { HerdApi } from './herd-api.service';
import { Animal, newUuid } from './herd.models';
import { AgendaItem, AgendaPage, PendingWorkPage, PlannerItem, PlannerPage, PlannerType, pendingLabels, plannerTypeLabels } from './herd-operations.models';
import { formatDate } from './herd.shared';

@Component({selector:'app-agenda-page',imports:[GroupPickerComponent,PaginationComponent,FormsModule,ErrorStateComponent,SkeletonComponent,DialogComponent],template:`<div class="herd-page operations-page page-enter">
 <header class="page-header"><div><span class="eyebrow">TEMPO OPERACIONAL</span><h1>Agenda do rebanho</h1><p>Atividades planejadas e necessidades derivadas, juntas sem perder sua origem.</p></div>@if(permissions.canMutateHerd()){<button class="primary-action" type="button" (click)="openCreate()">Planejar atividade</button>}</header>
 <section class="metric-strip" aria-label="Resumo da agenda"><div><span>Na agenda</span><strong>{{agenda()?.totalElements||0}}</strong></div><div><span>Necessitam atenção</span><strong>{{pending()?.totalElements||0}}</strong></div><div><span>Planejadas em aberto</span><strong>{{planner()?.totalElements||0}}</strong></div><div><span>Origem</span><strong>Unificada</strong><small>Planejado + necessário</small></div></section>
 <div class="surface-tools section-frame"><div><span class="section-kicker">FILTROS</span><h2>Janela operacional</h2></div><label>Origem<select [(ngModel)]="source" (ngModelChange)="reload()"><option value="">Todas</option><option value="MANUAL">Planejada</option><option value="DERIVED">Necessidade do rebanho</option></select></label><label>Tipo<select [(ngModel)]="type" (ngModelChange)="reload()"><option value="">Todos</option>@for(t of plannerTypes;track t){<option [value]="t">{{typeLabel(t)}}</option>}</select></label><label>De<input type="date" [(ngModel)]="from" (change)="reload()"/></label><label>Até<input type="date" [(ngModel)]="to" (change)="reload()"/></label></div>
 <div class="work-columns"><section class="section-frame operational-surface"><div class="surface-tools"><div><span class="section-kicker">AGENDA UNIFICADA</span><h2>Próximos marcos</h2></div></div>@if(loading()){<div class="list-loading"><gr-skeleton/><gr-skeleton/><gr-skeleton/></div>}@else if(error()){<gr-error-state title="Não foi possível carregar a agenda" (retry)="reload()"/>}@else if(!agenda()?.items?.length){<div class="domain-empty"><strong>Nenhum item na agenda</strong><p>Não há atividades ou necessidades para os filtros escolhidos.</p></div>}@else{<ol class="agenda-list">@for(item of agenda()!.items;track item.stableId){<li class="agenda-item"><time class="agenda-date" [attr.datetime]="item.operationalDate"><strong>{{day(item.operationalDate)}}</strong><span>{{month(item.operationalDate)}}</span></time><div class="agenda-content"><span class="source-label">{{item.source==='MANUAL'?'Atividade planejada':'Necessidade do rebanho'}}</span><strong>{{item.summary}}</strong>@if(item.identification){<small>{{item.identification}}{{item.name?' · '+item.name:''}}</small>}</div>@if(item.source==='MANUAL'&&item.plannerItemId&&permissions.canMutateHerd()){<div class="item-actions"><button type="button" (click)="editFromAgenda(item)">Reagendar</button><button type="button" (click)="transition(item.plannerItemId,'complete')">Concluir</button><button type="button" (click)="transition(item.plannerItemId,'cancel')">Cancelar</button></div>}@else if(item.source==='DERIVED'&&item.animalId){<a class="secondary-action" [href]="handoff(item)">Registrar fato</a>}</li>}</ol>}</section>
 <aside class="section-frame operational-surface"><div class="surface-tools"><div><span class="section-kicker">ATENÇÃO</span><h2>O que precisa ser feito</h2></div></div>@if(!pending()?.items?.length){<div class="domain-empty"><strong>Nenhuma pendência</strong><p>O rebanho está sem necessidades derivadas neste contexto.</p></div>}@else{<div class="process-list">@for(item of pending()!.items;track item.type+'-'+item.animalId){<article class="process-card"><div><span class="domain-badge">{{pendingLabel(item.type)}}</span><p><strong>{{item.identification}}</strong>{{item.name?' · '+item.name:''}}</p><small>{{date(item.dueOn||item.expectedOn)}}</small></div><a [href]="'/rebanho/animais/'+item.animalId">Ver animal</a></article>}</div>}</aside></div>
 <section class="section-frame parity-section"><h2>Atividades por grupo</h2><app-group-picker label="Filtrar atividades por grupo" [selected]="filterGroupId" (chosen)="filterGroupId=$event;groupPage=0;loadGroupTasks()"/><label>Situação<select [(ngModel)]="groupStatus" (ngModelChange)="groupPage=0;loadGroupTasks()"><option value="">Todas</option><option value="OPEN">Em aberto</option><option value="COMPLETED">Concluídas</option><option value="CANCELLED">Canceladas</option></select></label>@if(filterGroupId){@if(groupLoading()){<gr-skeleton/>}@else if(groupError()){<gr-error-state title="Não foi possível consultar as atividades do grupo" (retry)="loadGroupTasks()"/>}@else if(!groupTasks()?.items?.length){<p>Nenhuma atividade corresponde ao grupo e à situação selecionados.</p>}@else{<div class="responsive-table"><table><thead><tr><th>Atividade</th><th>Tipo</th><th>Data</th><th>Situação</th><th>Escopo</th><th>Ações</th></tr></thead><tbody>@for(item of groupTasks()?.items||[];track item.id){<tr><td>{{item.title}}</td><td>{{typeLabel(item.type)}}</td><td>{{date(item.scheduledFor)}}</td><td>{{item.status==='OPEN'?'Em aberto':item.status==='COMPLETED'?'Concluída':'Cancelada'}}</td><td>{{item.animalId?'Grupo e animal vinculado':'Grupo de manejo'}}</td><td>@if(item.status==='OPEN'&&permissions.canMutateHerd()){<button class="quiet-button" type="button" (click)="openEdit(item)">Editar</button><button class="quiet-button" type="button" (click)="transition(item.id,'complete')">Concluir</button><button class="quiet-button" type="button" (click)="transition(item.id,'cancel')">Cancelar</button>}</td></tr>}</tbody></table></div><gr-pagination [page]="groupPage" [totalPages]="groupTasks()?.totalPages||0" (pageChange)="groupPage=$event;loadGroupTasks()"/>}}@else{<p>Selecione um grupo para consultar suas atividades. O vínculo define o escopo planejado e não executa manejo automaticamente.</p>}</section>
 <gr-dialog [open]="editorOpen()" (closed)="closeEditor()"><span dialog-title>{{editing()?'Reagendar atividade':'Planejar atividade'}}</span><div class="form-grid compact"><label><span>Tipo</span><select [(ngModel)]="plannerType">@for(t of plannerTypes;track t){<option [value]="t">{{typeLabel(t)}}</option>}</select></label><label><span>Data prevista</span><input type="date" [(ngModel)]="scheduledFor"/></label><label class="wide"><span>Título</span><input [(ngModel)]="title" maxlength="160"/></label><label class="wide"><span>Animal</span><select [(ngModel)]="animalId"><option value="">Atividade da fazenda</option>@for(a of animals();track a.id){<option [value]="a.id">{{a.identification}}{{a.name?' · '+a.name:''}}</option>}</select></label><app-group-picker class="wide" [selected]="groupId" [disabled]="saving()" (chosen)="groupId=$event"/><label class="wide"><span>Observações</span><textarea [(ngModel)]="notes" maxlength="1000" placeholder="Opcional"></textarea></label>@if(formError()){<p class="form-error wide" role="alert">{{formError()}}</p>}</div><p class="semantic-note">Concluir esta atividade registra apenas a intenção como concluída. Pesagens, tratamentos e partos devem ser registrados em seus fluxos próprios.</p><div dialog-actions><button class="quiet-button" type="button" (click)="closeEditor()">Cancelar</button><button class="primary-action" type="button" [disabled]="saving()||!title.trim()||!scheduledFor" (click)="savePlanner()">{{editing()?'Salvar alteração':'Planejar atividade'}}</button></div></gr-dialog>
 <gr-dialog [open]="transitionItem()!==null" (closed)="closeTransition()"><span dialog-title>{{transitionAction()==='complete'?'Marcar atividade como concluída':'Cancelar atividade planejada'}}</span><p>{{transitionAction()==='complete'?'Esta ação não cria um fato de domínio. Registre o manejo realizado no fluxo correspondente.':'A atividade ficará encerrada e não poderá ser reaberta.'}}</p>@if(formError()){<p class="form-error" role="alert">{{formError()}}</p>}<div dialog-actions><button class="quiet-button" type="button" (click)="closeTransition()">Voltar</button><button class="primary-action" type="button" [disabled]="saving()" (click)="confirmTransition()">Confirmar</button></div></gr-dialog>
</div>`,styleUrls:['./herd-page.scss','./operations-page.component.scss','./parity.scss'],changeDetection:ChangeDetectionStrategy.OnPush})
export class AgendaPageComponent{
 private readonly route=inject(ActivatedRoute);private readonly api=inject(HerdApi);private readonly context=inject(ContextStore);private readonly destroyRef=inject(DestroyRef);private readonly toast=inject(ToastService);readonly permissions=inject(PermissionService);readonly agenda=signal<AgendaPage|null>(null);readonly pending=signal<PendingWorkPage|null>(null);readonly planner=signal<PlannerPage|null>(null);readonly animals=signal<Animal[]>([]);readonly loading=signal(true);readonly error=signal(false);readonly editorOpen=signal(false);readonly editing=signal<PlannerItem|null>(null);readonly transitionItem=signal<PlannerItem|null>(null);readonly transitionAction=signal<'complete'|'cancel'>('complete');readonly saving=signal(false);readonly formError=signal('');readonly groupTasks=signal<PlannerPage|null>(null);readonly groupLoading=signal(false);readonly groupError=signal(false);filterGroupId=this.route.snapshot.queryParamMap.get('groupId')||'';groupId='';groupStatus='';groupPage=0;private groupGeneration=0;private contextEpoch=0;private generation=0;private operationId='';readonly plannerTypes:PlannerType[]=['GENERAL','WEIGHING','VACCINATION','DEWORMING','BREEDING','PREGNANCY_CHECK','CALVING','MOVEMENT'];source='';type='';from='';to='';plannerType:PlannerType='GENERAL';title='';scheduledFor=localDateOnly();animalId='';notes='';
 constructor(){effect(()=>{this.context.contextVersion();this.contextEpoch++;this.animals.set([]);this.editorOpen.set(false);this.transitionItem.set(null);this.saving.set(false);this.formError.set('');if(this.context.transitionPending()||!this.context.selectedFarm()){this.generation++;this.groupGeneration++;this.groupTasks.set(null);this.animals.set([]);this.editorOpen.set(false);this.transitionItem.set(null);this.agenda.set(null);this.pending.set(null);this.planner.set(null);return}this.reload();this.loadGroupTasks()})}
 reload(){const g=++this.generation;this.loading.set(true);this.error.set(false);forkJoin({agenda:this.api.agenda({source:this.source||undefined,type:this.type||undefined,from:this.from||undefined,to:this.to||undefined}),pending:this.api.pendingWork(),planner:this.api.planner({status:'OPEN'})}).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:r=>{if(g===this.generation){this.agenda.set(r.agenda);this.pending.set(r.pending);this.planner.set(r.planner);this.loading.set(false)}},error:()=>{if(g===this.generation){this.loading.set(false);this.error.set(true)}}})}
 openCreate(){this.operationId=newUuid();this.editing.set(null);this.formError.set('');this.plannerType='GENERAL';this.title='';this.animalId='';this.groupId=this.filterGroupId;this.notes='';this.editorOpen.set(true);this.loadAnimals()}
 editFromAgenda(item:AgendaItem){if(!item.plannerItemId)return;const epoch=this.contextEpoch;this.api.plannerItem(item.plannerItemId).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:value=>{if(epoch===this.contextEpoch)this.openEdit(value)},error:()=>{if(epoch===this.contextEpoch)this.toast.show('error','Não foi possível carregar a atividade')}})}
 openEdit(item:PlannerItem){this.operationId=newUuid();this.editing.set(item);this.plannerType=item.type;this.title=item.title;this.scheduledFor=item.scheduledFor;this.animalId=item.animalId||'';this.groupId=item.groupId||'';this.notes=item.notes||'';this.formError.set('');this.editorOpen.set(true);this.loadAnimals()}
 private loadAnimals(){if(this.animals().length)return;const epoch=this.contextEpoch;this.api.animals({search:'',sex:'',status:'ACTIVE',page:0,size:100}).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:r=>{if(epoch===this.contextEpoch)this.animals.set(r.items)}})}
 closeEditor(){if(!this.saving())this.editorOpen.set(false)}
 savePlanner(){const body={operationId:this.operationId,...(this.editing()?{expectedVersion:this.editing()!.version}:{}),type:this.plannerType,title:this.title.trim(),notes:this.notes.trim()||null,scheduledFor:this.scheduledFor,animalId:this.animalId||null,groupId:this.groupId||null};const request=this.editing()?this.api.correctPlanner(this.editing()!.id,body):this.api.createPlanner(body);this.save(request,this.editing()?'Atividade reagendada':'Atividade planejada')}
 transition(id:string,action:'complete'|'cancel'){const epoch=this.contextEpoch;this.api.plannerItem(id).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:item=>{if(epoch!==this.contextEpoch)return;this.operationId=newUuid();this.transitionItem.set(item);this.transitionAction.set(action);this.formError.set('')},error:()=>{if(epoch===this.contextEpoch)this.toast.show('error','Não foi possível carregar a atividade')}})}
 closeTransition(){if(!this.saving())this.transitionItem.set(null)}
 confirmTransition(){const item=this.transitionItem();if(!item)return;const body={operationId:this.operationId,expectedVersion:item.version};this.save(this.transitionAction()==='complete'?this.api.completePlanner(item.id,body):this.api.cancelPlanner(item.id,body),this.transitionAction()==='complete'?'Atividade marcada como concluída':'Atividade cancelada')}
 private save(request:{subscribe:(observer:{next:(value:unknown)=>void;error:(error:unknown)=>void})=>unknown},message:string){if(!this.permissions.canMutateHerd()||this.saving()||this.context.transitionPending())return;const epoch=this.contextEpoch;this.saving.set(true);request.subscribe({next:()=>{if(epoch!==this.contextEpoch)return;this.saving.set(false);this.editorOpen.set(false);this.transitionItem.set(null);this.toast.show('success',message);this.reload();this.loadGroupTasks()},error:(error:unknown)=>{if(epoch!==this.contextEpoch)return;this.saving.set(false);const e=error as {status?:number;message?:string};this.formError.set(e.status===409?'A atividade foi alterada em outra sessão. Recarregue para reconciliar os dados.':e.message||'Não foi possível concluir a ação.')}})}
 loadGroupTasks(){const g=++this.groupGeneration;this.groupTasks.set(null);if(!this.filterGroupId)return;this.groupLoading.set(true);this.groupError.set(false);this.api.planner({groupId:this.filterGroupId,status:this.groupStatus||undefined,page:this.groupPage}).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:result=>{if(g!==this.groupGeneration)return;this.groupTasks.set(result);this.groupLoading.set(false)},error:()=>{if(g!==this.groupGeneration)return;this.groupError.set(true);this.groupLoading.set(false)}})}
 handoff(item:AgendaItem){return item.animalId?`/rebanho/animais/${item.animalId}`:'/rebanho/animais'};pendingLabel=(v:keyof typeof pendingLabels)=>pendingLabels[v];typeLabel=(v:PlannerType)=>plannerTypeLabels[v];date=formatDate;day=(v:string)=>new Date(v+'T12:00:00Z').toLocaleDateString('pt-BR',{day:'2-digit',timeZone:'UTC'});month=(v:string)=>new Date(v+'T12:00:00Z').toLocaleDateString('pt-BR',{month:'short',timeZone:'UTC'}).replace('.','');
}
