import { ChangeDetectionStrategy, Component, DestroyRef, effect, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { debounceTime, distinctUntilChanged, Subject, switchMap } from 'rxjs';
import { ContextStore } from '../../core/context/context.store';
import { PermissionService } from '../../core/permissions/permission.service';
import { AppError } from '../../core/api/api.models';
import { FilterBarComponent, PaginationComponent, TableComponent } from '../../design-system/data-display/data-display';
import { EmptyStateComponent, ErrorStateComponent, ToastService } from '../../design-system/feedback/feedback';
import { DialogComponent } from '../../design-system/surfaces/surfaces';
import { HerdApi } from './herd-api.service';
import { Animal, AnimalFilters, AnimalSex, AnimalStatus, Page, PaddockRef, newUuid } from './herd.models';
import { AnimalIdentityComponent, AnimalStateComponent, errorReference, sexLabel } from './herd.shared';

@Component({
  selector: 'app-animal-list-page',
  providers: [HerdApi],
  imports: [FormsModule, RouterLink, FilterBarComponent, PaginationComponent, TableComponent, EmptyStateComponent, ErrorStateComponent, DialogComponent, AnimalIdentityComponent, AnimalStateComponent],
  template: `<div class="herd-page page-enter">
    <header class="page-header"><div><span class="eyebrow">REBANHO · {{context.selectedFarm()?.farmName}}</span><h1>Animais</h1><p>Identidade, estado e localização do rebanho atual.</p></div>@if(permissions.canMutateHerd()){<a class="primary-action" routerLink="/rebanho/animais/novo">Cadastrar animal</a>}</header>
    <gr-filter-bar><label class="search-field"><span>Buscar animal</span><input type="search" [ngModel]="filters().search" (ngModelChange)="searchInput.next($event)" placeholder="Identificação ou nome" /></label><label><span>Sexo</span><select [ngModel]="filters().sex" (ngModelChange)="setFilter('sex',$event)"><option value="">Todos</option><option value="FEMALE">Fêmea</option><option value="MALE">Macho</option></select></label><label><span>Estado</span><select [ngModel]="filters().status" (ngModelChange)="setFilter('status',$event)"><option value="">Todos</option><option value="ACTIVE">Ativo</option><option value="SOLD">Vendido</option><option value="DECEASED">Baixado</option><option value="TRANSFERRED">Transferido</option><option value="ARCHIVED">Arquivado</option></select></label>@if(hasFilters()){<button class="quiet-button" type="button" (click)="clearFilters()">Limpar filtros</button>}</gr-filter-bar>
    @if(state()==='error'){<gr-error-state level="page" title="Não foi possível carregar os animais" [description]="error()?.message || 'Tente novamente em instantes.'" [reference]="reference" (retry)="load()" />}
    @else if(state()==='ready' && page()?.totalElements===0){<div class="empty-frame"><gr-empty-state [title]="hasFilters()?'Nenhum animal corresponde aos filtros':'O rebanho começa aqui'" [description]="hasFilters()?'Ajuste a busca ou remova um dos filtros ativos.':'Cadastre o primeiro animal para iniciar o histórico desta fazenda.'">@if(!hasFilters()&&permissions.canMutateHerd()){<a class="primary-action" routerLink="/rebanho/animais/novo">Cadastrar primeiro animal</a>}@if(hasFilters()){<button class="secondary-action" type="button" (click)="clearFilters()">Limpar filtros</button>}</gr-empty-state></div>}
    @else {<section class="herd-surface" aria-labelledby="herd-count"><div class="surface-heading"><div><span id="herd-count" class="count">{{page()?.totalElements || 0}} {{page()?.totalElements===1?'animal':'animais'}}</span><small>Ordenação operacional estável</small></div>@if(selected().size){<button class="secondary-action" type="button" (click)="openBatch()">Mover {{selected().size}} {{selected().size===1?'animal':'animais'}}</button>}</div>
      <gr-table [loading]="state()==='loading'" [empty]="false"><thead><tr>@if(permissions.canMutateHerd()){<th class="select-cell"><span class="sr-only">Selecionar</span></th>}<th>Animal</th><th>Estado</th><th>Sexo</th><th>Território atual</th><th><span class="sr-only">Abrir perfil</span></th></tr></thead><tbody>@for(animal of page()?.items || [];track animal.id){<tr [class.terminal]="animal.status!=='ACTIVE'"><td class="select-cell">@if(permissions.canMutateHerd()&&animal.status==='ACTIVE'){<input type="checkbox" [checked]="selected().has(animal.id)" [attr.aria-label]="'Selecionar '+animal.identification" (change)="toggle(animal)" />}</td><td><app-animal-identity [animal]="animal" /></td><td><app-animal-state [status]="animal.status" /></td><td>{{sex(animal.sex)}}</td><td><span class="territory"><i aria-hidden="true"></i>{{animal.paddock?.name || 'Sem piquete definido'}}</span></td><td><a class="row-link" [routerLink]="['/rebanho/animais',animal.id]" [attr.aria-label]="'Abrir perfil de '+animal.identification">→</a></td></tr>}</tbody></gr-table>
      @if(page();as result){<gr-pagination [page]="result.page" [totalPages]="result.totalPages" (pageChange)="changePage($event)" />}</section>}
    <gr-dialog [open]="batchOpen()" (closed)="closeBatch()"><span dialog-title>Movimentação em lote</span><div class="movement-review"><span>{{selected().size}} {{selected().size===1?'animal selecionado':'animais selecionados'}}</span><strong>{{context.selectedFarm()?.farmName}}</strong><i aria-hidden="true">↓</i><label>Destino<select [(ngModel)]="batchPaddock" required><option value="">Selecione um piquete</option>@for(paddock of paddocks();track paddock.id){<option [value]="paddock.id">{{paddock.name}}</option>}</select></label><label>Data do movimento<input type="date" [(ngModel)]="batchDate" /></label>@if(batchError()){<p class="form-error" role="alert">{{batchError()}}</p>}</div><div dialog-actions><button class="quiet-button" type="button" (click)="closeBatch()">Cancelar</button><button class="primary-action" type="button" [disabled]="batchPending()||!batchPaddock" (click)="submitBatch()">{{batchPending()?'Movendo...':'Confirmar movimentação'}}</button></div></gr-dialog>
  </div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AnimalListPageComponent {
  private readonly destroyRef=inject(DestroyRef); private readonly api=inject(HerdApi); private readonly route=inject(ActivatedRoute); private readonly router=inject(Router); private readonly toast=inject(ToastService);
  readonly context=inject(ContextStore); readonly permissions=inject(PermissionService); readonly searchInput=new Subject<string>();
  readonly state=signal<'loading'|'ready'|'error'>('loading'); readonly page=signal<Page<Animal>|null>(null); readonly error=signal<AppError|null>(null); readonly selected=signal(new Map<string,Animal>()); readonly paddocks=signal<PaddockRef[]>([]); readonly batchOpen=signal(false); readonly batchPending=signal(false); readonly batchError=signal('');
  readonly filters=signal<AnimalFilters>(parseFilters(this.route.snapshot.queryParamMap)); batchPaddock=''; batchDate=today(); private generation=0; private batchOperationId='';
  constructor(){this.searchInput.pipe(debounceTime(320),distinctUntilChanged(),takeUntilDestroyed()).subscribe(value=>this.setFilter('search',value.trim()));effect(()=>{this.context.contextVersion();this.selected.set(new Map());this.load();});}
  get reference(){return errorReference(this.error()?.requestId);} sex=sexLabel;
  hasFilters(){const f=this.filters();return !!(f.search||f.sex||f.status);}
  setFilter<K extends 'search'|'sex'|'status'>(key:K,value:AnimalFilters[K]){this.filters.update(f=>({...f,[key]:value,page:0}));this.syncUrl();this.load();}
  clearFilters(){this.filters.set({search:'',sex:'',status:'',page:0,size:20});this.syncUrl();this.load();}
  changePage(page:number){this.filters.update(f=>({...f,page}));this.syncUrl();this.load();}
  load(){const current=++this.generation;this.state.set('loading');this.error.set(null);this.api.animals(this.filters()).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:value=>{if(current!==this.generation)return;this.page.set(value);this.state.set('ready');},error:error=>{if(current!==this.generation)return;this.error.set(error instanceof AppError?error:null);this.state.set('error');}});}
  toggle(animal:Animal){this.selected.update(current=>{const next=new Map(current);next.has(animal.id)?next.delete(animal.id):next.set(animal.id,animal);return next;});}
  openBatch(){this.batchOperationId=newUuid();this.batchPaddock='';this.batchDate=today();this.batchError.set('');this.batchOpen.set(true);this.api.paddocks().subscribe({next:p=>this.paddocks.set(p.items),error:()=>this.batchError.set('Não foi possível carregar os piquetes disponíveis.')});}
  closeBatch(){if(!this.batchPending())this.batchOpen.set(false);}
  submitBatch(){if(!this.batchPaddock)return;this.batchPending.set(true);this.batchError.set('');const body={operationId:this.batchOperationId,destinationPaddockId:this.batchPaddock,occurredOn:this.batchDate,notes:null,animals:[...this.selected().values()].map(a=>({animalId:a.id,expectedVersion:a.version}))};this.api.moveBatch(body).subscribe({next:r=>{this.batchPending.set(false);this.batchOpen.set(false);this.selected.set(new Map());this.toast.show('success','Rebanho movimentado',`${r.movedCount} ${r.movedCount===1?'animal foi movido':'animais foram movidos'} para ${r.destinationPaddock.name}.`);this.load();},error:e=>{this.batchPending.set(false);this.batchError.set(conflictText(e));}});}
  private syncUrl(){const f=this.filters();void this.router.navigate([], {relativeTo:this.route,queryParams:{search:f.search||null,sex:f.sex||null,status:f.status||null,page:f.page||null,size:f.size===20?null:f.size},replaceUrl:true});}
}
function parseFilters(params:import('@angular/router').ParamMap):AnimalFilters{const page=Number(params.get('page'));const size=Number(params.get('size'));const sex=params.get('sex');const status=params.get('status');return{search:(params.get('search')||'').slice(0,100),sex:sex==='FEMALE'||sex==='MALE'?sex:'',status:['ACTIVE','SOLD','DECEASED','TRANSFERRED','ARCHIVED'].includes(status||'')?status as AnimalStatus:'',page:Number.isInteger(page)&&page>=0?page:0,size:[20,50,100].includes(size)?size:20};}
function today(){return new Date().toISOString().slice(0,10);}
function conflictText(error:unknown){return error instanceof AppError&&error.code==='HERD_VERSION_CONFLICT'?'Um dos animais foi atualizado em outra sessão. Recarregue a lista antes de tentar novamente.':error instanceof AppError?error.message:'Não foi possível concluir a movimentação.';}
