import { ChangeDetectionStrategy, Component, DestroyRef, effect, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { forkJoin } from 'rxjs';
import { AppError } from '../../core/api/api.models';
import { ContextStore } from '../../core/context/context.store';
import { PermissionService } from '../../core/permissions/permission.service';
import { StatusIndicatorComponent } from '../../design-system/data-display/data-display';
import { AlertComponent, ErrorStateComponent, SkeletonComponent, ToastService } from '../../design-system/feedback/feedback';
import { DialogComponent } from '../../design-system/surfaces/surfaces';
import { HerdApi } from './herd-api.service';
import { Animal, AnimalEvent, AnimalHistory, PaddockRef, animalTone, newUuid, sexLabels, statusLabels, terminalStatuses } from './herd.models';
import { errorReference, formatDate } from './herd.shared';

type Action='correct'|'move'|'transfer'|null;
@Component({selector:'app-animal-profile-page',providers:[HerdApi],imports:[FormsModule,RouterLink,StatusIndicatorComponent,AlertComponent,ErrorStateComponent,SkeletonComponent,DialogComponent],template:`<div class="herd-page profile page-enter">
  <a class="back-link" routerLink="/rebanho/animais">← Voltar ao rebanho</a>
  @if(state()==='loading'){<div class="profile-skeleton" aria-label="Carregando perfil do animal"><gr-skeleton/><gr-skeleton/><gr-skeleton/><gr-skeleton/></div>}
  @else if(state()==='error'){<gr-error-state level="page" title="Animal não encontrado ou indisponível neste contexto" [description]="profileErrorText()" [reference]="reference" (retry)="load()" />}
  @else if(animal();as item){
    <header class="profile-header"><div class="identity-block"><span class="identity-orbit" aria-hidden="true"><i></i></span><div><span class="eyebrow">IDENTIDADE ANIMAL</span><h1>{{item.identification}}</h1>@if(item.name){<p>{{item.name}}</p>}</div></div><div class="profile-actions">@if(permissions.canMutateHerd()){<button class="secondary-action" type="button" (click)="openCorrection(item)">Corrigir dados</button>}@if(canOperate(item)){<button class="secondary-action" type="button" (click)="openMovement()">Movimentar</button>}@if(canTransfer(item)){<button class="primary-action" type="button" (click)="openTransfer()">Transferir</button>}</div></header>
    @if(created()){<gr-alert tone="success" title="Animal cadastrado"><p>A identidade foi criada e o histórico já está disponível.</p></gr-alert>}
    @if(conflict()){<gr-alert tone="warning" title="Os dados deste animal foram atualizados em outra sessão"><p>Recarregue os dados antes de fazer uma nova alteração.</p><button class="alert-action" type="button" (click)="load()">Recarregar dados</button></gr-alert>}
    <section class="state-strip" aria-label="Estado e território atuais"><div><span>Estado atual</span><gr-status-indicator [tone]="tone(item.status)">{{status(item.status)}}</gr-status-indicator></div><div><span>Sexo</span><strong>{{sex(item.sex)}}</strong></div><div><span>Nascimento</span><strong>{{date(item.birthDate)}}</strong></div><div class="territory-current"><span>Território atual</span><strong>{{context.selectedFarm()?.farmName}}</strong><small>› {{item.paddock?.name || 'Sem piquete definido'}}</small></div></section>
    <div class="detail-grid"><section class="timeline section-frame" aria-labelledby="timeline-title"><header><div><span class="section-kicker">TRAJETÓRIA</span><h2 id="timeline-title">Histórico do animal</h2></div><span>{{history()?.totalElements || 0}} eventos</span></header>@if(historyError()){<gr-error-state title="Não foi possível carregar o histórico" [reference]="historyReference" (retry)="load()"/>}@else if(!history()){<div class="timeline-loading"><gr-skeleton/><gr-skeleton/><gr-skeleton/></div>}@else{<ol>@for(event of visibleEvents();track event.id){<li><span class="timeline-marker" aria-hidden="true"></span><div class="event"><div><strong>{{eventTitle(event)}}</strong><time [attr.datetime]="event.occurredOn">{{date(event.occurredOn)}}</time></div><p>{{eventSummary(event)}}</p></div></li>}</ol>}</section>
      <aside class="facts section-frame"><span class="section-kicker">LEITURA ATUAL</span><h2>Dados de identidade</h2><dl><div><dt>Identificação</dt><dd>{{item.identification}}</dd></div><div><dt>Nome</dt><dd>{{item.name || 'Não informado'}}</dd></div><div><dt>Sexo</dt><dd>{{sex(item.sex)}}</dd></div><div><dt>Nascimento</dt><dd>{{date(item.birthDate)}}</dd></div></dl><p class="version">Versão {{item.version}} · usada para proteger alterações simultâneas</p></aside></div>
  }
  <gr-dialog [open]="action()==='correct'" (closed)="closeAction()"><span dialog-title>Corrigir dados do animal</span><div class="form-grid compact"><label class="wide"><span>Identificação</span><input [(ngModel)]="editIdentification" maxlength="100" /></label><label><span>Nome</span><input [(ngModel)]="editName" maxlength="255" /></label><label><span>Sexo</span><select [(ngModel)]="editSex"><option value="FEMALE">Fêmea</option><option value="MALE">Macho</option></select></label><label><span>Nascimento</span><input type="date" [(ngModel)]="editBirthDate" [max]="today" /></label>@if(actionError()){<p class="form-error wide" role="alert">{{actionError()}}</p>}</div><div dialog-actions><button class="quiet-button" type="button" (click)="closeAction()">Cancelar</button><button class="primary-action" type="button" [disabled]="pending()||!editIdentification.trim()" (click)="saveCorrection()">Salvar correção</button></div></gr-dialog>
  <gr-dialog [open]="action()==='move'" (closed)="closeAction()"><span dialog-title>Movimentar animal</span><div class="movement-review"><span>{{animal()?.identification}}</span><strong>{{animal()?.paddock?.name || 'Sem piquete definido'}}</strong><i aria-hidden="true">↓</i><label>Destino<select [(ngModel)]="destinationPaddock"><option value="">Selecione um piquete</option>@for(p of availablePaddocks();track p.id){<option [value]="p.id">{{p.name}}</option>}</select></label><label>Data do movimento<input type="date" [(ngModel)]="occurredOn" /></label><label>Observações<textarea [(ngModel)]="notes" maxlength="1000" placeholder="Opcional"></textarea></label>@if(actionError()){<p class="form-error" role="alert">{{actionError()}}</p>}</div><div dialog-actions><button class="quiet-button" type="button" (click)="closeAction()">Cancelar</button><button class="primary-action" type="button" [disabled]="pending()||!destinationPaddock" (click)="move()">Confirmar movimentação</button></div></gr-dialog>
  <gr-dialog [open]="action()==='transfer'" (closed)="closeAction()"><span dialog-title>Transferir custódia</span><div class="movement-review"><span>{{animal()?.identification}}</span><strong>{{context.selectedFarm()?.farmName}}</strong><i aria-hidden="true">↓</i><label>Fazenda de destino<select [(ngModel)]="destinationFarm"><option value="">Selecione uma fazenda</option>@for(f of destinationFarms();track f.farmId){<option [value]="f.farmId">{{f.farmName}}</option>}</select></label><label>Data da transferência<input type="date" [(ngModel)]="occurredOn" /></label><label>Observações<textarea [(ngModel)]="notes" maxlength="1000" placeholder="Opcional"></textarea></label><p class="custody-note">A fazenda de destino assumirá a custódia operacional. Este perfil pode deixar de estar disponível no contexto atual.</p>@if(actionError()){<p class="form-error" role="alert">{{actionError()}}</p>}</div><div dialog-actions><button class="quiet-button" type="button" (click)="closeAction()">Cancelar</button><button class="primary-action" type="button" [disabled]="pending()||!destinationFarm" (click)="transfer()">Confirmar transferência</button></div></gr-dialog>
  </div>`,styleUrl:'./animal-profile-page.component.scss',changeDetection:ChangeDetectionStrategy.OnPush})
export class AnimalProfilePageComponent{
 private readonly api=inject(HerdApi);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);private readonly destroyRef=inject(DestroyRef);private readonly toast=inject(ToastService);readonly context=inject(ContextStore);readonly permissions=inject(PermissionService);readonly state=signal<'loading'|'ready'|'error'>('loading');readonly animal=signal<Animal|null>(null);readonly history=signal<AnimalHistory|null>(null);readonly error=signal<AppError|null>(null);readonly historyError=signal<AppError|null>(null);readonly action=signal<Action>(null);readonly actionError=signal('');readonly pending=signal(false);readonly paddocks=signal<PaddockRef[]>([]);readonly destinationFarms=signal<{farmId:string;farmName:string}[]>([]);readonly conflict=signal(false);readonly created=signal(!!history.state?.['created']);readonly today=new Date().toISOString().slice(0,10);private generation=0;private operationId='';editIdentification='';editName='';editSex='FEMALE';editBirthDate='';destinationPaddock='';destinationFarm='';occurredOn=this.today;notes='';
 constructor(){effect(()=>{this.context.contextVersion();this.load();});}
 get id(){return this.route.snapshot.paramMap.get('animalId')||'';}get reference(){return errorReference(this.error()?.requestId)}get historyReference(){return errorReference(this.historyError()?.requestId)}tone=animalTone;status=(s:Animal['status'])=>statusLabels[s];sex=(s:Animal['sex'])=>sexLabels[s];date=formatDate;
 canOperate(a:Animal){return this.permissions.canMutateHerd()&&a.status==='ACTIVE';}canTransfer(a:Animal){return this.permissions.canTransferHerd()&&a.status==='ACTIVE';}
 load(){const id=this.id;if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id)){this.state.set('error');this.error.set(new AppError('not-found','Animal não encontrado ou indisponível neste contexto.',404,'invalid_id'));return;}const generation=++this.generation;this.state.set('loading');this.conflict.set(false);this.error.set(null);this.history.set(null);this.historyError.set(null);this.api.animal(id).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:a=>{if(generation!==this.generation)return;this.animal.set(a);this.state.set('ready');this.api.history(id).subscribe({next:h=>{if(generation===this.generation)this.history.set(h);},error:e=>{if(generation===this.generation)this.historyError.set(e instanceof AppError?e:null);}});},error:e=>{if(generation!==this.generation)return;this.error.set(e instanceof AppError?e:null);this.state.set('error');}});}
 visibleEvents(){return (this.history()?.items||[]).filter(e=>['CREATED','CORRECTED','SOLD','DECEASED','MOVED','TRANSFERRED_IN','TRANSFERRED_OUT','BORN'].includes(e.type));}
 eventTitle(e:AnimalEvent){return {CREATED:'Identidade criada',CORRECTED:'Dados corrigidos',SOLD:'Venda registrada',DECEASED:'Baixa registrada',MOVED:'Mudança de território',TRANSFERRED_IN:'Custódia recebida',TRANSFERRED_OUT:'Custódia transferida',BORN:'Nascimento registrado'}[e.type]||'Evento do animal';}
 eventSummary(e:AnimalEvent){const d=e.details||{};if(e.type==='MOVED')return `${d['sourcePaddockName']||'Sem piquete'} → ${d['destinationPaddockName']||'Destino registrado'}`;if(e.type==='TRANSFERRED_IN'||e.type==='TRANSFERRED_OUT')return `${d['sourceFarmName']||'Origem protegida'} → ${d['destinationFarmName']||'Destino protegido'}`;if(e.type==='CORRECTED'){const changes=d['changes'] as Record<string,unknown>|undefined;return changes?`${Object.keys(changes).length} ${Object.keys(changes).length===1?'campo corrigido':'campos corrigidos'}.`:'Dados cadastrais atualizados.';}if(e.type==='CREATED')return 'Início do histórico nesta fazenda.';return typeof d['notes']==='string'&&d['notes']?String(d['notes']):'Evento registrado no ciclo de vida.';}
 profileErrorText(){const e=this.error();return e?.kind==='unavailable'?'O serviço está temporariamente indisponível. Tente novamente em instantes.':'O identificador não existe ou não está acessível nesta fazenda.';}
 openCorrection(a:Animal){this.actionError.set('');this.editIdentification=a.identification;this.editName=a.name||'';this.editSex=a.sex;this.editBirthDate=a.birthDate||'';this.action.set('correct');}
 openMovement(){this.resetOperation();this.action.set('move');this.api.paddocks().subscribe({next:p=>this.paddocks.set(p.items),error:()=>this.actionError.set('Não foi possível carregar os piquetes disponíveis.')});}
 openTransfer(){this.resetOperation();this.action.set('transfer');const org=this.context.selectedOrganization();if(org)this.api.accessibleFarms(org.organizationId).subscribe({next:r=>this.destinationFarms.set(r.items.filter(f=>f.farmId!==this.context.selectedFarm()?.farmId)),error:()=>this.actionError.set('Não foi possível carregar as fazendas de destino.')});}
 closeAction(){if(!this.pending())this.action.set(null);}
 saveCorrection(){const a=this.animal();if(!a)return;this.mutate(this.api.correct(a.id,{expectedVersion:a.version,identification:this.editIdentification.trim(),name:this.editName.trim()||null,sex:this.editSex,birthDate:this.editBirthDate||null}),'Dados do animal corrigidos');}
 move(){const a=this.animal();if(!a||!this.destinationPaddock)return;this.mutate(this.api.move(a.id,{operationId:this.operationId,expectedVersion:a.version,destinationPaddockId:this.destinationPaddock,occurredOn:this.occurredOn,notes:this.notes.trim()||null}),'Localização atualizada');}
 transfer(){const a=this.animal();if(!a||!this.destinationFarm)return;this.pending.set(true);this.actionError.set('');this.api.transfer(a.id,{operationId:this.operationId,expectedVersion:a.version,destinationFarmId:this.destinationFarm,destinationPaddockId:null,occurredOn:this.occurredOn,notes:this.notes.trim()||null}).subscribe({next:r=>{this.pending.set(false);this.action.set(null);this.toast.show('success','Custódia transferida',`${a.identification} agora está sob custódia de ${r.destinationFarm.name}.`);void this.router.navigate(['/rebanho/animais']);},error:e=>this.handleMutationError(e)});}
 private mutate(request:ReturnType<HerdApi['correct']>,message:string){this.pending.set(true);this.actionError.set('');request.subscribe({next:a=>{this.pending.set(false);this.action.set(null);this.animal.set(a);this.toast.show('success',message);this.load();},error:e=>this.handleMutationError(e)});}
 private handleMutationError(error:unknown){this.pending.set(false);const e=error instanceof AppError?error:null;if(e?.code==='HERD_VERSION_CONFLICT'){this.action.set(null);this.conflict.set(true);return;}this.actionError.set(e?.code==='HERD_OPERATION_IDEMPOTENCY_CONFLICT'?'Esta tentativa usa uma operação já registrada com dados diferentes.':e?.message||'Não foi possível concluir a ação.');}
 private resetOperation(){this.operationId=newUuid();this.destinationPaddock='';this.destinationFarm='';this.occurredOn=this.today;this.notes='';this.actionError.set('');}
 availablePaddocks(){return this.paddocks().filter(p=>p.id!==this.animal()?.paddock?.id);}
}
