import { ChangeDetectionStrategy, Component, DestroyRef, effect, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ContextStore } from '../../core/context/context.store';
import { localDateOnly } from '../../core/date/date-only';
import { PermissionService } from '../../core/permissions/permission.service';
import { ErrorStateComponent, SkeletonComponent, ToastService } from '../../design-system/feedback/feedback';
import { DialogComponent } from '../../design-system/surfaces/surfaces';
import { AnimalIdentityComponent, formatDate } from './herd.shared';
import { HerdApi } from './herd-api.service';
import { Animal, newUuid } from './herd.models';
import { HealthReport, HealthTreatmentType, healthLabels } from './herd-operations.models';

@Component({selector:'app-health-page',imports:[FormsModule,AnimalIdentityComponent,ErrorStateComponent,SkeletonComponent,DialogComponent],template:`<div class="herd-page operations-page page-enter">
  <header class="page-header"><div><span class="eyebrow">CUIDADO REALIZADO</span><h1>Saúde do rebanho</h1><p>Histórico de vacinações e vermifugações já realizadas.</p></div>@if(permissions.canMutateHerd()){<button class="primary-action" type="button" (click)="openCreate()">Registrar tratamento</button>}</header>
  <section class="metric-strip" aria-label="Resumo de saúde"><div><span>Tratamentos</span><strong>{{report()?.summary?.treatmentsCount||0}}</strong></div><div><span>Animais atendidos</span><strong>{{report()?.summary?.animalsTreated||0}}</strong></div><div><span>Vacinações</span><strong>{{report()?.summary?.countsByTreatmentType?.VACCINATION||0}}</strong></div><div><span>Vermifugações</span><strong>{{report()?.summary?.countsByTreatmentType?.DEWORMING||0}}</strong></div></section>
  <section class="section-frame operational-surface"><div class="surface-tools"><div><span class="section-kicker">HISTÓRICO</span><h2>Tratamentos realizados</h2></div><label>Tipo<select [(ngModel)]="type" (ngModelChange)="page=0;reload()"><option value="">Todos</option><option value="VACCINATION">Vacinação</option><option value="DEWORMING">Vermifugação</option></select></label></div>
    @if(loading()){<div class="list-loading"><gr-skeleton/><gr-skeleton/><gr-skeleton/></div>}@else if(error()){<gr-error-state title="Não foi possível carregar o histórico de saúde" (retry)="reload()"/>}@else if(!report()?.items?.length){<div class="domain-empty"><strong>Nenhum tratamento registrado</strong><p>Vacinações e vermifugações realizadas aparecerão aqui.</p></div>}@else{<div class="responsive-table"><table><thead><tr><th>Animal</th><th>Tratamento</th><th>Data</th><th>Produto</th><th>Protocolo</th><th>Próxima aplicação</th></tr></thead><tbody>@for(item of report()!.items;track item.id){<tr><td><app-animal-identity [animal]="animalRef(item.animal!)"/></td><td><span class="domain-badge">{{healthLabel(item.treatmentType!)}}</span></td><td>{{date(item.occurredOn)}}</td><td>{{item.product||'Não informado'}}</td><td>{{item.protocol||'Não informado'}}</td><td>{{item.nextDueOn?date(item.nextDueOn):'Não definida'}}</td></tr>}</tbody></table></div><nav class="pagination" aria-label="Paginação do histórico"><button type="button" [disabled]="page===0" (click)="page=page-1;reload()">Anterior</button><span>Página {{page+1}} de {{report()!.totalPages||1}}</span><button type="button" [disabled]="page+1>=report()!.totalPages" (click)="page=page+1;reload()">Próxima</button></nav>}
  </section>
  <gr-dialog [open]="creating()" (closed)="closeCreate()"><span dialog-title>Registrar tratamento realizado</span><div class="form-grid compact"><label class="wide batch-toggle"><input type="checkbox" [(ngModel)]="batch"/><span>Aplicar o mesmo tratamento a vários animais</span></label>@if(batch){<label class="wide"><span>Animais</span><select multiple [(ngModel)]="animalIds" size="6">@for(a of animals();track a.id){<option [value]="a.id">{{a.identification}}{{a.name?' · '+a.name:''}}</option>}</select><small>Use Ctrl ou ⌘ para selecionar mais de um.</small></label>}@else{<label><span>Animal</span><select [(ngModel)]="animalId"><option value="">Selecione</option>@for(a of animals();track a.id){<option [value]="a.id">{{a.identification}}{{a.name?' · '+a.name:''}}</option>}</select></label>}<label><span>Tipo</span><select [(ngModel)]="treatmentType"><option value="VACCINATION">Vacinação</option><option value="DEWORMING">Vermifugação</option></select></label><label><span>Data realizada</span><input type="date" [(ngModel)]="occurredOn" [max]="today"/></label><label><span>Próxima aplicação</span><input type="date" [(ngModel)]="nextDueOn" [min]="occurredOn"/></label><label><span>Produto</span><input [(ngModel)]="product" maxlength="160" placeholder="Opcional"/></label><label><span>Protocolo</span><input [(ngModel)]="protocol" maxlength="160" placeholder="Opcional"/></label><label class="wide"><span>Observações</span><textarea [(ngModel)]="notes" maxlength="1000" placeholder="Opcional"></textarea></label>@if(formError()){<p class="form-error wide" role="alert">{{formError()}}</p>}</div><p class="semantic-note">Este registro confirma um cuidado realizado. Atividades planejadas continuam separadas.</p><div dialog-actions><button class="quiet-button" type="button" (click)="closeCreate()">Cancelar</button><button class="primary-action" type="button" [disabled]="saving()||(!batch&&!animalId)||(batch&&!animalIds.length)||!occurredOn" (click)="save()">Registrar tratamento</button></div></gr-dialog>
</div>`,styleUrls:['./herd-page.scss','./operations-page.component.scss'],styles:[`.batch-toggle{display:flex!important;grid-column:1/-1;align-items:center;gap:.6rem}.batch-toggle input{min-height:auto}.form-grid select[multiple]{min-height:9rem;padding:.35rem}.form-grid small{color:var(--color-text-muted);font-weight:400}.pagination{display:flex;align-items:center;justify-content:flex-end;gap:var(--space-3);padding:var(--space-3) var(--space-4);border-top:1px solid var(--color-border);font-size:.75rem}.pagination button{min-height:2rem;border:1px solid var(--color-border);border-radius:var(--radius-sm);background:var(--color-surface)}.pagination button:disabled{opacity:.45}`],changeDetection:ChangeDetectionStrategy.OnPush})
export class HealthPageComponent{
  private readonly api=inject(HerdApi);private readonly context=inject(ContextStore);private readonly destroyRef=inject(DestroyRef);private readonly toast=inject(ToastService);readonly permissions=inject(PermissionService);
  readonly report=signal<HealthReport|null>(null);readonly animals=signal<Animal[]>([]);readonly loading=signal(true);readonly error=signal(false);readonly creating=signal(false);readonly saving=signal(false);readonly formError=signal('');private generation=0;private operationId='';type='';page=0;batch=false;animalId='';animalIds:string[]=[];treatmentType:HealthTreatmentType='VACCINATION';today=localDateOnly();occurredOn=this.today;nextDueOn='';product='';protocol='';notes='';
  constructor(){effect(()=>{this.context.contextVersion();if(this.context.transitionPending()||!this.context.selectedFarm()){this.generation++;this.report.set(null);return}this.reload();});}
  reload(){const generation=++this.generation;this.loading.set(true);this.error.set(false);this.api.healthReport({treatmentType:this.type||undefined,page:this.page}).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:r=>{if(generation===this.generation){this.report.set(r);this.loading.set(false)}},error:()=>{if(generation===this.generation){this.loading.set(false);this.error.set(true)}}});}
  openCreate(){this.operationId=newUuid();this.batch=false;this.animalId='';this.animalIds=[];this.formError.set('');this.creating.set(true);this.api.animals({search:'',sex:'',status:'ACTIVE',page:0,size:100}).subscribe({next:r=>this.animals.set(r.items),error:()=>this.formError.set('Não foi possível carregar os animais ativos.')});}
  closeCreate(){if(!this.saving())this.creating.set(false)}
  save(){const selected=this.animals().filter(a=>(this.batch?this.animalIds:[this.animalId]).includes(a.id));if(!selected.length)return;this.saving.set(true);this.formError.set('');const common={operationId:this.operationId,treatmentType:this.treatmentType,occurredOn:this.occurredOn,product:this.product.trim()||null,protocol:this.protocol.trim()||null,nextDueOn:this.nextDueOn||null,notes:this.notes.trim()||null};const request=this.batch?this.api.recordHealthBatch({...common,animals:selected.map(a=>({id:a.id,expectedVersion:a.version}))}):this.api.recordHealth(selected[0].id,{...common,expectedVersion:selected[0].version});request.subscribe({next:r=>{this.saving.set(false);this.creating.set(false);this.toast.show('success',r.replayed?'Tratamento já registrado':this.batch?'Tratamentos registrados':'Tratamento registrado');this.reload()},error:(error:unknown)=>{this.saving.set(false);const e=error as {status?:number;message?:string};this.formError.set(e.status===409?'Os dados dos animais mudaram. Recarregue e tente novamente.':e.message||'Não foi possível registrar o tratamento.')}})}
  healthLabel=(v:HealthTreatmentType)=>healthLabels[v];date=formatDate;animalRef=(a:{id:string;identification:string;name:string|null})=>({...a,sex:'FEMALE',birthDate:null,status:'ACTIVE',version:0,paddock:null}) as Animal;
}
