import { describe, expect, it, vi } from 'vitest';
import { of } from 'rxjs';
import { ApiClient } from '../../core/api/api-client.service';
import { HerdApi } from './herd-api.service';

describe('HerdApi', () => {
  const setup=()=>{const client={get:vi.fn(()=>of({})),post:vi.fn(()=>of({})),patch:vi.fn(()=>of({}))} as unknown as ApiClient;return{client,api:new HerdApi(client)}};
  it('usa contexto de tenant em todas as leituras operacionais',()=>{const {client,api}=setup();api.animal('a').subscribe();expect(client.get).toHaveBeenCalledWith('/api/v1/herd/animals/a',true);api.paddocks().subscribe();expect(client.get).toHaveBeenLastCalledWith('/api/v1/herd/paddocks?status=ACTIVE&page=0&size=100',true);});
  it('preserva o comando de criação fornecido pelo chamador',()=>{const {client,api}=setup();const body={id:'fixed-id',identification:'BR-01',name:null,sex:'FEMALE',birthDate:null};api.create(body).subscribe();expect(client.post).toHaveBeenCalledWith('/api/v1/herd/animals',body,true);});
  it('envia expectedVersion e operationId sem substituí-los no movimento',()=>{const {client,api}=setup();const body={operationId:'stable',expectedVersion:7,destinationPaddockId:'p',occurredOn:'2026-09-17'};api.move('animal',body).subscribe();expect(client.post).toHaveBeenCalledWith('/api/v1/herd/animals/animal/movements',body,true);});
  it('usa o endpoint atômico real e o campo animalId para lote',()=>{const {client,api}=setup();const body={operationId:'stable',animals:[{animalId:'a',expectedVersion:1}]};api.moveBatch(body).subscribe();expect(client.post).toHaveBeenCalledWith('/api/v1/herd/movements/batch',body,true);});
  it('não envia contexto atual ao consultar fazendas acessíveis',()=>{const {client,api}=setup();api.accessibleFarms('org').subscribe();expect(client.get).toHaveBeenCalledWith('/api/v1/me/organizations/org/farms');});
  it('mapeia pesagem e tratamento para os endpoints de domínio',()=>{const {client,api}=setup();const weight={operationId:'op',expectedVersion:2,weightKg:'412.750',measuredOn:'2026-09-17'};api.recordWeight('animal/1',weight).subscribe();expect(client.post).toHaveBeenCalledWith('/api/v1/herd/animals/animal%2F1/weights',weight,true);const health={operationId:'op-2',expectedVersion:3,treatmentType:'VACCINATION',occurredOn:'2026-09-17'};api.recordHealth('animal',health).subscribe();expect(client.post).toHaveBeenCalledWith('/api/v1/herd/animals/animal/health-treatments',health,true);});
  it('preserva filtros server-side de pendências e agenda',()=>{const {client,api}=setup();api.pendingWork({type:'WEIGHING_DUE',animalId:'a',page:2}).subscribe();expect(client.get).toHaveBeenCalledWith('/api/v1/herd/pending-work?page=2&size=20&type=WEIGHING_DUE&animalId=a',true);api.agenda({source:'DERIVED',type:'CALVING',from:'2026-09-01',to:'2026-09-30'}).subscribe();expect(client.get).toHaveBeenCalledWith('/api/v1/herd/agenda?page=0&size=20&source=DERIVED&type=CALVING&from=2026-09-01&to=2026-09-30',true);});
  it('envia versionamento otimista nas transições de gestação e planner',()=>{const {client,api}=setup();const transition={operationId:'stable',expectedVersion:4,occurredOn:'2026-09-17'};api.confirmPregnancy('pregnancy',transition).subscribe();expect(client.post).toHaveBeenCalledWith('/api/v1/herd/pregnancies/pregnancy/confirmation',transition,true);const planner={operationId:'planner-op',expectedVersion:7};api.completePlanner('item',planner).subscribe();expect(client.post).toHaveBeenCalledWith('/api/v1/herd/planner-items/item/completion',planner,true);});
  it('mantém planner separado dos registros de manejo',()=>{const {client,api}=setup();const body={operationId:'x',type:'VACCINATION',title:'Vacinar lote',scheduledFor:'2026-09-20',animalId:null};api.createPlanner(body).subscribe();expect(client.post).toHaveBeenCalledWith('/api/v1/herd/planner-items',body,true);expect(client.post).not.toHaveBeenCalledWith('/api/v1/herd/health-treatments/batch',expect.anything(),true);});
  it('lê o item exato do planejador antes de uma transição',()=>{const {client,api}=setup();api.plannerItem('item/1').subscribe();expect(client.get).toHaveBeenCalledWith('/api/v1/herd/planner-items/item%2F1',true);});
});
