import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { EmptyStateComponent } from '../../design-system/feedback/feedback';
import { StatusIndicatorComponent, TableComponent } from '../../design-system/data-display/data-display';

@Component({selector:'app-herd-showcase',imports:[FormsModule,EmptyStateComponent,StatusIndicatorComponent,TableComponent],template:`<div class="showcase"><nav aria-label="Cenário visual"><button [class.active]="view()==='list'" (click)="view.set('list')">Lista</button><button [class.active]="view()==='profile'" (click)="view.set('profile')">Perfil</button><button [class.active]="view()==='create'" (click)="view.set('create')">Cadastro</button><button [class.active]="view()==='empty'" (click)="view.set('empty')">Vazio</button></nav>
 @if(view()==='list'){<div class="herd-page"><header class="page-header"><div><span class="eyebrow">REBANHO · Fazenda Santa Helena</span><h1>Animais</h1><p>Identidade, estado e localização do rebanho atual.</p></div><button class="primary-action">Cadastrar animal</button></header><div class="filter"><label>Buscar animal<input placeholder="Identificação ou nome" value="" /></label><label>Sexo<select><option>Todos</option></select></label><label>Estado<select><option>Todos</option></select></label></div><section class="herd-surface"><div class="surface-heading"><div><span class="count">3 animais</span><small>Ordenação operacional estável</small></div></div><gr-table><thead><tr><th>Animal</th><th>Estado</th><th>Sexo</th><th>Território atual</th><th></th></tr></thead><tbody>@for(a of animals;track a.id){<tr [class.terminal]="a.status!=='Ativo'"><td><span class="animal-id"><i></i><span><strong>{{a.id}}</strong><small>{{a.name}}</small></span></span></td><td><gr-status-indicator [tone]="a.tone">{{a.status}}</gr-status-indicator></td><td>{{a.sex}}</td><td><span class="territory"><i></i>{{a.place}}</span></td><td class="arrow">→</td></tr>}</tbody></gr-table></section></div>}
 @if(view()==='profile'){<div class="herd-page profile"><span class="back-link">← Voltar ao rebanho</span><header class="profile-header"><div class="identity-block"><span class="identity-orbit"><i></i></span><div><span class="eyebrow">IDENTIDADE ANIMAL</span><h1>BR-0248</h1><p>Aurora</p></div></div><div class="profile-actions"><button class="secondary-action">Corrigir dados</button><button class="secondary-action">Movimentar</button><button class="primary-action">Transferir</button></div></header><section class="state-strip"><div><span>Estado atual</span><gr-status-indicator tone="success">Ativo</gr-status-indicator></div><div><span>Sexo</span><strong>Fêmea</strong></div><div><span>Nascimento</span><strong>15/03/2024</strong></div><div class="territory-current"><span>Território atual</span><strong>Fazenda Santa Helena</strong><small>› Piquete Norte</small></div></section><div class="detail-grid"><section class="timeline section-frame"><header><div><span class="section-kicker">TRAJETÓRIA</span><h2>Histórico do animal</h2></div><span>4 eventos</span></header><ol>@for(e of events;track e.title){<li><span class="timeline-marker"></span><div class="event"><div><strong>{{e.title}}</strong><time>{{e.date}}</time></div><p>{{e.text}}</p></div></li>}</ol></section><aside class="facts section-frame"><span class="section-kicker">LEITURA ATUAL</span><h2>Dados de identidade</h2><dl><div><dt>Identificação</dt><dd>BR-0248</dd></div><div><dt>Nome</dt><dd>Aurora</dd></div><div><dt>Sexo</dt><dd>Fêmea</dd></div></dl></aside></div></div>}
 @if(view()==='create'){<div class="herd-page"><header class="page-header"><div><span class="eyebrow">NOVA IDENTIDADE</span><h1>Cadastrar animal</h1><p>Registre a identidade essencial. O histórico começa no momento da criação.</p></div></header><form class="focused-form section-frame"><div class="form-intro"><span class="identity-seal"><i></i></span><div><h2>Identificação do animal</h2><p>Use a identificação reconhecida no manejo da fazenda.</p></div></div><div class="form-grid"><label class="wide">Identificação<input value="BR-0251" /></label><label>Nome<input value="Estrela" /></label><label>Sexo<select><option>Fêmea</option></select></label><label>Data de nascimento<input type="date" value="2025-02-12" /></label></div><footer><button class="quiet-button">Cancelar</button><button class="primary-action">Cadastrar animal</button></footer></form></div>}
 @if(view()==='empty'){<div class="herd-page"><header class="page-header"><div><span class="eyebrow">REBANHO · Fazenda Santa Helena</span><h1>Animais</h1><p>Identidade, estado e localização do rebanho atual.</p></div></header><div class="empty-frame"><gr-empty-state title="Nenhum animal corresponde aos filtros" description="Ajuste a busca ou remova um dos filtros ativos."><button class="secondary-action">Limpar filtros</button></gr-empty-state></div></div>}
 </div>`,styleUrl:'./herd-showcase.component.scss',changeDetection:ChangeDetectionStrategy.OnPush})
export class HerdShowcaseComponent{readonly view=signal<'list'|'profile'|'create'|'empty'>('list');readonly animals=[{id:'BR-0248',name:'Aurora',status:'Ativo',sex:'Fêmea',place:'Piquete Norte',tone:'success' as const},{id:'BR-0187',name:'Mimosa',status:'Vendido',sex:'Fêmea',place:'Sem piquete definido',tone:'warning' as const},{id:'BR-0301',name:'Trovão',status:'Ativo',sex:'Macho',place:'Piquete Sul',tone:'success' as const}];readonly events=[{title:'Mudança de território',date:'16/09/2026',text:'Piquete Sul → Piquete Norte'},{title:'Dados corrigidos',date:'02/08/2026',text:'1 campo corrigido.'},{title:'Identidade criada',date:'15/03/2024',text:'Início do histórico nesta fazenda.'}];}
