import { ChangeDetectionStrategy, Component, DestroyRef, effect, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { AppError } from '../../core/api/api.models';
import { ContextStore } from '../../core/context/context.store';
import { PaginationComponent, TableComponent } from '../../design-system/data-display/data-display';
import { EmptyStateComponent, ErrorStateComponent } from '../../design-system/feedback/feedback';
import { HerdApi } from './herd-api.service';
import { MovementPage } from './herd.models';
import { errorReference, formatDate } from './herd.shared';

@Component({selector:'app-movements-page',providers:[HerdApi],imports:[RouterLink,PaginationComponent,TableComponent,EmptyStateComponent,ErrorStateComponent],template:`<div class="herd-page page-enter"><header class="page-header"><div><span class="eyebrow">TERRITÓRIO · {{context.selectedFarm()?.farmName}}</span><h1>Movimentações</h1><p>Histórico de deslocamentos internos do rebanho entre piquetes.</p></div><a class="secondary-action" routerLink="/rebanho/animais">Selecionar animais</a></header>
 @if(state()==='error'){<gr-error-state level="page" title="Não foi possível carregar as movimentações" [description]="error()?.message || 'Tente novamente em instantes.'" [reference]="reference" (retry)="load()"/>}
 @else if(state()==='ready'&&!data()?.items?.length){<div class="empty-frame"><gr-empty-state title="Nenhuma movimentação registrada" description="As mudanças de piquete aparecerão aqui quando forem realizadas pelo perfil ou pela seleção em lote."/></div>}
 @else{<section class="herd-surface"><div class="movement-summary"><div><span>MOVIMENTOS REGISTRADOS</span><strong>{{data()?.summary?.movementCount || 0}}</strong></div><div><span>ANIMAIS MOVIMENTADOS</span><strong>{{data()?.summary?.distinctAnimalsMoved || 0}}</strong></div></div><gr-table [loading]="state()==='loading'"><thead><tr><th>Data</th><th>Animal</th><th>Trajeto</th><th>Observações</th></tr></thead><tbody>@for(item of data()?.items || [];track item.id){<tr><td>{{date(item.occurredOn)}}</td><td><a [routerLink]="['/rebanho/animais',item.animal.id]"><strong>{{item.animal.identification}}</strong>@if(item.animal.name){<small>{{item.animal.name}}</small>}</a></td><td><span class="route"><span>{{item.sourcePaddock?.name || 'Sem piquete'}}</span><i>→</i><strong>{{item.destinationPaddock.name}}</strong></span></td><td>{{item.notes || '—'}}</td></tr>}</tbody></gr-table>@if(data();as result){<gr-pagination [page]="result.page" [totalPages]="result.totalPages" (pageChange)="page.set($event);load()"/>}</section>}</div>`,styleUrl:'./movements-page.component.scss',changeDetection:ChangeDetectionStrategy.OnPush})
export class MovementsPageComponent{private readonly api=inject(HerdApi);private readonly destroyRef=inject(DestroyRef);readonly context=inject(ContextStore);readonly state=signal<'loading'|'ready'|'error'>('loading');readonly data=signal<MovementPage|null>(null);readonly error=signal<AppError|null>(null);readonly page=signal(0);private generation=0;date=formatDate;constructor(){effect(()=>{this.context.contextVersion();this.page.set(0);this.load();});}get reference(){return errorReference(this.error()?.requestId)}load(){const generation=++this.generation;this.state.set('loading');this.api.movements(this.page()).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:value=>{if(generation===this.generation){this.data.set(value);this.state.set('ready');}},error:error=>{if(generation===this.generation){this.error.set(error instanceof AppError?error:null);this.state.set('error');}}});}}
