import { ChangeDetectionStrategy, Component, DestroyRef, effect, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ContextStore } from '../../core/context/context.store';
import { localDateOnly } from '../../core/date/date-only';
import { PermissionService } from '../../core/permissions/permission.service';
import { ErrorStateComponent, SkeletonComponent, ToastService } from '../../design-system/feedback/feedback';
import { DialogComponent } from '../../design-system/surfaces/surfaces';
import { HerdApi } from './herd-api.service';
import { Animal, AnimalSex, newUuid } from './herd.models';
import { Pregnancy, PregnancyTerminationReason, ReproductionReport, ReproductionServiceType, pregnancyLabels, serviceLabels } from './herd-operations.models';
import { formatDate } from './herd.shared';

type Flow='breeding'|'confirm'|'terminate'|'calving'|null;
@Component({selector:'app-reproduction-page',imports:[FormsModule,ErrorStateComponent,SkeletonComponent,DialogComponent],template:`<div class="herd-page operations-page page-enter">
 <header class="page-header"><div><span class="eyebrow">PROCESSO REPRODUTIVO</span><h1>Reprodução</h1><p>Do serviço registrado ao parto, com o estado atual de cada gestação.</p></div>@if(permissions.canMutateHerd()){<div class="profile-actions"><button class="secondary-action" type="button" (click)="openStandaloneCalving()">Registrar parto sem gestação</button><button class="primary-action" type="button" (click)="openBreeding()">Registrar cobertura</button></div>}</header>
 <section class="metric-strip" aria-label="Resumo reprodutivo"><div><span>Serviços</span><strong>{{report()?.summary?.servicesRecorded||0}}</strong></div><div><span>Possíveis gestações</span><strong>{{report()?.summary?.openPossiblePregnancies||0}}</strong></div><div><span>Gestações confirmadas</span><strong>{{report()?.summary?.openConfirmedPregnancies||0}}</strong></div><div><span>Partos</span><strong>{{report()?.summary?.calvings||0}}</strong></div></section>
 <section class="section-frame operational-surface"><div class="surface-tools"><div><span class="section-kicker">LINHA OPERACIONAL</span><h2>Eventos de reprodução</h2></div><label>Situação<select [(ngModel)]="status" (ngModelChange)="page=0;reload()"><option value="">Todas</option><option value="POSSIBLE">Em acompanhamento</option><option value="CONFIRMED">Confirmada</option><option value="CALVED">Parto realizado</option><option value="TERMINATED">Encerrada</option></select></label></div>
 @if(loading()){<div class="list-loading"><gr-skeleton/><gr-skeleton/><gr-skeleton/></div>}@else if(error()){<gr-error-state title="Não foi possível carregar a reprodução" (retry)="reload()"/>}@else if(!report()?.items?.length){<div class="domain-empty"><strong>Nenhum evento reprodutivo registrado</strong><p>Serviços, confirmações e partos aparecerão nesta sequência.</p></div>}@else{<div class="process-list">@for(item of report()!.items;track item.id){<article class="process-card"><div><span class="domain-badge">{{actionLabel(item.action)}}</span><h3>{{item.mother.identification}}{{item.mother.name?' · '+item.mother.name:''}}</h3><p>{{date(item.occurredOn)}} @if(item.expectedCalvingOn){<span>· Parto esperado em {{date(item.expectedCalvingOn)}}</span>}</p><small>@if(item.serviceType){ {{serviceLabel(item.serviceType)}} }@if(item.calfId){ · Cria vinculada }</small></div>@if(permissions.canMutateHerd()&&item.pregnancyId&&item.action==='BREEDING_RECORDED'){<div class="item-actions"><button type="button" (click)="openPregnancy(item.pregnancyId,'confirm')">Confirmar</button><button type="button" (click)="openPregnancy(item.pregnancyId,'terminate')">Encerrar</button></div>}@else if(permissions.canMutateHerd()&&item.pregnancyId&&item.action==='PREGNANCY_CONFIRMED'){<div class="item-actions"><button type="button" (click)="openPregnancy(item.pregnancyId,'terminate')">Encerrar</button><button type="button" (click)="openPregnancy(item.pregnancyId,'calving')">Registrar parto</button></div>}</article>}</div><nav class="pagination" aria-label="Paginação dos eventos"><button type="button" [disabled]="page===0" (click)="page=page-1;reload()">Anterior</button><span>Página {{page+1}} de {{report()!.totalPages||1}}</span><button type="button" [disabled]="page+1>=report()!.totalPages" (click)="page=page+1;reload()">Próxima</button></nav>}
 </section>
 <gr-dialog [open]="flow()==='breeding'" (closed)="close()"><span dialog-title>Registrar serviço reprodutivo</span><div class="form-grid compact"><label><span>Fêmea</span><select [(ngModel)]="motherId"><option value="">Selecione</option>@for(a of females();track a.id){<option [value]="a.id">{{a.identification}}{{a.name?' · '+a.name:''}}</option>}</select></label><label><span>Tipo de serviço</span><select [(ngModel)]="serviceType"><option value="INSEMINATION">Inseminação</option><option value="NATURAL_SERVICE">Monta natural</option></select></label><label><span>Data do serviço</span><input type="date" [(ngModel)]="serviceOn" [max]="today"/></label><label><span>Parto esperado</span><input type="date" [(ngModel)]="expectedCalvingOn" [min]="serviceOn"/></label><label class="wide"><span>Referência do reprodutor</span><input [(ngModel)]="sireReference" maxlength="160" placeholder="Opcional"/></label><label class="wide"><span>Observações</span><textarea [(ngModel)]="notes" maxlength="1000" placeholder="Opcional"></textarea></label>@if(formError()){<p class="form-error wide" role="alert">{{formError()}}</p>}</div><div dialog-actions><button class="quiet-button" type="button" (click)="close()">Cancelar</button><button class="primary-action" type="button" [disabled]="saving()||!motherId||!serviceOn" (click)="saveBreeding()">Registrar serviço</button></div></gr-dialog>
 <gr-dialog [open]="flow()==='confirm'" (closed)="close()"><span dialog-title>Confirmar gestação</span><p>Confirme o diagnóstico da gestação selecionada.</p><label class="standalone-field">Data da confirmação<input type="date" [(ngModel)]="transitionOn" [max]="today"/></label>@if(formError()){<p class="form-error" role="alert">{{formError()}}</p>}<div dialog-actions><button class="quiet-button" type="button" (click)="close()">Cancelar</button><button class="primary-action" type="button" [disabled]="saving()" (click)="confirm()">Confirmar gestação</button></div></gr-dialog>
 <gr-dialog [open]="flow()==='terminate'" (closed)="close()"><span dialog-title>Encerrar acompanhamento</span><div class="form-grid compact"><label><span>Data do encerramento</span><input type="date" [(ngModel)]="transitionOn" [max]="today"/></label><label><span>Motivo</span><select [(ngModel)]="terminationReason"><option value="NOT_PREGNANT">Gestação não confirmada</option><option value="PREGNANCY_LOSS">Perda gestacional</option><option value="ABORTION">Abortamento</option><option value="OTHER">Outro</option></select></label>@if(formError()){<p class="form-error wide" role="alert">{{formError()}}</p>}</div><div dialog-actions><button class="quiet-button" type="button" (click)="close()">Voltar</button><button class="primary-action" type="button" [disabled]="saving()" (click)="terminate()">Encerrar acompanhamento</button></div></gr-dialog>
 <gr-dialog [open]="flow()==='calving'" (closed)="close()"><span dialog-title>Registrar parto e cria</span><div class="form-grid compact">@if(!pregnancy()){<label class="wide"><span>Mãe</span><select [(ngModel)]="motherId"><option value="">Selecione</option>@for(a of females();track a.id){<option [value]="a.id">{{a.identification}}{{a.name?' · '+a.name:''}}</option>}</select></label>}<label><span>Data do parto</span><input type="date" [(ngModel)]="calvedOn" [max]="today"/></label><label><span>Identificação da cria</span><input [(ngModel)]="calfIdentification" maxlength="100"/></label><label><span>Nome da cria</span><input [(ngModel)]="calfName" maxlength="255" placeholder="Opcional"/></label><label><span>Sexo da cria</span><select [(ngModel)]="calfSex"><option value="FEMALE">Fêmea</option><option value="MALE">Macho</option></select></label><label><span>Data de nascimento</span><input type="date" [(ngModel)]="birthDate" [max]="today"/></label>@if(formError()){<p class="form-error wide" role="alert">{{formError()}}</p>}</div><p class="semantic-note">{{pregnancy()?'O parto será vinculado à mãe, à gestação selecionada e à nova cria.':'O backend permite registrar este parto sem uma gestação previamente cadastrada. A mãe e a nova cria serão vinculadas.'}}</p><div dialog-actions><button class="quiet-button" type="button" (click)="close()">Voltar</button><button class="primary-action" type="button" [disabled]="saving()||(!pregnancy()&&!motherId)||!calfIdentification||!birthDate" (click)="calve()">Confirmar parto</button></div></gr-dialog>
</div>`,styleUrls:['./herd-page.scss','./operations-page.component.scss'],styles:[`.process-card h3{margin:.5rem 0 0;font-size:1rem}.standalone-field{display:grid;gap:.35rem;margin:var(--space-4) 0;font-size:.8rem;font-weight:650}.profile-actions{display:flex;flex-wrap:wrap;gap:var(--space-2)}.pagination{display:flex;align-items:center;justify-content:flex-end;gap:var(--space-3);padding:var(--space-3) var(--space-4);border-top:1px solid var(--color-border);font-size:.75rem}.pagination button{min-height:2rem;border:1px solid var(--color-border);border-radius:var(--radius-sm);background:var(--color-surface)}.pagination button:disabled{opacity:.45}`],changeDetection:ChangeDetectionStrategy.OnPush})
export class ReproductionPageComponent{
 private readonly api=inject(HerdApi);private readonly context=inject(ContextStore);private readonly destroyRef=inject(DestroyRef);private readonly toast=inject(ToastService);readonly permissions=inject(PermissionService);readonly report=signal<ReproductionReport|null>(null);readonly females=signal<Animal[]>([]);readonly loading=signal(true);readonly error=signal(false);readonly flow=signal<Flow>(null);readonly pregnancy=signal<Pregnancy|null>(null);readonly saving=signal(false);readonly formError=signal('');private generation=0;private operationId='';status='';page=0;today=localDateOnly();motherId='';serviceType:ReproductionServiceType='INSEMINATION';serviceOn=this.today;expectedCalvingOn='';sireReference='';notes='';transitionOn=this.today;terminationReason:PregnancyTerminationReason='NOT_PREGNANT';calvedOn=this.today;calfIdentification='';calfName='';calfSex:AnimalSex='FEMALE';birthDate=this.today;
 constructor(){effect(()=>{this.context.contextVersion();if(this.context.transitionPending()||!this.context.selectedFarm()){this.generation++;this.report.set(null);return}this.reload()})}
 reload(){const g=++this.generation;this.loading.set(true);this.error.set(false);this.api.reproductionReport({pregnancyStatus:this.status||undefined,page:this.page}).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:r=>{if(g===this.generation){this.report.set(r);this.loading.set(false)}},error:()=>{if(g===this.generation){this.loading.set(false);this.error.set(true)}}})}
 openBreeding(){this.operationId=newUuid();this.formError.set('');this.flow.set('breeding');this.api.animals({search:'',sex:'FEMALE',status:'ACTIVE',page:0,size:100}).subscribe({next:r=>this.females.set(r.items),error:()=>this.formError.set('Não foi possível carregar as fêmeas ativas.')})}
 openStandaloneCalving(){this.operationId=newUuid();this.pregnancy.set(null);this.motherId='';this.calfIdentification='';this.calfName='';this.formError.set('');this.flow.set('calving');this.api.animals({search:'',sex:'FEMALE',status:'ACTIVE',page:0,size:100}).subscribe({next:r=>this.females.set(r.items),error:()=>this.formError.set('Não foi possível carregar as mães disponíveis.')})}
 openPregnancy(id:string,flow:Exclude<Flow,'breeding'|null>){this.formError.set('');this.api.pregnancy(id).subscribe({next:p=>{if(flow==='confirm'&&p.status!=='POSSIBLE'){this.toast.show('warning','A gestação não pode ser confirmada no estado atual');return}if(flow==='terminate'&&!['POSSIBLE','CONFIRMED'].includes(p.status)){this.toast.show('warning','A gestação já está encerrada');return}this.pregnancy.set(p);this.operationId=newUuid();this.flow.set(flow)},error:()=>this.toast.show('error','Não foi possível carregar a gestação')})}
 close(){if(!this.saving())this.flow.set(null)}
 saveBreeding(){const mother=this.females().find(a=>a.id===this.motherId);if(!mother)return;this.run(this.api.breed(mother.id,{operationId:this.operationId,expectedVersion:mother.version,serviceType:this.serviceType,serviceOn:this.serviceOn,sireReference:this.sireReference.trim()||null,expectedCalvingOn:this.expectedCalvingOn||null,notes:this.notes.trim()||null}),'Serviço reprodutivo registrado')}
 confirm(){const p=this.pregnancy();if(p)this.run(this.api.confirmPregnancy(p.id,{operationId:this.operationId,expectedVersion:p.version,occurredOn:this.transitionOn}),'Gestação confirmada')}
 terminate(){const p=this.pregnancy();if(p)this.run(this.api.terminatePregnancy(p.id,{operationId:this.operationId,expectedVersion:p.version,endedOn:this.transitionOn,reason:this.terminationReason}),'Acompanhamento encerrado')}
 calve(){const p=this.pregnancy();const targetMother=p?.motherId||this.motherId;if(!targetMother)return;const mother=this.females().find(a=>a.id===targetMother);const save=(a:Animal)=>this.run(this.api.calve(a.id,{operationId:this.operationId,expectedVersion:a.version,pregnancyId:p?.id||null,expectedPregnancyVersion:p?.version??null,calvedOn:this.calvedOn,calfId:newUuid(),identification:this.calfIdentification.trim(),name:this.calfName.trim()||null,sex:this.calfSex,birthDate:this.birthDate}),'Parto e cria registrados');if(mother)save(mother);else this.api.animal(targetMother).subscribe({next:save,error:()=>this.formError.set('Não foi possível atualizar os dados da mãe.')})}
 private run(request:{subscribe:(observer:{next:(value:unknown)=>void;error:(error:unknown)=>void})=>unknown},message:string){this.saving.set(true);this.formError.set('');request.subscribe({next:()=>{this.saving.set(false);this.flow.set(null);this.toast.show('success',message);this.reload()},error:(error:unknown)=>{this.saving.set(false);const e=error as {status?:number;message?:string};this.formError.set(e.status===409?'Os dados mudaram em outra sessão. Recarregue e tente novamente.':e.message||'Não foi possível concluir a ação.')}})}
 date=formatDate;serviceLabel=(v:ReproductionServiceType)=>serviceLabels[v];pregnancyLabel=(v:Pregnancy['status'])=>pregnancyLabels[v];actionLabel=(v:string)=>({BREEDING_RECORDED:'Serviço registrado',PREGNANCY_CONFIRMED:'Gestação confirmada',PREGNANCY_TERMINATED:'Acompanhamento encerrado',CALVED:'Parto realizado',BORN:'Cria nascida'}[v]||v);
}
