import{signal}from'@angular/core';import{TestBed}from'@angular/core/testing';import{provideRouter}from'@angular/router';import{Observable,Subject,of,throwError}from'rxjs';import{describe,expect,it,vi}from'vitest';
import{AppError,MembershipRole}from'../../core/api/api.models';import{ContextStore}from'../../core/context/context.store';import{ToastService}from'../../design-system/feedback/feedback';import{AdministrationApi}from'./administration-api.service';import{AdminFarm,AdminMember,OrganizationAdmin}from'./administration.models';import{AdministrationPageComponent}from'./administration-page.component';
HTMLDialogElement.prototype.showModal??=function(){this.open=true;};HTMLDialogElement.prototype.close??=function(){this.open=false;};
const organization:OrganizationAdmin={id:'o',name:'Grupo rural',status:'ACTIVE',version:4};
function mocks(){return{organization:vi.fn(():Observable<OrganizationAdmin>=>of(organization)),farms:vi.fn(():Observable<AdminFarm[]>=>of([])),members:vi.fn(():Observable<AdminMember[]>=>of([])),updateOrganization:vi.fn(():Observable<OrganizationAdmin>=>of(organization))};}
async function setup(role:MembershipRole='OWNER',initialize?:(api:ReturnType<typeof mocks>)=>void){const api=mocks();initialize?.(api);const context={contextVersion:signal(0),transitionPending:signal(false),selectedOrganization:signal({organizationId:'o',organizationName:'Grupo',farmScopeMode:'ALL_FARMS'}),selectedFarm:signal({farmId:'f',farmName:'Fazenda Norte'}),role:signal<MembershipRole|null>(role),revalidateAccess:vi.fn(()=>Promise.resolve())};const toast={show:vi.fn()};await TestBed.configureTestingModule({imports:[AdministrationPageComponent],providers:[provideRouter([]),{provide:AdministrationApi,useValue:api},{provide:ContextStore,useValue:context},{provide:ToastService,useValue:toast}]}).compileComponents();const fixture=TestBed.createComponent(AdministrationPageComponent);fixture.detectChanges();await fixture.whenStable();return{fixture,component:fixture.componentInstance,api,context,toast};}
describe('Visão geral administrativa',()=>{
 it.each(['OWNER','ADMIN','MANAGER','OPERATOR','VIEWER'] as MembershipRole[])('%s consulta pessoas e estrutura segundo o contrato público',async role=>{const{fixture,component,api}=await setup(role);expect(api.members).toHaveBeenCalledWith('o',0,100);expect(component.organization()?.name).toBe(organization.name);expect(fixture.nativeElement.querySelector('a[href="/administracao/pessoas"]')).not.toBeNull();if(role!=='OWNER'){component.openEdit();component.organizationName='Outro nome';component.saveOrganization();expect(component.editOpen()).toBe(false);expect(api.updateOrganization).not.toHaveBeenCalled();}});
 it('duplo envio é bloqueado e troca de contexto fecha edição e cancela callback',async()=>{const pending=new Subject<OrganizationAdmin>();const{fixture,component,api,context,toast}=await setup('OWNER',a=>a.updateOrganization.mockReturnValue(pending));component.openEdit();component.organizationName='Nome corrigido';component.saveOrganization();component.saveOrganization();expect(api.updateOrganization).toHaveBeenCalledTimes(1);context.transitionPending.set(true);fixture.detectChanges();expect(pending.observed).toBe(false);expect(component.organization()).toBeNull();expect(component.editOpen()).toBe(false);pending.next(organization);expect(toast.show).not.toHaveBeenCalled();});
 it('erro em uma consulta impede resumo parcial e oferece nova consulta completa',async()=>{const{component,api}=await setup('OWNER',a=>a.farms.mockReturnValue(throwError(()=>new AppError('unavailable','',503,'UNAVAILABLE'))));expect(component.state()).toBe('error');expect(component.organization()).toBeNull();api.farms.mockReturnValue(of([]));component.load();expect(component.state()).toBe('ready');expect(component.organization()).toEqual(organization);});
});
