import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { ContextStore } from '../../core/context/context.store';
import { PermissionService } from '../../core/permissions/permission.service';

@Component({selector:'app-administration-header',imports:[RouterLink,RouterLinkActive],template:`
  <header class="admin-heading"><div><span>ADMINISTRAÇÃO · {{context.selectedOrganization()?.organizationName}}</span><h1>Organização e acessos</h1><p>Você está administrando esta organização. O contexto permanece definido pelo seletor principal do BovNex.</p></div><div class="context-mark"><small>Organização atual</small><strong>{{context.selectedOrganization()?.organizationName}}</strong><span>{{context.selectedFarm()?.farmName||'Nenhuma fazenda selecionada'}}</span></div></header>
  <nav class="admin-tabs" aria-label="Áreas da administração"><a routerLink="/administracao" [routerLinkActiveOptions]="{exact:true}" routerLinkActive="active">Visão geral</a><a routerLink="/administracao/fazendas" routerLinkActive="active">Fazendas</a>@if(permissions.canManageUsers()){<a routerLink="/administracao/pessoas" routerLinkActive="active">Pessoas e acessos</a>}</nav>
`,styles:[`
  :host{display:block}.admin-heading{display:flex;align-items:flex-end;justify-content:space-between;gap:var(--space-8);padding-bottom:var(--space-6);border-bottom:1px solid var(--color-border)}.admin-heading>div:first-child{max-width:43rem}.admin-heading span{font-size:.6875rem;font-weight:740;letter-spacing:.08em;color:var(--color-primary)}h1{margin:.45rem 0 var(--space-2);font-size:clamp(1.75rem,3vw,2.4rem);letter-spacing:-.045em}p{max-width:40rem;margin:0;color:var(--color-text-secondary)}.context-mark{min-width:16rem;display:grid;gap:2px;padding:var(--space-4);border-left:3px solid var(--color-accent);background:var(--color-surface-soft)}.context-mark small,.context-mark span{color:var(--color-text-muted);font-size:.75rem}.context-mark strong{font-size:.9375rem}.admin-tabs{display:flex;gap:var(--space-6);margin-bottom:var(--space-6);border-bottom:1px solid var(--color-border)}.admin-tabs a{position:relative;padding:var(--space-4) 0;color:var(--color-text-secondary);font-size:.875rem;text-decoration:none}.admin-tabs a.active{color:var(--color-primary);font-weight:700}.admin-tabs a.active:after{content:'';position:absolute;right:0;bottom:-1px;left:0;height:2px;background:var(--color-primary)}@media(max-width:46rem){.admin-heading{align-items:stretch;flex-direction:column;gap:var(--space-4)}.context-mark{min-width:0}.admin-tabs{gap:var(--space-4);overflow:auto}.admin-tabs a{white-space:nowrap}}
`],changeDetection:ChangeDetectionStrategy.OnPush})
export class AdministrationHeaderComponent{readonly context=inject(ContextStore);readonly permissions=inject(PermissionService)}
