import { of } from 'rxjs';
import { describe, expect, it, vi } from 'vitest';
import { ApiClient } from '../../core/api/api-client.service';
import { AdministrationApi } from './administration-api.service';

describe('AdministrationApi',()=>{
  it('consulta diretório global e cadastra organização sem contexto de fazenda',()=>{const get=vi.fn(()=>of([])),post=vi.fn(()=>of({}));const api=new AdministrationApi({get,post} as unknown as ApiClient);api.administrativeOrganizations().subscribe();api.createOrganization({id:'o',name:'Grupo rural'}).subscribe();expect(get).toHaveBeenCalledWith('/api/v1/me/administrative-organizations');expect(post).toHaveBeenCalledWith('/api/v1/organizations',{id:'o',name:'Grupo rural'});});
  it('consulta e altera perfil usando exclusivamente o contexto operacional',()=>{const get=vi.fn(()=>of({})),patch=vi.fn(()=>of({}));const api=new AdministrationApi({get,patch} as unknown as ApiClient);api.currentFarm().subscribe();api.updateCurrentFarm({name:'Fazenda Norte',expectedVersion:4}).subscribe();expect(get).toHaveBeenCalledWith('/api/v1/farms/current',true);expect(patch).toHaveBeenCalledWith('/api/v1/farms/current',{name:'Fazenda Norte',expectedVersion:4},true);});
  it('inclui usuário existente com o escopo validado e consulta fazenda individual',()=>{const get=vi.fn(()=>of({})),post=vi.fn(()=>of({}));const api=new AdministrationApi({get,post} as unknown as ApiClient);api.farm('org segura','fazenda segura').subscribe();api.addMember('org-a','user-a',{role:'OPERATOR',scopeMode:'SELECTED_FARMS',farmIds:['f']}).subscribe();expect(get).toHaveBeenCalledWith('/api/v1/organizations/org%20segura/farms/fazenda%20segura');expect(post).toHaveBeenCalledWith('/api/v1/organizations/org-a/members',{userId:'user-a',role:'OPERATOR',farmScopeMode:'SELECTED_FARMS',farmIds:['f']});});
  it('pagina convites de todas as situações e auditoria com filtros opcionais',()=>{const get=vi.fn(()=>of([]));const api=new AdministrationApi({get} as unknown as ApiClient);api.invitations('org-a','',2,25).subscribe();expect(get).toHaveBeenLastCalledWith('/api/v1/organizations/org-a/invitations?page=2&size=25');api.invitations('org-a','EXPIRED',1,25).subscribe();expect(get).toHaveBeenLastCalledWith('/api/v1/organizations/org-a/invitations?status=EXPIRED&page=1&size=25');api.audit('org-a','MEMBER_ROLE_CHANGED','farm-a',3,25).subscribe();expect(get).toHaveBeenLastCalledWith('/api/v1/organizations/org-a/audit?eventType=MEMBER_ROLE_CHANGED&farmId=farm-a&page=3&size=25');});
  it('mantém o tenant somente no caminho validado pelo backend',()=>{const get=vi.fn(()=>of([]));const api=new AdministrationApi({get} as unknown as ApiClient);api.members('org segura',2,25).subscribe();expect(get).toHaveBeenCalledWith('/api/v1/organizations/org%20segura/members?page=2&size=25');});
  it('remove membership com expectedVersion e sem confundir com conta global',()=>{const remove=vi.fn(()=>of(undefined));const api=new AdministrationApi({delete:remove} as unknown as ApiClient);api.revokeMember('org-a','member-a',7).subscribe();expect(remove).toHaveBeenCalledWith('/api/v1/organizations/org-a/members/member-a?expectedVersion=7');});
  it('normaliza ALL_FARMS para uma seleção vazia',()=>{const patch=vi.fn(()=>of({}));const api=new AdministrationApi({patch} as unknown as ApiClient);api.updateMember('org-a','member-a',{role:'MANAGER',scopeMode:'ALL_FARMS',farmIds:['farm-indevida']},3).subscribe();expect(patch).toHaveBeenCalledWith('/api/v1/organizations/org-a/members/member-a',{role:'MANAGER',farmScopeMode:'ALL_FARMS',farmIds:[],expectedVersion:3});});
  it('usa o fluxo oficial de convite por e-mail',()=>{const post=vi.fn(()=>of({}));const api=new AdministrationApi({post} as unknown as ApiClient);api.invite('org-a','pessoa@example.test',{role:'VIEWER',scopeMode:'SELECTED_FARMS',farmIds:['farm-a']}).subscribe();expect(post).toHaveBeenCalledWith('/api/v1/organizations/org-a/invitations',{email:'pessoa@example.test',role:'VIEWER',farmScopeMode:'SELECTED_FARMS',farmIds:['farm-a']});});
});
