import { ChangeDetectionStrategy, Component, DestroyRef, effect, inject, signal, untracked } from '@angular/core';
import { forkJoin } from 'rxjs';
import { FormsModule } from '@angular/forms';
import { ContextStore } from '../../core/context/context.store';
import { ErrorStateComponent, SkeletonComponent } from '../../design-system/feedback/feedback';
import { ContextRequestScope, managementTimestamp } from '../management/management.shared';
import { AdministrationApi } from './administration-api.service';
import { AdminAuditEvent, AdminFarm } from './administration.models';
import { AdministrationHeaderComponent } from './administration-header.component';

export const adminEventLabels:Record<string,string>={ORGANIZATION_CREATED:'Organização criada',ORGANIZATION_CORRECTED:'Organização alterada',FARM_CREATED:'Fazenda criada',FARM_CORRECTED:'Fazenda alterada',MEMBER_ADDED:'Pessoa adicionada',MEMBER_ROLE_CHANGED:'Papel alterado',MEMBER_SCOPE_CHANGED:'Escopo de fazendas alterado',MEMBER_REVOKED:'Acesso revogado',INVITATION_CREATED:'Convite criado',INVITATION_ACCEPTED:'Convite aceito',INVITATION_REVOKED:'Convite cancelado'};
@Component({selector:'app-audit-page',imports:[FormsModule,AdministrationHeaderComponent,ErrorStateComponent,SkeletonComponent],template:`
<div class="admin-page page-enter"><app-administration-header/><section class="section-heading"><div><span>AUDITORIA</span><h2>Histórico administrativo</h2><p>Eventos registrados pelo servidor nesta organização. O histórico operacional permanece no perfil de cada animal.</p></div></section>
<form class="admin-filters" (ngSubmit)="filter()"><label><span>Evento</span><select name="event" [(ngModel)]="eventType"><option value="">Todos</option>@for(option of eventOptions;track option.key){<option [value]="option.key">{{option.label}}</option>}</select></label><label><span>Fazenda</span><select name="farm" [(ngModel)]="farmId"><option value="">Todas</option>@for(farm of farms();track farm.id){<option [value]="farm.id">{{farm.name}}</option>}</select></label><button class="secondary" type="submit" [disabled]="state()==='loading'">Aplicar filtros</button></form>
@if(state()==='loading'){<section class="list-skeleton"><gr-skeleton/><gr-skeleton/><gr-skeleton/></section>}@else if(state()==='error'){<gr-error-state title="Não foi possível carregar a auditoria" description="Recarregue os eventos administrativos." (retry)="load()"/>}@else if(!events().length){<section class="empty-inline"><h3>Nenhum evento encontrado</h3><p>{{eventType||farmId?'Revise os filtros ou consulte outra página.':'Não há eventos administrativos nesta página.'}}</p></section>}@else{<section class="admin-audit-list" aria-label="Eventos administrativos">@for(event of events();track event.id){<article><header><strong>{{labels[event.eventType]||'Evento administrativo'}}</strong><time [attr.datetime]="event.recordedAt">{{timestamp(event.recordedAt)}}</time></header><dl><div><dt>Fazenda</dt><dd>{{farmName(event.farmId)}}</dd></div><div><dt>Responsável</dt><dd>{{event.actorUserId===context.user()?.userId?'Você':event.actorUserId}}</dd></div>@if(event.targetUserId){<div><dt>Usuário relacionado</dt><dd>{{event.targetUserId===context.user()?.userId?'Você':event.targetUserId}}</dd></div>}@if(detail(event)){<div><dt>Registro</dt><dd>{{detail(event)}}</dd></div>}</dl><small>Identificador do evento: {{event.id}}</small></article>}</section>}
<nav class="simple-pagination" aria-label="Paginação da auditoria"><span>Página {{page+1}} · até {{pageSize}} eventos por página</span><div><button class="secondary" type="button" [disabled]="page===0||state()==='loading'" (click)="changePage(page-1)">Anterior</button><button class="secondary" type="button" [disabled]="events().length<pageSize||state()==='loading'" (click)="changePage(page+1)">Próxima</button></div></nav></div>
`,styleUrl:'./administration.scss',changeDetection:ChangeDetectionStrategy.OnPush})
export class AuditPageComponent{
 private readonly api=inject(AdministrationApi);private readonly scope=new ContextRequestScope(inject(DestroyRef));readonly context=inject(ContextStore);readonly labels=adminEventLabels;readonly eventOptions=Object.entries(adminEventLabels).map(([key,label])=>({key,label}));readonly timestamp=managementTimestamp;
 readonly state=signal<'loading'|'ready'|'error'>('loading');readonly events=signal<AdminAuditEvent[]>([]);readonly farms=signal<AdminFarm[]>([]);page=0;readonly pageSize=25;eventType='';farmId='';private queryRevision=0;
 constructor(){effect(()=>{this.context.contextVersion();this.context.selectedOrganization();const pending=this.context.transitionPending();untracked(()=>{this.scope.reset();this.queryRevision++;this.events.set([]);this.farms.set([]);this.page=0;this.eventType='';this.farmId='';this.state.set('loading');if(!pending)this.load();});});}
 load(){const org=this.context.selectedOrganization();if(!org||this.context.transitionPending()){this.state.set('ready');return;}const revision=++this.queryRevision;this.state.set('loading');this.scope.run(forkJoin({events:this.api.audit(org.organizationId,this.eventType,this.farmId,this.page,this.pageSize),farms:this.api.farms(org.organizationId)}),data=>{if(revision!==this.queryRevision)return;this.events.set(data.events);this.farms.set(data.farms);this.state.set('ready');},()=>{if(revision===this.queryRevision)this.state.set('error');});}
 filter(){this.page=0;this.load();}changePage(page:number){this.page=Math.max(0,page);this.load();}
 farmName(id:string|null){return id?(this.farms().find(f=>f.id===id)?.name||'Fazenda indisponível'):'Organização';}
 detail(event:AdminAuditEvent){try{const details:unknown=JSON.parse(event.details);if(details&&typeof details==='object'&&'name' in details&&typeof details.name==='string')return details.name;}catch{/* Eventos antigos sem detalhes legíveis continuam disponíveis. */}return '';}
}
