import{signal}from'@angular/core';import{TestBed}from'@angular/core/testing';import{provideRouter}from'@angular/router';import{Observable,Subject,of,throwError}from'rxjs';import{describe,expect,it,vi}from'vitest';
import{AppError}from'../../core/api/api.models';import{ContextStore}from'../../core/context/context.store';import{AdministrationApi}from'./administration-api.service';import{AdminAuditEvent,AdminFarm}from'./administration.models';import{AuditPageComponent}from'./audit-page.component';
const event:AdminAuditEvent={id:'e',farmId:'f',actorUserId:'u',targetUserId:null,eventType:'FARM_CREATED',details:'{"name":"Fazenda Norte","unknown":"Não exibir"}',recordedAt:'2026-09-29T03:00:00Z'};
function mocks(){return{audit:vi.fn(():Observable<AdminAuditEvent[]>=>of([event])),farms:vi.fn(():Observable<AdminFarm[]>=>of([{id:'f',organizationId:'o',name:'Fazenda Norte',status:'ACTIVE',version:0}]))};}
async function setup(initialize?:(api:ReturnType<typeof mocks>)=>void){const api=mocks();initialize?.(api);const context={contextVersion:signal(0),transitionPending:signal(false),selectedOrganization:signal({organizationId:'o',organizationName:'Grupo'}),selectedFarm:signal({farmId:'f',farmName:'Fazenda Norte'}),role:signal('OWNER'),user:signal({userId:'u'})};await TestBed.configureTestingModule({imports:[AuditPageComponent],providers:[provideRouter([]),{provide:AdministrationApi,useValue:api},{provide:ContextStore,useValue:context}]}).compileComponents();const fixture=TestBed.createComponent(AuditPageComponent);fixture.detectChanges();await fixture.whenStable();return{fixture,component:fixture.componentInstance,api,context};}
describe('Auditoria administrativa contextual',()=>{
 it('envia filtros e paginação, sem expor detalhes JSON desconhecidos',async()=>{const{fixture,component,api}=await setup();expect(fixture.nativeElement.textContent).toContain('Fazenda criada');expect(fixture.nativeElement.textContent).not.toContain('Não exibir');component.eventType='FARM_CREATED';component.farmId='f';component.filter();component.changePage(2);expect(api.audit).toHaveBeenLastCalledWith('o','FARM_CREATED','f',2,25);expect(component.farmName('f')).toBe('Fazenda Norte');expect(component.detail({...event,details:'inválido'})).toBe('');});
 it('troca cancela histórico e elimina referências da organização anterior',async()=>{const pending=new Subject<AdminAuditEvent[]>();const{fixture,component,context}=await setup(a=>a.audit.mockReturnValue(pending));context.transitionPending.set(true);fixture.detectChanges();expect(pending.observed).toBe(false);expect(component.events()).toEqual([]);expect(component.farms()).toEqual([]);expect(component.farmId).toBe('');expect(component.page).toBe(0);pending.next([event]);expect(component.events()).toEqual([]);});
 it('falha nas referências tem erro e retry completo, sem sucesso parcial',async()=>{const{component,api}=await setup(a=>a.farms.mockReturnValue(throwError(()=>new AppError('unavailable','',503,'UNAVAILABLE'))));expect(component.state()).toBe('error');api.farms.mockReturnValue(of([]));component.load();expect(component.state()).toBe('ready');expect(component.events()).toEqual([event]);});
});
