import{signal}from'@angular/core';import{TestBed}from'@angular/core/testing';import{provideRouter}from'@angular/router';import{Observable,Subject,of,throwError}from'rxjs';import{describe,expect,it,vi}from'vitest';
import{AppError,MembershipRole}from'../../core/api/api.models';import{ContextStore}from'../../core/context/context.store';import{ToastService}from'../../design-system/feedback/feedback';import{AdministrationApi}from'./administration-api.service';import{AdminFarm}from'./administration.models';import{CurrentFarmPageComponent}from'./current-farm-page.component';
HTMLDialogElement.prototype.showModal??=function(){this.open=true;};HTMLDialogElement.prototype.close??=function(){this.open=false;};
const farm:AdminFarm={id:'f',organizationId:'o',name:'Fazenda Norte',status:'ACTIVE',version:9};
function mocks(){return{currentFarm:vi.fn(():Observable<AdminFarm>=>of(farm)),updateCurrentFarm:vi.fn(():Observable<AdminFarm>=>of(farm))};}
async function setup(role:MembershipRole='OWNER',initialize?:(api:ReturnType<typeof mocks>)=>void){const api=mocks();initialize?.(api);const context={contextVersion:signal(0),transitionPending:signal(false),selectedOrganization:signal({organizationId:'o',organizationName:'Grupo'}),selectedFarm:signal({farmId:'f',farmName:'Fazenda Norte'}),role:signal<MembershipRole|null>(role),revalidateAccess:vi.fn(()=>Promise.resolve())};const toast={show:vi.fn()};await TestBed.configureTestingModule({imports:[CurrentFarmPageComponent],providers:[provideRouter([]),{provide:AdministrationApi,useValue:api},{provide:ContextStore,useValue:context},{provide:ToastService,useValue:toast}]}).compileComponents();const fixture=TestBed.createComponent(CurrentFarmPageComponent);fixture.detectChanges();await fixture.whenStable();return{fixture,component:fixture.componentInstance,api,context,toast};}
describe('Perfil da fazenda selecionada',()=>{
 it.each(['MANAGER','OPERATOR','VIEWER'] as MembershipRole[])('%s consulta sem renomear fazenda',async role=>{const{component,api}=await setup(role);expect(component.farm()?.name).toBe(farm.name);component.openEditor();component.name='Outro nome';component.prepare();component.save();expect(component.editor()).toBe(false);expect(api.updateCurrentFarm).not.toHaveBeenCalled();});
 it.each(['OWNER','ADMIN'] as MembershipRole[])('%s confirma nome e preserva controle de versão',async role=>{const{component,api}=await setup(role);component.openEditor();component.name=' Fazenda Nova ';component.save();expect(api.updateCurrentFarm).not.toHaveBeenCalled();component.prepare();component.save();expect(api.updateCurrentFarm).toHaveBeenCalledWith({name:'Fazenda Nova',expectedVersion:9});});
 it('troca cancela escrita e apaga perfil anterior sem feedback tardio',async()=>{const pending=new Subject<AdminFarm>();const{fixture,component,api,context,toast}=await setup('OWNER',a=>a.updateCurrentFarm.mockReturnValue(pending));component.openEditor();component.name='Outro nome';component.prepare();component.save();component.save();expect(api.updateCurrentFarm).toHaveBeenCalledTimes(1);context.transitionPending.set(true);fixture.detectChanges();expect(pending.observed).toBe(false);expect(component.farm()).toBeNull();expect(component.editor()).toBe(false);pending.next(farm);expect(toast.show).not.toHaveBeenCalled();});
 it('falha de consulta oferece retry e não abre edição sem perfil',async()=>{const{component,api}=await setup('OWNER',a=>a.currentFarm.mockReturnValue(throwError(()=>new AppError('unavailable','',503,'UNAVAILABLE'))));expect(component.state()).toBe('error');component.openEditor();expect(component.editor()).toBe(false);api.currentFarm.mockReturnValue(of(farm));component.load();expect(component.state()).toBe('ready');});
});
