import { ChangeDetectionStrategy, Component, DestroyRef, computed, effect, inject, signal, untracked } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ContextRequestScope } from '../management/management.shared';
import { LucideDynamicIcon } from '@lucide/angular';
import { AppError } from '../../core/api/api.models';
import { ContextStore } from '../../core/context/context.store';
import { PermissionService } from '../../core/permissions/permission.service';
import { ErrorStateComponent, SkeletonComponent, ToastService } from '../../design-system/feedback/feedback';
import { DialogComponent } from '../../design-system/surfaces/surfaces';
import { administrationError } from './administration.shared';
import { AdministrationApi } from './administration-api.service';
import { AdminFarm, statusLabels } from './administration.models';
import { AdministrationHeaderComponent } from './administration-header.component';

@Component({selector:'app-farms-page',imports:[FormsModule,LucideDynamicIcon,AdministrationHeaderComponent,DialogComponent,SkeletonComponent,ErrorStateComponent],template:`
<div class="admin-page page-enter"><app-administration-header/><section class="section-heading"><div><span>FAZENDAS</span><h2>Estrutura da organização</h2><p>Cadastros administrativos das fazendas, sem misturar a operação do rebanho.</p></div>@if(permissions.canManageFarms()){<button class="primary" type="button" (click)="openCreate()"><svg lucideIcon="plus"></svg>Nova fazenda</button>}</section>
<section class="admin-filters" aria-label="Filtros de fazendas"><label><span>Buscar pelo nome</span><input [ngModel]="search()" (ngModelChange)="search.set($event);page.set(0)"/></label><label><span>Situação</span><select [ngModel]="filterStatus()" (ngModelChange)="filterStatus.set($event);page.set(0)"><option value="">Todas</option><option value="ACTIVE">Ativa</option><option value="INACTIVE">Inativa</option><option value="ARCHIVED">Arquivada</option></select></label></section>
@if(state()==='loading'){<section class="list-skeleton"><gr-skeleton/><gr-skeleton/><gr-skeleton/></section>}
@else if(state()==='error'){<gr-error-state title="Não foi possível carregar as fazendas" description="Recarregue para consultar a estrutura desta organização." (retry)="load()"/>}
@else if(!filtered().length){<section class="empty-inline"><h3>{{farms().length?'Nenhuma fazenda encontrada':'Nenhuma fazenda cadastrada'}}</h3><p>{{farms().length?'Revise os filtros para consultar outros cadastros.':'Esta organização ainda não possui fazendas.'}}</p>@if(permissions.canManageFarms()&&!farms().length){<button class="primary" type="button" (click)="openCreate()">Cadastrar primeira fazenda</button>}</section>}
@else{<section class="farm-list" aria-label="Fazendas da organização">@for(farm of visible();track farm.id){<article><div class="farm-symbol" aria-hidden="true"><svg lucideIcon="land-plot"></svg></div><div><strong>{{farm.name}}</strong><span>Cadastro administrativo</span></div><span class="status" [class.muted]="farm.status!=='ACTIVE'">{{statusLabels[farm.status]||farm.status}}</span><button class="secondary" type="button" (click)="openEdit(farm)">{{permissions.canManageFarms()?'Editar':'Ver detalhes'}}</button></article>}</section><nav class="simple-pagination" aria-label="Paginação de fazendas"><span>{{filtered().length}} {{filtered().length===1?'fazenda':'fazendas'}} · página {{page()+1}}</span><div><button class="secondary" type="button" [disabled]="page()===0" (click)="page.set(page()-1)">Anterior</button><button class="secondary" type="button" [disabled]="(page()+1)*pageSize>=filtered().length" (click)="page.set(page()+1)">Próxima</button></div></nav>}
</div>
<gr-dialog [open]="dialogOpen()" (closed)="closeDialog()"><strong dialog-title>{{editing()?'Cadastro da fazenda':'Nova fazenda'}}</strong>@if(editorLoading()){<gr-skeleton/>}@else if(editorFailed()){<p class="form-error" role="alert">Não foi possível consultar o cadastro atual.</p><button class="secondary" type="button" (click)="retryEditor()">Tentar novamente</button>}@else if(review()){<section class="confirmation"><h3>Confirmar cadastro</h3><p><strong>{{farmName.trim()}}</strong> · {{statusLabels[farmStatus]}}</p><p>{{farmStatus==='ACTIVE'?'A fazenda ficará disponível conforme o escopo de cada pessoa.':'A fazenda deixará de aparecer no seletor de operação. O acesso atual será revalidado.'}}</p><p>As alterações preservam o histórico da fazenda.</p></section>}@else{<form id="farm-form" (ngSubmit)="prepare()"><fieldset [disabled]="!permissions.canManageFarms()"><label><span>Nome da fazenda *</span><input name="farmName" [(ngModel)]="farmName" maxlength="160" required autofocus/></label>@if(editing()){<fieldset><legend>Situação *</legend><label class="choice"><input type="radio" name="farmStatus" [(ngModel)]="farmStatus" value="ACTIVE"/><span><strong>Ativa</strong><small>Disponível para acesso e operação.</small></span></label><label class="choice"><input type="radio" name="farmStatus" [(ngModel)]="farmStatus" value="INACTIVE"/><span><strong>Inativa</strong><small>Deixa de aparecer nos contextos acessíveis.</small></span></label><label class="choice"><input type="radio" name="farmStatus" [(ngModel)]="farmStatus" value="ARCHIVED"/><span><strong>Arquivada</strong><small>Preserva o histórico e retira a fazenda do seletor de operação.</small></span></label></fieldset>@if(farmStatus!==editing()!.status){<div class="impact-note"><strong>Consequência desta alteração</strong><p>{{farmStatus!=='ACTIVE'?'Pessoas não poderão selecionar esta fazenda. O contexto atual será revalidado.':'A fazenda voltará a ficar disponível conforme o escopo de cada pessoa.'}}</p></div>}}</fieldset></form>}@if(formError()){<p class="form-error" role="alert">{{formError()}}</p>@if(editing()){<button class="secondary" type="button" (click)="retryEditor()" [disabled]="saving()">Recarregar cadastro</button>}}<div dialog-actions><button class="secondary" type="button" (click)="closeDialog()">Cancelar</button>@if(permissions.canManageFarms()&&!editorLoading()&&!editorFailed()){@if(review()){<button class="secondary" type="button" (click)="review.set(false)" [disabled]="saving()">Voltar</button><button class="primary" type="button" (click)="save()" [disabled]="saving()">{{saving()?'Salvando…':'Confirmar cadastro'}}</button>}@else{<button class="primary" type="submit" form="farm-form">Revisar cadastro</button>}}</div></gr-dialog>
`,styleUrl:'./administration.scss',changeDetection:ChangeDetectionStrategy.OnPush})
export class FarmsPageComponent{
  private readonly api=inject(AdministrationApi);private readonly context=inject(ContextStore);private readonly destroyRef=inject(DestroyRef);private readonly toast=inject(ToastService);readonly permissions=inject(PermissionService);readonly statusLabels=statusLabels;
  readonly state=signal<'loading'|'ready'|'error'>('loading');readonly farms=signal<AdminFarm[]>([]);readonly editing=signal<AdminFarm|null>(null);readonly dialogOpen=signal(false);readonly saving=signal(false);readonly formError=signal('');farmName='';farmStatus='ACTIVE';private generation=0;private createId='';private editorRevision=0;private readonly scope=new ContextRequestScope(this.destroyRef);readonly editorLoading=signal(false);readonly editorFailed=signal(false);readonly review=signal(false);readonly search=signal('');readonly filterStatus=signal('');readonly page=signal(0);readonly pageSize=20;readonly filtered=computed(()=>this.farms().filter(f=>(!this.filterStatus()||f.status===this.filterStatus())&&f.name.toLocaleLowerCase('pt-BR').includes(this.search().trim().toLocaleLowerCase('pt-BR'))));readonly visible=computed(()=>this.filtered().slice(this.page()*this.pageSize,(this.page()+1)*this.pageSize));
  constructor(){effect(()=>{this.context.contextVersion();this.context.selectedOrganization();const pending=this.context.transitionPending();untracked(()=>{this.scope.reset();this.generation++;this.editorRevision++;this.farms.set([]);this.editing.set(null);this.dialogOpen.set(false);this.saving.set(false);this.review.set(false);this.editorLoading.set(false);this.editorFailed.set(false);this.formError.set('');this.farmName='';this.farmStatus='ACTIVE';this.createId='';this.page.set(0);this.search.set('');this.filterStatus.set('');this.state.set('loading');if(!pending)this.load();});});}
  load(){const organization=this.context.selectedOrganization();if(!organization){this.farms.set([]);this.state.set('ready');return;}const current=++this.generation;this.state.set('loading');this.scope.run(this.api.farms(organization.organizationId),value=>{if(current===this.generation){this.farms.set(value);this.state.set('ready');}},()=>{if(current===this.generation)this.state.set('error');})}
  openCreate(){if(!this.permissions.canManageFarms()||this.context.transitionPending())return;this.editorRevision++;this.createId=crypto.randomUUID();this.editing.set(null);this.farmName='';this.farmStatus='ACTIVE';this.formError.set('');this.editorLoading.set(false);this.editorFailed.set(false);this.review.set(false);this.dialogOpen.set(true)}
  openEdit(farm:AdminFarm){if(this.context.transitionPending())return;this.editing.set(farm);this.dialogOpen.set(true);this.review.set(false);this.formError.set('');this.retryEditor()}
  retryEditor(){if(this.saving()||this.context.transitionPending())return;this.review.set(false);this.formError.set('');const org=this.context.selectedOrganization(),farm=this.editing();if(!org||!farm)return;const revision=++this.editorRevision;this.editorLoading.set(true);this.editorFailed.set(false);this.scope.run(this.api.farm(org.organizationId,farm.id),value=>{if(revision!==this.editorRevision||!this.dialogOpen())return;this.editing.set(value);this.farmName=value.name;this.farmStatus=value.status;this.editorLoading.set(false);},()=>{if(revision!==this.editorRevision||!this.dialogOpen())return;this.editorLoading.set(false);this.editorFailed.set(true);});}
  closeDialog(){if(!this.saving()){this.editorRevision++;this.dialogOpen.set(false);this.review.set(false);}}
  prepare(){if(!this.permissions.canManageFarms()||this.editorLoading()||this.editorFailed()||this.saving())return;if(!this.farmName.trim()||this.farmName.trim().length>160){this.formError.set('Informe um nome com até 160 caracteres.');return;}this.formError.set('');this.review.set(true);}
  save(){if(this.saving()||!this.review()||!this.permissions.canManageFarms()||this.context.transitionPending()||this.editorLoading()||this.editorFailed())return;const organization=this.context.selectedOrganization();const name=this.farmName.trim();if(!organization||!name){this.formError.set('Nome da fazenda é obrigatório.');return;}this.saving.set(true);this.formError.set('');const farm=this.editing();const request=farm?this.api.updateFarm(organization.organizationId,farm.id,{name,status:this.farmStatus,expectedVersion:farm.version}):this.api.createFarm(organization.organizationId,{id:this.createId,name});this.scope.run(request,value=>{this.farms.update(items=>farm?items.map(item=>item.id===value.id?value:item):[...items,value].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR')));this.saving.set(false);this.dialogOpen.set(false);this.toast.show('success',farm?'Fazenda atualizada':'Fazenda criada',`${value.name} está ${value.status==='ACTIVE'?'disponível':'atualizada'} na organização.`);void this.context.revalidateAccess();},error=>{this.saving.set(false);this.formError.set(administrationError(error,'Não foi possível salvar a fazenda.'));})}
}
