import { ChangeDetectionStrategy, Component, DestroyRef, effect, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { LucideDynamicIcon } from '@lucide/angular';
import { AppError } from '../../core/api/api.models';
import { ContextStore } from '../../core/context/context.store';
import { PermissionService } from '../../core/permissions/permission.service';
import { ErrorStateComponent, SkeletonComponent, ToastService } from '../../design-system/feedback/feedback';
import { DialogComponent } from '../../design-system/surfaces/surfaces';
import { AdministrationApi } from './administration-api.service';
import { AdminFarm, statusLabels } from './administration.models';
import { AdministrationHeaderComponent } from './administration-header.component';

@Component({selector:'app-farms-page',imports:[FormsModule,LucideDynamicIcon,AdministrationHeaderComponent,DialogComponent,SkeletonComponent,ErrorStateComponent],template:`
<div class="admin-page page-enter"><app-administration-header/><section class="section-heading"><div><span>FAZENDAS</span><h2>Estrutura da organização</h2><p>Cadastros administrativos das fazendas, sem misturar a operação do rebanho.</p></div>@if(permissions.canManageFarms()){<button class="primary" type="button" (click)="openCreate()"><svg lucideIcon="plus"></svg>Nova fazenda</button>}</section>
@if(state()==='loading'){<section class="list-skeleton"><gr-skeleton/><gr-skeleton/><gr-skeleton/></section>}
@else if(state()==='error'){<gr-error-state title="Não foi possível carregar as fazendas" description="Recarregue para consultar a estrutura desta organização." (retry)="load()"/>}
@else if(!farms().length){<section class="empty-inline"><h3>Nenhuma fazenda cadastrada</h3><p>Esta organização ainda não possui fazendas.</p>@if(permissions.canManageFarms()){<button class="primary" type="button" (click)="openCreate()">Cadastrar primeira fazenda</button>}</section>}
@else{<section class="farm-list" aria-label="Fazendas da organização">@for(farm of farms();track farm.id){<article><div class="farm-symbol" aria-hidden="true"><svg lucideIcon="land-plot"></svg></div><div><strong>{{farm.name}}</strong><span>Cadastro administrativo</span></div><span class="status" [class.muted]="farm.status!=='ACTIVE'">{{statusLabels[farm.status]||farm.status}}</span>@if(permissions.canManageFarms()){<button class="secondary" type="button" (click)="openEdit(farm)">Editar</button>}</article>}</section>}
</div>
<gr-dialog [open]="dialogOpen()" (closed)="closeDialog()"><strong dialog-title>{{editing()?'Editar fazenda':'Nova fazenda'}}</strong><form id="farm-form" (ngSubmit)="save()"><label><span>Nome da fazenda</span><input name="farmName" [(ngModel)]="farmName" maxlength="160" required autofocus/></label>@if(editing()){<fieldset><legend>Situação</legend><label class="choice"><input type="radio" name="farmStatus" [(ngModel)]="farmStatus" value="ACTIVE"/><span><strong>Ativa</strong><small>Disponível para acesso e operação.</small></span></label><label class="choice"><input type="radio" name="farmStatus" [(ngModel)]="farmStatus" value="INACTIVE"/><span><strong>Inativa</strong><small>Deixa de aparecer nos contextos acessíveis.</small></span></label></fieldset>@if(farmStatus!==editing()!.status){<div class="impact-note"><strong>Consequência desta alteração</strong><p>{{farmStatus==='INACTIVE'?'Pessoas não poderão selecionar esta fazenda. O contexto atual será revalidado.':'A fazenda voltará a ficar disponível conforme o escopo de cada pessoa.'}}</p></div>}}@if(formError()){<p class="form-error" role="alert">{{formError()}}</p>}</form><div dialog-actions><button class="secondary" type="button" (click)="closeDialog()">Cancelar</button><button class="primary" type="submit" form="farm-form" [disabled]="saving()">{{saving()?'Salvando…':editing()?'Salvar alterações':'Criar fazenda'}}</button></div></gr-dialog>
`,styleUrl:'./administration.scss',changeDetection:ChangeDetectionStrategy.OnPush})
export class FarmsPageComponent{
  private readonly api=inject(AdministrationApi);private readonly context=inject(ContextStore);private readonly destroyRef=inject(DestroyRef);private readonly toast=inject(ToastService);readonly permissions=inject(PermissionService);readonly statusLabels=statusLabels;
  readonly state=signal<'loading'|'ready'|'error'>('loading');readonly farms=signal<AdminFarm[]>([]);readonly editing=signal<AdminFarm|null>(null);readonly dialogOpen=signal(false);readonly saving=signal(false);readonly formError=signal('');farmName='';farmStatus='ACTIVE';private generation=0;
  constructor(){effect(()=>{this.context.contextVersion();this.context.selectedOrganization();if(!this.context.transitionPending())this.load();});}
  load(){const organization=this.context.selectedOrganization();if(!organization){this.farms.set([]);this.state.set('ready');return;}const current=++this.generation;this.state.set('loading');this.api.farms(organization.organizationId).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:value=>{if(current===this.generation){this.farms.set(value);this.state.set('ready');}},error:()=>{if(current===this.generation)this.state.set('error');}})}
  openCreate(){this.editing.set(null);this.farmName='';this.farmStatus='ACTIVE';this.formError.set('');this.dialogOpen.set(true)}openEdit(farm:AdminFarm){this.editing.set(farm);this.farmName=farm.name;this.farmStatus=farm.status;this.formError.set('');this.dialogOpen.set(true)}closeDialog(){if(!this.saving())this.dialogOpen.set(false)}
  save(){const organization=this.context.selectedOrganization();const name=this.farmName.trim();if(!organization||!name){this.formError.set('Nome da fazenda é obrigatório.');return;}this.saving.set(true);this.formError.set('');const farm=this.editing();const request=farm?this.api.updateFarm(organization.organizationId,farm.id,{name,status:this.farmStatus,expectedVersion:farm.version}):this.api.createFarm(organization.organizationId,{id:crypto.randomUUID(),name});request.pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:value=>{this.farms.update(items=>farm?items.map(item=>item.id===value.id?value:item):[...items,value].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR')));this.saving.set(false);this.dialogOpen.set(false);this.toast.show('success',farm?'Fazenda atualizada':'Fazenda criada',`${value.name} está ${value.status==='ACTIVE'?'disponível':'atualizada'} na organização.`);void this.context.revalidateAccess();},error:error=>{this.saving.set(false);this.formError.set(error instanceof AppError&&error.kind==='conflict'?'Esta fazenda foi atualizada em outra sessão. Recarregue os dados.':'Não foi possível salvar a fazenda.');}})}
}
