import { ChangeDetectionStrategy, Component, DestroyRef, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ActivatedRoute, Router } from '@angular/router';
import { AppError } from '../../core/api/api.models';
import { ContextStore } from '../../core/context/context.store';
import { AdministrationApi } from './administration-api.service';

@Component({selector:'app-invitation-acceptance-page',template:`<main class="invitation-page"><section><span class="brand-mark" aria-hidden="true"><i></i></span><p class="eyebrow">BOVNEX · CONVITE</p><h1>Entrar em uma organização</h1><p>Ao aceitar, seu acesso será vinculado à conta autenticada. O papel e as fazendas permitidas foram definidos por quem enviou o convite.</p>@if(state()==='error'){<div class="error" role="alert"><strong>Não foi possível aceitar o convite</strong><span>{{message()}}</span></div>}@if(state()==='success'){<div class="success" role="status"><strong>Convite aceito</strong><span>Seu novo acesso já está disponível.</span></div>}@else{<button type="button" [disabled]="state()==='loading'||!token" (click)="accept()">{{state()==='loading'?'Aceitando…':'Aceitar convite'}}</button>}</section></main>`,styles:[`
  .invitation-page{min-height:100dvh;display:grid;place-items:center;padding:var(--space-5);background:var(--color-background)}section{width:min(31rem,100%);padding:var(--space-8);border:1px solid var(--color-border);border-radius:var(--radius-lg);background:var(--color-surface);box-shadow:var(--shadow-floating)}.brand-mark{width:2.5rem;height:2.5rem;display:grid;place-items:center;border-radius:var(--radius-sm);color:#fff;background:var(--color-primary)}.brand-mark i{width:1.2rem;height:.8rem;border:1.5px solid currentColor;border-radius:60% 40% 55% 45%;transform:rotate(-12deg)}.eyebrow{margin:var(--space-5) 0 var(--space-2);color:var(--color-primary);font-size:.6875rem;font-weight:740;letter-spacing:.08em}h1{margin:0 0 var(--space-3);font-size:2rem;letter-spacing:-.04em}p{color:var(--color-text-secondary)}button{width:100%;min-height:2.75rem;margin-top:var(--space-5);border:1px solid var(--color-primary);border-radius:var(--radius-sm);color:#fff;background:var(--color-primary);font:inherit;font-weight:700;cursor:pointer}button:disabled{opacity:.55}.error,.success{display:grid;gap:2px;margin-top:var(--space-5);padding:var(--space-4);border-radius:var(--radius-sm);font-size:.875rem}.error{color:var(--color-danger);background:var(--color-danger-subtle)}.success{color:var(--color-success);background:var(--color-success-subtle)}.error span,.success span{color:var(--color-text-secondary)}
`],changeDetection:ChangeDetectionStrategy.OnPush})
export class InvitationAcceptancePageComponent{
  private readonly api=inject(AdministrationApi);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);private readonly context=inject(ContextStore);private readonly destroyRef=inject(DestroyRef);readonly state=signal<'idle'|'loading'|'success'|'error'>('idle');readonly message=signal('O convite pode estar expirado, cancelado ou já ter sido usado.');readonly token=this.route.snapshot.paramMap.get('token')||'';
  accept(){if(!this.token||this.state()==='loading')return;this.state.set('loading');this.api.acceptInvitation(this.token).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:async()=>{this.state.set('success');await this.context.revalidateAccess();setTimeout(()=>void this.router.navigate(['/administracao']),800);},error:error=>{this.state.set('error');if(error instanceof AppError&&error.kind==='forbidden')this.message.set('Sua conta não pode aceitar este convite.');}})}
}
