import { ChangeDetectionStrategy, Component, DestroyRef, computed, effect, inject, signal, untracked } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { ContextStore } from '../../core/context/context.store';
import { ErrorStateComponent, SkeletonComponent, ToastService } from '../../design-system/feedback/feedback';
import { DialogComponent } from '../../design-system/surfaces/surfaces';
import { ContextRequestScope } from '../management/management.shared';
import { administrationError } from './administration.shared';
import { AdministrationApi } from './administration-api.service';
import { AdministrativeOrganization, OrganizationAdmin, roleLabels, statusLabels } from './administration.models';
import { AdministrationHeaderComponent } from './administration-header.component';

@Component({selector:'app-organizations-page',imports:[FormsModule,AdministrationHeaderComponent,ErrorStateComponent,SkeletonComponent,DialogComponent],template:`
<div class="admin-page page-enter"><app-administration-header/><section class="section-heading"><div><span>SUAS ORGANIZAÇÕES</span><h2>Ambientes aos quais você tem acesso</h2><p>Consulte suas organizações, cadastre um ambiente ou reative um cadastro sob sua responsabilidade.</p></div><button class="primary" type="button" (click)="openCreate()">Nova organização</button></section>
<section class="admin-filters" aria-label="Filtros de organizações"><label><span>Buscar pelo nome</span><input [ngModel]="search()" (ngModelChange)="search.set($event);page.set(0)"/></label><label><span>Situação</span><select [ngModel]="status()" (ngModelChange)="status.set($event);page.set(0)"><option value="">Todas</option><option value="ACTIVE">Ativa</option><option value="SUSPENDED">Suspensa</option><option value="ARCHIVED">Arquivada</option></select></label></section>
@if(state()==='loading'){<section class="list-skeleton"><gr-skeleton/><gr-skeleton/><gr-skeleton/></section>}@else if(state()==='error'){<gr-error-state title="Não foi possível carregar suas organizações" description="Tente novamente para consultar os ambientes associados à sua conta." (retry)="load()"/>}@else if(!filtered().length){<section class="empty-inline"><h3>{{organizations().length?'Nenhuma organização encontrada':'Nenhuma organização associada'}}</h3><p>{{organizations().length?'Revise os filtros.':'Cadastre sua organização ou aceite um convite para começar.'}}</p></section>}@else{<section class="organization-list" aria-label="Suas organizações">@for(organization of visible();track organization.id){<article><div><strong>{{organization.name}}</strong><span>{{roleLabels[organization.role]}} · {{organization.farmScopeMode==='ALL_FARMS'?'Todas as fazendas':'Fazendas selecionadas'}}</span></div><span class="status" [class.muted]="organization.status!=='ACTIVE'">{{statusLabels[organization.status]}}</span><button class="secondary" type="button" (click)="openEdit(organization)">{{organization.role==='OWNER'?'Editar':'Ver detalhes'}}</button>@if(organization.status==='ACTIVE'){<button class="primary" type="button" (click)="enter(organization)" [disabled]="context.transitionPending()">Acessar</button>}</article>}</section><nav class="simple-pagination" aria-label="Paginação de organizações"><span>{{filtered().length}} {{filtered().length===1?'organização':'organizações'}} · página {{page()+1}}</span><div><button class="secondary" type="button" [disabled]="page()===0" (click)="page.set(page()-1)">Anterior</button><button class="secondary" type="button" [disabled]="(page()+1)*pageSize>=filtered().length" (click)="page.set(page()+1)">Próxima</button></div></nav>}
@if(pageError()){<p class="form-error" role="alert">{{pageError()}}</p>}</div>
<gr-dialog [open]="editor()" (closed)="closeEditor()"><strong dialog-title>{{editing()?'Cadastro da organização':'Nova organização'}}</strong>@if(editorLoading()){<gr-skeleton/>}@else if(editorFailed()){<p class="form-error" role="alert">Não foi possível consultar a organização.</p><button class="secondary" type="button" (click)="retryEditor()">Tentar novamente</button>}@else if(review()){<section class="confirmation"><h3>Confirmar cadastro</h3><p><strong>{{name.trim()}}</strong> · {{statusLabels[editStatus]}}</p><p>{{editStatus==='ACTIVE'?'O ambiente ficará disponível conforme o papel e o escopo de cada pessoa.':'A organização deixará de aparecer no seletor de operação. O acesso às fazendas será revalidado.'}}</p><small>O histórico será preservado. Somente um proprietário pode alterar a situação.</small></section>}@else{<form id="organization-directory-form" (ngSubmit)="prepare()"><fieldset [disabled]="!!editing()&&editing()!.role!=='OWNER'"><label><span>Nome da organização *</span><input name="name" [(ngModel)]="name" maxlength="160" required/></label>@if(editing()){<label><span>Situação *</span><select name="status" [(ngModel)]="editStatus"><option value="ACTIVE">Ativa</option><option value="SUSPENDED">Suspensa</option><option value="ARCHIVED">Arquivada</option></select></label><small>Organizações suspensas ou arquivadas podem ser reativadas nesta página por um proprietário.</small>}@else{<small>Você será o proprietário da nova organização. Depois, cadastre as fazendas e configure os acessos.</small>}</fieldset></form>}@if(formError()){<p class="form-error" role="alert">{{formError()}}</p>@if(editing()){<button class="secondary" type="button" (click)="retryEditor()" [disabled]="saving()">Recarregar cadastro</button>}}<div dialog-actions><button class="secondary" type="button" (click)="closeEditor()" [disabled]="saving()">Fechar</button>@if((!editing()||editing()!.role==='OWNER')&&!editorLoading()&&!editorFailed()){@if(review()){<button class="secondary" type="button" (click)="review.set(false)" [disabled]="saving()">Voltar</button><button class="primary" type="button" (click)="save()" [disabled]="saving()">{{saving()?'Salvando…':'Confirmar cadastro'}}</button>}@else{<button class="primary" type="submit" form="organization-directory-form">Revisar cadastro</button>}}</div></gr-dialog>
`,styleUrl:'./administration.scss',changeDetection:ChangeDetectionStrategy.OnPush})
export class OrganizationsPageComponent{
 private readonly api=inject(AdministrationApi);private readonly scope=new ContextRequestScope(inject(DestroyRef));private readonly router=inject(Router);private readonly toast=inject(ToastService);readonly context=inject(ContextStore);readonly roleLabels=roleLabels;readonly statusLabels=statusLabels;
 readonly state=signal<'loading'|'ready'|'error'>('loading');readonly organizations=signal<AdministrativeOrganization[]>([]);readonly search=signal('');readonly status=signal('');readonly page=signal(0);readonly pageSize=20;readonly editor=signal(false);readonly editing=signal<AdministrativeOrganization|null>(null);readonly editorLoading=signal(false);readonly editorFailed=signal(false);readonly review=signal(false);readonly saving=signal(false);readonly formError=signal('');readonly pageError=signal('');name='';editStatus='ACTIVE';private createId='';private editorRevision=0;private readRevision=0;
 readonly filtered=computed(()=>this.organizations().filter(o=>(!this.status()||o.status===this.status())&&o.name.toLocaleLowerCase('pt-BR').includes(this.search().trim().toLocaleLowerCase('pt-BR'))));readonly visible=computed(()=>this.filtered().slice(this.page()*this.pageSize,(this.page()+1)*this.pageSize));
 constructor(){effect(()=>{this.context.contextVersion();const pending=this.context.transitionPending();untracked(()=>{this.scope.reset();this.readRevision++;this.editorRevision++;this.organizations.set([]);this.editing.set(null);this.editor.set(false);this.review.set(false);this.saving.set(false);this.editorLoading.set(false);this.editorFailed.set(false);this.formError.set('');this.pageError.set('');this.name='';this.editStatus='ACTIVE';this.createId='';this.state.set('loading');if(!pending)this.load();});});}
 load(){const revision=++this.readRevision;this.state.set('loading');this.scope.run(this.api.administrativeOrganizations(),value=>{if(revision!==this.readRevision)return;this.organizations.set(value);this.page.set(Math.min(this.page(),Math.max(0,Math.ceil(this.filtered().length/this.pageSize)-1)));this.state.set('ready');},()=>{if(revision===this.readRevision)this.state.set('error');});}
 openCreate(){if(this.context.transitionPending())return;this.editorRevision++;this.createId=crypto.randomUUID();this.editing.set(null);this.name='';this.editStatus='ACTIVE';this.editorLoading.set(false);this.editorFailed.set(false);this.review.set(false);this.formError.set('');this.editor.set(true);}
 openEdit(value:AdministrativeOrganization){if(this.context.transitionPending())return;this.editing.set(value);this.editor.set(true);this.review.set(false);this.formError.set('');this.retryEditor();}
 retryEditor(){if(this.saving()||this.context.transitionPending())return;this.review.set(false);this.formError.set('');const selected=this.editing();if(!selected)return;const revision=++this.editorRevision;this.editorLoading.set(true);this.editorFailed.set(false);this.scope.run(this.api.organization(selected.id),value=>{if(revision!==this.editorRevision||!this.editor())return;this.editing.set({...selected,id:value.id,name:value.name,status:value.status,version:value.version});this.name=value.name;this.editStatus=value.status;this.editorLoading.set(false);},()=>{if(revision!==this.editorRevision||!this.editor())return;this.editorLoading.set(false);this.editorFailed.set(true);});}
 closeEditor(){if(!this.saving()){this.editorRevision++;this.editor.set(false);this.review.set(false);}}
 prepare(){if(this.saving()||this.editorLoading()||this.editorFailed()||(this.editing()&&this.editing()!.role!=='OWNER'))return;if(!this.name.trim()||this.name.trim().length>160){this.formError.set('Informe um nome com até 160 caracteres.');return;}if(!['ACTIVE','SUSPENDED','ARCHIVED'].includes(this.editStatus))return;this.formError.set('');this.review.set(true);}
 save(){const current=this.editing();if(!this.review()||this.saving()||this.context.transitionPending()||this.editorLoading()||this.editorFailed()||(current&&current.role!=='OWNER'))return;this.saving.set(true);this.formError.set('');const request=current?this.api.updateOrganization(current.id,{name:this.name.trim(),status:this.editStatus,expectedVersion:current.version}):this.api.createOrganization({id:this.createId,name:this.name.trim()});this.scope.run(request,value=>this.saved(value,!!current),error=>{this.saving.set(false);this.formError.set(administrationError(error,'Não foi possível salvar a organização.'));});}
 private saved(value:OrganizationAdmin,updated:boolean){this.saving.set(false);this.editor.set(false);this.toast.show('success',updated?'Organização atualizada':'Organização criada',value.name);this.load();void this.context.revalidateAccess();}
 async enter(value:AdministrativeOrganization){if(this.context.transitionPending()||value.status!=='ACTIVE')return;this.pageError.set('');try{if(!this.context.organizations().some(o=>o.organizationId===value.id))await this.context.revalidateAccess();await this.context.selectOrganization(value.id);if(this.context.selectedOrganization()?.organizationId!==value.id){this.pageError.set('A organização não está disponível para operação. Recarregue os dados.');return;}await this.router.navigate(['/administracao']);}catch{this.pageError.set('Não foi possível acessar esta organização. Tente novamente.');}}
}
