import {signal} from '@angular/core';
import {TestBed} from '@angular/core/testing';
import {provideRouter} from '@angular/router';
import {Observable,Subject,of,throwError} from 'rxjs';
import {describe,expect,it,vi} from 'vitest';
import {AppError,MembershipRole} from '../../core/api/api.models';
import {ContextStore} from '../../core/context/context.store';
import {ToastService} from '../../design-system/feedback/feedback';
import {AdministrationApi} from './administration-api.service';
import {AdministrativeOrganization,OrganizationAdmin} from './administration.models';
import {OrganizationsPageComponent} from './organizations-page.component';

HTMLDialogElement.prototype.showModal??=function(){this.open=true;};HTMLDialogElement.prototype.close??=function(){this.open=false;};
const organization:AdministrativeOrganization={id:'o',name:'Grupo rural',status:'SUSPENDED',version:8,role:'OWNER',farmScopeMode:'ALL_FARMS'};
function mocks(){return{administrativeOrganizations:vi.fn(():Observable<AdministrativeOrganization[]>=>of([organization])),organization:vi.fn(():Observable<OrganizationAdmin>=>of(organization)),createOrganization:vi.fn(():Observable<OrganizationAdmin>=>of(organization)),updateOrganization:vi.fn(():Observable<OrganizationAdmin>=>of(organization))};}
async function setup(role:MembershipRole|null='OWNER',initialize?:(api:ReturnType<typeof mocks>)=>void){const api=mocks();initialize?.(api);const context={contextVersion:signal(0),transitionPending:signal(false),selectedOrganization:signal(null),selectedFarm:signal(null),role:signal<MembershipRole|null>(role),organizations:signal([]),revalidateAccess:vi.fn(()=>Promise.resolve()),selectOrganization:vi.fn(()=>Promise.resolve())};const toast={show:vi.fn()};await TestBed.configureTestingModule({imports:[OrganizationsPageComponent],providers:[provideRouter([]),{provide:AdministrationApi,useValue:api},{provide:ContextStore,useValue:context},{provide:ToastService,useValue:toast}]}).compileComponents();const fixture=TestBed.createComponent(OrganizationsPageComponent);fixture.detectChanges();await fixture.whenStable();return{fixture,component:fixture.componentInstance,api,context,toast};}
describe('Organizações e recuperação do ambiente',()=>{
 it('conta sem organização selecionada consulta diretório e cadastra ambiente',async()=>{const{component,api}=await setup(null);expect(component.organizations()).toEqual([organization]);component.openCreate();component.name='Novo ambiente';component.save();expect(api.createOrganization).not.toHaveBeenCalled();component.prepare();component.save();expect(api.createOrganization).toHaveBeenCalledWith({id:expect.any(String),name:'Novo ambiente'});});
 it('reativação usa papel do vínculo da organização editada e versão atual',async()=>{const{component,api}=await setup('VIEWER');component.openEdit(organization);component.editStatus='ACTIVE';component.prepare();component.save();expect(api.updateOrganization).toHaveBeenCalledWith('o',{name:organization.name,status:'ACTIVE',expectedVersion:8});});
 it.each(['ADMIN','MANAGER','OPERATOR','VIEWER'] as MembershipRole[])('%s consulta outra organização sem alterar sua situação',async role=>{const{component,api}=await setup('OWNER');component.openEdit({...organization,role});component.editStatus='ACTIVE';component.prepare();component.save();expect(api.updateOrganization).not.toHaveBeenCalled();});
 it('erro na consulta individual não autoriza criar no lugar de editar',async()=>{const{component,api}=await setup('OWNER',a=>a.organization.mockReturnValue(throwError(()=>new AppError('not-found','',404,'PLATFORM_ORGANIZATION_NOT_FOUND'))));component.openEdit(organization);component.prepare();component.save();expect(component.editorFailed()).toBe(true);expect(api.createOrganization).not.toHaveBeenCalled();expect(api.updateOrganization).not.toHaveBeenCalled();});
 it('bloqueia envio duplicado e conserva UUID em nova tentativa',async()=>{const pending=new Subject<OrganizationAdmin>();const{component,api}=await setup('OWNER',a=>a.createOrganization.mockReturnValue(pending));component.openCreate();component.name='Novo ambiente';component.prepare();component.save();component.save();expect(api.createOrganization).toHaveBeenCalledTimes(1);pending.error(new AppError('unavailable','',503,'UNAVAILABLE'));api.createOrganization.mockReturnValue(of(organization));component.save();expect(api.createOrganization.mock.calls[0]).toEqual(api.createOrganization.mock.calls[1]);});
 it('troca de contexto limpa editor e inutiliza consulta anterior',async()=>{const pending=new Subject<OrganizationAdmin>();const{fixture,component,context}=await setup('OWNER',a=>a.organization.mockReturnValue(pending));component.openEdit(organization);context.transitionPending.set(true);fixture.detectChanges();expect(pending.observed).toBe(false);expect(component.organizations()).toEqual([]);expect(component.editor()).toBe(false);expect(component.editing()).toBeNull();pending.next(organization);expect(component.editor()).toBe(false);});
 it('falha do diretório tem estado de erro e retry com dados reais do serviço',async()=>{const{component,api}=await setup('OWNER',a=>a.administrativeOrganizations.mockReturnValue(throwError(()=>new AppError('unavailable','',503,'UNAVAILABLE'))));expect(component.state()).toBe('error');api.administrativeOrganizations.mockReturnValue(of([organization]));component.load();expect(component.state()).toBe('ready');expect(component.organizations()).toEqual([organization]);});
});
