import { ChangeDetectionStrategy, Component, DestroyRef, computed, effect, inject, signal, untracked } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NgTemplateOutlet } from '@angular/common';
import { Router } from '@angular/router';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { LucideDynamicIcon } from '@lucide/angular';
import { AppError, MembershipRole } from '../../core/api/api.models';
import { ContextStore } from '../../core/context/context.store';
import { ErrorStateComponent, SkeletonComponent, ToastService } from '../../design-system/feedback/feedback';
import { AvatarComponent } from '../../design-system/data-display/data-display';
import { DialogComponent, DrawerComponent } from '../../design-system/surfaces/surfaces';
import { AdministrationApi } from './administration-api.service';
import { AccessDraft, AdminFarm, AdminInvitation, AdminMember, accessSummary, canManageMember, roleDescriptions, roleLabels, roleOptions, statusLabels } from './administration.models';
import { AdministrationHeaderComponent } from './administration-header.component';

@Component({selector:'app-people-page',imports:[FormsModule,NgTemplateOutlet,LucideDynamicIcon,AdministrationHeaderComponent,AvatarComponent,DialogComponent,DrawerComponent,SkeletonComponent,ErrorStateComponent],template:`
<div class="admin-page people-page page-enter"><app-administration-header/><section class="section-heading"><div><span>PESSOAS E ACESSOS</span><h2>Quem participa desta organização</h2><p>Cada acesso combina identidade, papel e alcance nas fazendas.</p></div><button class="primary" type="button" (click)="openInvite()"><svg lucideIcon="user-plus"></svg>Convidar pessoa</button></section>
@if(state()==='loading'){<section class="list-skeleton"><gr-skeleton/><gr-skeleton/><gr-skeleton/></section>}
@else if(state()==='error'){<gr-error-state title="Não foi possível carregar pessoas e acessos" description="Seu papel pode ter mudado. Recarregue os dados para continuar." (retry)="load()"/>}
@else{
  <section class="access-legend" aria-label="Como ler os acessos"><span>IDENTIDADE</span><i aria-hidden="true">→</i><span>PAPEL</span><i aria-hidden="true">→</i><span>FAZENDAS</span><i aria-hidden="true">→</i><span>ESTADO</span></section>
  @if(!members().length){<section class="empty-inline"><h3>Nenhuma pessoa encontrada</h3><p>Não há associações disponíveis nesta página.</p></section>}
  @else{<section class="member-list" aria-label="Pessoas da organização">@for(member of members();track member.membershipId){<article [class.revoked]="member.status!=='ACTIVE'"><div class="identity"><gr-avatar [name]="member.displayName||member.email||'Usuário'"/><span><strong>{{member.displayName||member.email||'Usuário sem nome'}}</strong>@if(member.displayName&&member.email){<small>{{member.email}}</small>}</span>@if(member.userId===context.user()?.userId){<em>Você</em>}</div><div class="role"><span>Papel</span><strong>{{roleLabels[member.role]}}</strong></div><div class="scope"><span>Acesso às fazendas</span><strong>{{summary(member)}}</strong></div><span class="status" [class.muted]="member.status!=='ACTIVE'">{{statusLabels[member.status]||member.status}}</span>@if(manageable(member)&&member.status==='ACTIVE'){<button class="secondary" type="button" (click)="openEdit(member)">Editar acesso</button>}</article>}</section>
  <nav class="simple-pagination" aria-label="Paginação de pessoas"><span>Página {{page()+1}}</span><div><button class="secondary" type="button" [disabled]="page()===0" (click)="changePage(page()-1)">Anterior</button><button class="secondary" type="button" [disabled]="members().length<pageSize" (click)="changePage(page()+1)">Próxima</button></div></nav>}
  <section class="invites"><header><div><span>CONVITES PENDENTES</span><h2>Aguardando entrada</h2></div></header>@if(!invitations().length){<p class="quiet-empty">Não há convites pendentes.</p>}@else{@for(invitation of invitations();track invitation.id){<article><div><strong>{{invitation.email}}</strong><span>{{roleLabels[invitation.role]}} · {{invitation.scopeMode==='ALL_FARMS'?'Todas as fazendas':'Fazendas selecionadas'}}</span></div><time [attr.datetime]="invitation.expiresAt">Expira em {{date(invitation.expiresAt)}}</time><button class="danger-link" type="button" (click)="confirmInvitationRevocation(invitation)">Cancelar convite</button></article>}}</section>
}
</div>

<gr-drawer [open]="editOpen()" label="Editar acesso" (closed)="closeEdit()">@if(selectedMember();as member){<div class="access-editor"><div class="editor-person"><gr-avatar [name]="member.displayName||member.email||'Usuário'"/><span><strong>{{member.displayName||member.email}}</strong><small>{{member.displayName?member.email:''}}</small></span></div><form id="member-form" (ngSubmit)="saveMember()"><label><span>Papel na organização</span><select name="memberRole" [(ngModel)]="draftRole" (ngModelChange)="formError.set('')">@for(role of availableRoles;track role){<option [value]="role">{{roleLabels[role]}}</option>}</select><small>{{roleDescriptions[draftRole]}}</small></label><fieldset><legend>Acesso às fazendas</legend><label class="choice"><input type="radio" name="memberScope" [(ngModel)]="draftScope" value="ALL_FARMS"/><span><strong>Todas as fazendas</strong><small>Inclui fazendas atuais e novas enquanto este acesso estiver ativo.</small></span></label><label class="choice"><input type="radio" name="memberScope" [(ngModel)]="draftScope" value="SELECTED_FARMS"/><span><strong>Fazendas selecionadas</strong><small>A pessoa acessa somente as fazendas marcadas abaixo.</small></span></label></fieldset>@if(draftScope==='SELECTED_FARMS'){<ng-container [ngTemplateOutlet]="farmSelector"/>}<section class="access-review"><span>RESUMO DA ALTERAÇÃO</span><strong>{{roleLabels[draftRole]}}</strong><p>{{draftSummary}}</p></section>@if(formError()){<p class="form-error" role="alert">{{formError()}}</p>}<button class="primary full" type="submit" [disabled]="saving()">{{saving()?'Salvando…':'Salvar acesso'}}</button><button class="danger-link full" type="button" (click)="confirmRemoval(member)">Remover da organização</button></form></div>}</gr-drawer>

<gr-dialog [open]="inviteOpen()" (closed)="closeInvite()"><strong dialog-title>Convidar pessoa</strong><form id="invite-form" (ngSubmit)="sendInvite()"><label><span>E-mail</span><input type="email" name="inviteEmail" [(ngModel)]="inviteEmail" maxlength="320" required autofocus placeholder="pessoa@exemplo.com"/></label><label><span>Papel na organização</span><select name="inviteRole" [(ngModel)]="draftRole">@for(role of availableRoles;track role){<option [value]="role">{{roleLabels[role]}}</option>}</select><small>{{roleDescriptions[draftRole]}}</small></label><fieldset><legend>Acesso às fazendas</legend><label class="choice"><input type="radio" name="inviteScope" [(ngModel)]="draftScope" value="ALL_FARMS"/><span><strong>Todas as fazendas</strong><small>Inclui fazendas atuais e novas.</small></span></label><label class="choice"><input type="radio" name="inviteScope" [(ngModel)]="draftScope" value="SELECTED_FARMS"/><span><strong>Fazendas selecionadas</strong><small>Limita o convite às fazendas marcadas.</small></span></label></fieldset>@if(draftScope==='SELECTED_FARMS'){<ng-container [ngTemplateOutlet]="farmSelector"/>}<section class="access-review"><span>O CONVITE CONCEDE</span><strong>{{roleLabels[draftRole]}}</strong><p>{{draftSummary}}</p></section>@if(formError()){<p class="form-error" role="alert">{{formError()}}</p>}</form><div dialog-actions><button class="secondary" type="button" (click)="closeInvite()">Cancelar</button><button class="primary" type="submit" form="invite-form" [disabled]="saving()">{{saving()?'Enviando…':'Criar convite'}}</button></div></gr-dialog>

<ng-template #farmSelector><section class="farm-selector"><label><span>Buscar fazenda</span><input name="farmSearch" [ngModel]="farmSearch()" (ngModelChange)="farmSearch.set($event)" placeholder="Digite o nome"/></label><div role="group" aria-label="Fazendas permitidas">@for(farm of filteredFarms();track farm.id){<label><input type="checkbox" [checked]="selectedFarmIds().has(farm.id)" (change)="toggleFarm(farm.id)"/><span>{{farm.name}}</span></label>}@if(!filteredFarms().length){<p>Nenhuma fazenda encontrada.</p>}</div></section></ng-template>

<gr-dialog [open]="removalOpen()" (closed)="removalOpen.set(false)"><strong dialog-title>Remover acesso</strong>@if(removalTarget();as member){<div class="confirmation"><p><strong>{{member.displayName||member.email}}</strong> perderá o acesso à organização e às fazendas permitidas.</p><small>A conta da pessoa não será excluída.</small></div>}<div dialog-actions><button class="secondary" type="button" (click)="removalOpen.set(false)">Manter acesso</button><button class="danger" type="button" [disabled]="saving()" (click)="removeMember()">Remover acesso</button></div></gr-dialog>
<gr-dialog [open]="invitationRemovalOpen()" (closed)="invitationRemovalOpen.set(false)"><strong dialog-title>Cancelar convite</strong><div class="confirmation"><p>Este convite não poderá mais ser usado para entrar na organização.</p></div><div dialog-actions><button class="secondary" type="button" (click)="invitationRemovalOpen.set(false)">Manter convite</button><button class="danger" type="button" [disabled]="saving()" (click)="revokeInvitation()">Cancelar convite</button></div></gr-dialog>
<gr-dialog [open]="!!createdToken()" (closed)="createdToken.set('')"><strong dialog-title>Convite criado</strong><div class="token-result"><p>Compartilhe este link somente com a pessoa convidada. Ele aparece uma única vez.</p><code>{{invitationLink}}</code><button class="secondary" type="button" (click)="copyLink()">Copiar link</button></div><div dialog-actions><button class="primary" type="button" (click)="createdToken.set('')">Concluir</button></div></gr-dialog>
`,styleUrls:['./administration.scss','./people-page.component.scss'],changeDetection:ChangeDetectionStrategy.OnPush})
export class PeoplePageComponent{
  private readonly api=inject(AdministrationApi);private readonly destroyRef=inject(DestroyRef);private readonly toast=inject(ToastService);private readonly router=inject(Router);readonly context=inject(ContextStore);
  readonly state=signal<'loading'|'ready'|'error'>('loading');readonly members=signal<AdminMember[]>([]);readonly farms=signal<AdminFarm[]>([]);readonly invitations=signal<AdminInvitation[]>([]);readonly page=signal(0);readonly selectedMember=signal<AdminMember|null>(null);readonly editOpen=signal(false);readonly inviteOpen=signal(false);readonly removalOpen=signal(false);readonly removalTarget=signal<AdminMember|null>(null);readonly invitationRemovalOpen=signal(false);readonly invitationTarget=signal<AdminInvitation|null>(null);readonly saving=signal(false);readonly formError=signal('');readonly selectedFarmIds=signal(new Set<string>());readonly createdToken=signal('');readonly farmSearch=signal('');readonly pageSize=25;readonly roleLabels=roleLabels;readonly roleDescriptions=roleDescriptions;readonly statusLabels=statusLabels;inviteEmail='';draftRole:MembershipRole='VIEWER';draftScope:'ALL_FARMS'|'SELECTED_FARMS'='ALL_FARMS';private generation=0;
  readonly filteredFarms=computed(()=>{const term=this.farmSearch().trim().toLocaleLowerCase('pt-BR');return this.farms().filter(f=>f.status==='ACTIVE'&&(!term||f.name.toLocaleLowerCase('pt-BR').includes(term)));});
  constructor(){effect(()=>{this.context.contextVersion();this.context.selectedOrganization();if(!this.context.transitionPending()){untracked(()=>{this.page.set(0);this.load();});}});}
  get availableRoles(){return this.context.role()==='OWNER'?roleOptions:roleOptions.filter(role=>!['OWNER','ADMIN'].includes(role))}get draftSummary(){return accessSummary(this.draftScope,[...this.selectedFarmIds()],this.farms())}get invitationLink(){return this.createdToken()?`${location.origin}/convites/${encodeURIComponent(this.createdToken())}`:''}
  load(){const organization=this.context.selectedOrganization();if(!organization)return;const current=++this.generation;this.state.set('loading');let members:AdminMember[]|null=null,farms:AdminFarm[]|null=null,invites:AdminInvitation[]|null=null;const done=()=>{if(current!==this.generation||!members||!farms||!invites)return;this.members.set(members);this.farms.set(farms);this.invitations.set(invites);this.state.set('ready');};const failed=()=>{if(current===this.generation)this.state.set('error');};this.api.members(organization.organizationId,this.page(),this.pageSize).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:v=>{members=v;done();},error:failed});this.api.farms(organization.organizationId).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:v=>{farms=v;done();},error:failed});this.api.invitations(organization.organizationId,'PENDING',0,50).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:v=>{invites=v;done();},error:failed});}
  changePage(value:number){this.page.set(Math.max(0,value));this.load()}summary(member:AdminMember){return accessSummary(member.scopeMode,member.farmIds,this.farms())}manageable(member:AdminMember){return canManageMember(this.context.role(),member.role)}date(value:string){return new Intl.DateTimeFormat('pt-BR').format(new Date(value))}
  resetDraft(){this.draftRole='VIEWER';this.draftScope='ALL_FARMS';this.selectedFarmIds.set(new Set());this.farmSearch.set('');this.formError.set('')}
  openEdit(member:AdminMember){this.selectedMember.set(member);this.draftRole=member.role;this.draftScope=member.scopeMode;this.selectedFarmIds.set(new Set(member.farmIds));this.farmSearch.set('');this.formError.set('');this.editOpen.set(true)}closeEdit(){if(!this.saving())this.editOpen.set(false)}openInvite(){this.resetDraft();this.inviteEmail='';this.inviteOpen.set(true)}closeInvite(){if(!this.saving())this.inviteOpen.set(false)}toggleFarm(id:string){this.selectedFarmIds.update(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next;});this.formError.set('')}
  private draft():AccessDraft|null{const farmIds=[...this.selectedFarmIds()];if(this.draftScope==='SELECTED_FARMS'&&!farmIds.length){this.formError.set('Selecione ao menos uma fazenda.');return null;}return{role:this.draftRole,scopeMode:this.draftScope,farmIds};}
  saveMember(){const organization=this.context.selectedOrganization(),member=this.selectedMember(),draft=this.draft();if(!organization||!member||!draft)return;this.saving.set(true);this.api.updateMember(organization.organizationId,member.membershipId,draft,member.version).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:value=>{this.members.update(items=>items.map(item=>item.membershipId===value.membershipId?value:item));this.saving.set(false);this.editOpen.set(false);this.toast.show('success','Acesso atualizado',`${value.displayName||value.email} agora tem o acesso revisado.`);if(value.userId===this.context.user()?.userId)void this.reconcileSelf();},error:error=>this.mutationError(error,'Não foi possível atualizar este acesso.')})}
  sendInvite(){const organization=this.context.selectedOrganization(),draft=this.draft(),email=this.inviteEmail.trim();if(!organization||!draft)return;if(!/^\S+@\S+\.\S+$/.test(email)){this.formError.set('Informe um e-mail válido.');return;}this.saving.set(true);this.api.invite(organization.organizationId,email,draft).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:value=>{this.invitations.update(items=>[value.invitation,...items]);this.saving.set(false);this.inviteOpen.set(false);this.createdToken.set(value.token);this.toast.show('success','Convite criado','O link de acesso está pronto para compartilhamento seguro.');},error:error=>this.mutationError(error,'Não foi possível criar o convite.')})}
  confirmRemoval(member:AdminMember){this.removalTarget.set(member);this.editOpen.set(false);this.removalOpen.set(true)}removeMember(){const organization=this.context.selectedOrganization(),member=this.removalTarget();if(!organization||!member)return;this.saving.set(true);this.api.revokeMember(organization.organizationId,member.membershipId,member.version).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:()=>{this.members.update(items=>items.map(item=>item.membershipId===member.membershipId?{...item,status:'REVOKED',version:item.version+1}:item));this.saving.set(false);this.removalOpen.set(false);this.toast.show('success','Acesso removido',`${member.displayName||member.email} não participa mais desta organização.`);if(member.userId===this.context.user()?.userId)void this.reconcileSelf();},error:error=>this.mutationError(error,'Não foi possível remover este acesso.')})}
  confirmInvitationRevocation(invitation:AdminInvitation){this.invitationTarget.set(invitation);this.invitationRemovalOpen.set(true)}revokeInvitation(){const organization=this.context.selectedOrganization(),invitation=this.invitationTarget();if(!organization||!invitation)return;this.saving.set(true);this.api.revokeInvitation(organization.organizationId,invitation.id).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:()=>{this.invitations.update(items=>items.filter(item=>item.id!==invitation.id));this.saving.set(false);this.invitationRemovalOpen.set(false);this.toast.show('success','Convite cancelado',`O convite para ${invitation.email} não pode mais ser usado.`);},error:error=>this.mutationError(error,'Não foi possível cancelar o convite.')})}
  async copyLink(){try{await navigator.clipboard.writeText(this.invitationLink);this.toast.show('success','Link copiado');}catch{this.toast.show('error','Não foi possível copiar o link','Selecione o endereço e copie manualmente.');}}
  private async reconcileSelf(){try{await this.context.revalidateAccess();await this.router.navigate(['/administracao']);}catch{await this.router.navigate(['/visao-geral']);}}
  private mutationError(error:unknown,fallback:string){this.saving.set(false);const app=error instanceof AppError?error:null;this.formError.set(app?.kind==='conflict'?(app.code==='PLATFORM_VERSION_CONFLICT'?'Este acesso foi atualizado em outra sessão. Recarregue os dados.':'A alteração entra em conflito com uma regra da organização, como a proteção do último proprietário.'):fallback);this.toast.show('error','Alteração não concluída',this.formError());}
}
