import { signal } from '@angular/core';
import { TestBed } from '@angular/core/testing';
import { provideRouter } from '@angular/router';
import { provideLucideIcons, LucideUserPlus } from '@lucide/angular';
import { Observable, Subject, of } from 'rxjs';
import { describe, expect, it, vi } from 'vitest';
import { MembershipRole } from '../../core/api/api.models';
import { ContextStore } from '../../core/context/context.store';
import { ToastService } from '../../design-system/feedback/feedback';
import { AdministrationApi } from './administration-api.service';
import { AdminFarm,AdminInvitation,AdminMember,InvitationCreated } from './administration.models';
import { PeoplePageComponent } from './people-page.component';

HTMLDialogElement.prototype.showModal ??= function () { this.open = true; };
HTMLDialogElement.prototype.close ??= function () { this.open = false; };
const userId='12345678-1234-1234-1234-123456789abc';
const member:AdminMember={membershipId:'m',userId,displayName:'Pessoa de teste',email:null,role:'VIEWER',status:'ACTIVE',scopeMode:'ALL_FARMS',farmIds:[],version:3,createdAt:'2026-09-01T00:00:00Z'};
const invitation:AdminInvitation={id:'i',email:'pessoa@example.test',role:'VIEWER',scopeMode:'ALL_FARMS',status:'PENDING',expiresAt:'2026-10-01T00:00:00Z',createdAt:'2026-09-01T00:00:00Z'};
function mocks(){return{members:vi.fn(():Observable<AdminMember[]>=>of([member])),farms:vi.fn(():Observable<AdminFarm[]>=>of([])),invitations:vi.fn(():Observable<AdminInvitation[]>=>of([invitation])),invite:vi.fn(():Observable<InvitationCreated>=>of({invitation,token:'test-only-token'})),addMember:vi.fn(():Observable<AdminMember>=>of(member)),updateMember:vi.fn(():Observable<AdminMember>=>of(member)),revokeMember:vi.fn(()=>of(undefined)),revokeInvitation:vi.fn(()=>of(undefined))};}
async function setup(role:MembershipRole='OWNER',initialize?:(api:ReturnType<typeof mocks>)=>void){const api=mocks();initialize?.(api);const context={contextVersion:signal(0),transitionPending:signal(false),selectedOrganization:signal({organizationId:'o',organizationName:'Grupo',farmScopeMode:'ALL_FARMS'}),selectedFarm:signal({farmId:'f',farmName:'Fazenda Norte'}),role:signal<MembershipRole|null>(role),user:signal({userId:'current'}),revalidateAccess:vi.fn(()=>Promise.resolve())};const toast={show:vi.fn()};await TestBed.configureTestingModule({imports:[PeoplePageComponent],providers:[provideRouter([]),provideLucideIcons(LucideUserPlus),{provide:AdministrationApi,useValue:api},{provide:ContextStore,useValue:context},{provide:ToastService,useValue:toast}]}).compileComponents();const fixture=TestBed.createComponent(PeoplePageComponent);fixture.detectChanges();await fixture.whenStable();return{fixture,component:fixture.componentInstance,api,context,toast};}
describe('Pessoas, acessos e convites',()=>{
 it.each(['MANAGER','OPERATOR','VIEWER'] as MembershipRole[])('%s consulta pessoas e não consulta convites nem altera acessos',async role=>{const{fixture,component,api}=await setup(role);expect(component.members()).toEqual([member]);expect(api.invitations).not.toHaveBeenCalled();expect(fixture.nativeElement.querySelector('.people-page').textContent).not.toContain('Convidar pessoa');component.openInvite();component.openEdit(member);component.sendInvite();component.saveMember();component.confirmRemoval(member);component.removeMember();expect(component.inviteOpen()).toBe(false);expect(api.invite).not.toHaveBeenCalled();expect(api.updateMember).not.toHaveBeenCalled();expect(api.revokeMember).not.toHaveBeenCalled();});
 it('administrador não gerencia proprietário nem concede papel elevado',async()=>{const{component,api}=await setup('ADMIN');component.openEdit({...member,role:'OWNER'});expect(component.editOpen()).toBe(false);component.openInvite();component.inviteEmail='pessoa@example.test';component.draftRole='ADMIN';component.sendInvite();expect(api.invite).not.toHaveBeenCalled();expect(component.availableRoles).not.toContain('OWNER');});
 it('inclui usuário existente com UUID e valida seleção de fazendas',async()=>{const{component,api}=await setup();component.openInvite(true);component.existingUserId='inválido';component.sendInvite();expect(api.addMember).not.toHaveBeenCalled();component.existingUserId=userId;component.draftScope='SELECTED_FARMS';component.sendInvite();expect(component.formError()).toBe('Selecione ao menos uma fazenda.');component.selectedFarmIds.set(new Set(['f']));component.sendInvite();expect(api.addMember).toHaveBeenCalledWith('o',userId,{role:'VIEWER',scopeMode:'SELECTED_FARMS',farmIds:['f']});});
 it('pagina pessoas e convites independentemente e envia a situação real ao backend',async()=>{const{component,api}=await setup();component.changePage(2);component.invitationStatus='EXPIRED';component.filterInvitations();component.changeInvitationPage(3);expect(api.members).toHaveBeenLastCalledWith('o',2,25);expect(api.invitations).toHaveBeenLastCalledWith('o','EXPIRED',3,25);component.invitationStatus='';component.filterInvitations();expect(api.invitations).toHaveBeenLastCalledWith('o','',0,25);});
 it('troca de contexto cancela envio, apaga token e fecha todos os editores',async()=>{const pending=new Subject<InvitationCreated>();const{fixture,component,api,context,toast}=await setup('OWNER',a=>a.invite.mockReturnValue(pending));component.openInvite();component.inviteEmail=invitation.email;component.sendInvite();component.sendInvite();expect(api.invite).toHaveBeenCalledTimes(1);component.createdToken.set('token-antigo');context.transitionPending.set(true);fixture.detectChanges();expect(pending.observed).toBe(false);expect(component.createdToken()).toBe('');expect(component.members()).toEqual([]);expect(component.invitations()).toEqual([]);expect(component.inviteOpen()).toBe(false);expect(component.selectedFarmIds().size).toBe(0);pending.next({invitation,token:'não-usar'});expect(toast.show).not.toHaveBeenCalled();});
 it('convites expirados não oferecem cancelamento e o envio pendente não fecha a confirmação',async()=>{const{component,api}=await setup();component.confirmInvitationRevocation({...invitation,status:'EXPIRED'});expect(component.invitationRemovalOpen()).toBe(false);component.confirmInvitationRevocation(invitation);component.saving.set(true);component.closeInvitationRemoval();component.revokeInvitation();expect(component.invitationRemovalOpen()).toBe(true);expect(api.revokeInvitation).not.toHaveBeenCalled();});
});
