import { ChangeDetectionStrategy, Component, effect, signal } from '@angular/core';
import { Router, RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { LucideDynamicIcon } from '@lucide/angular';
import { AuthStore } from '../core/auth/auth.store';
import { ContextStore } from '../core/context/context.store';
import { PermissionService } from '../core/permissions/permission.service';
import { ToastRegionComponent, ToastService } from '../design-system/feedback/feedback';
import { AvatarComponent } from '../design-system/data-display/data-display';
import { ContextNavigatorComponent } from '../design-system/navigation/navigation';
import { IconButtonComponent, TooltipDirective } from '../design-system/primitives/primitives';
import { MenuComponent, PopoverComponent } from '../design-system/surfaces/surfaces';

interface NavItem { label:string; icon:string; route:string; permission?:'manageUsers' }
interface NavSection { label?:string; items:NavItem[] }

@Component({
  selector:'app-shell',
  imports:[RouterOutlet,RouterLink,RouterLinkActive,LucideDynamicIcon,ToastRegionComponent,AvatarComponent,ContextNavigatorComponent,IconButtonComponent,TooltipDirective,MenuComponent,PopoverComponent],
  template:`<div class="shell" [class.collapsed]="collapsed()">
    @if(mobileOpen()){<button class="mobile-backdrop" type="button" aria-label="Fechar menu" (click)="mobileOpen.set(false)"></button>}
    <aside class="sidebar" [class.mobile-open]="mobileOpen()" aria-label="Navegação principal">
      <div class="brand"><span class="brand-mark"><i></i></span><strong>Gerenciador<br/>Rural</strong><button type="button" class="close-mobile" aria-label="Fechar menu" (click)="mobileOpen.set(false)"><svg lucideIcon="x"></svg></button></div>
      <div class="mobile-contexts"><gr-context-navigator [organizations]="context.organizations()" [farms]="context.farms()" [organization]="context.selectedOrganization()" [farm]="context.selectedFarm()" [disabled]="context.transitionPending()" (organizationChanged)="changeOrganization($event)" (farmChanged)="changeFarm($event)" /></div>
      <nav>
        @for(section of navigation;track section.label){<section>@if(section.label){<h2>{{section.label}}</h2>}<ul>@for(item of section.items;track item.route){@if(!item.permission||permissions.can(item.permission)){<li><a [routerLink]="item.route" routerLinkActive="active" ariaCurrentWhenActive="page" (click)="mobileOpen.set(false)" [grTooltip]="collapsed()?item.label:''"><svg [lucideIcon]="item.icon"></svg><span>{{item.label}}</span></a></li>}}</ul></section>}
      </nav>
      <div class="sidebar-footer"><button type="button" (click)="collapsed.set(!collapsed())" [attr.aria-label]="collapsed()?'Expandir menu':'Recolher menu'"><svg lucideIcon="command"></svg><span>Recolher menu</span><kbd>⌘ B</kbd></button></div>
    </aside>
    <div class="workspace">
      <header class="topbar">
        <div class="topbar-start"><gr-icon-button class="menu-button" label="Abrir menu" (pressed)="mobileOpen.set(true)"><svg lucideIcon="menu"></svg></gr-icon-button><div class="contexts" [class.pending]="context.transitionPending()"><gr-context-navigator [organizations]="context.organizations()" [farms]="context.farms()" [organization]="context.selectedOrganization()" [farm]="context.selectedFarm()" [disabled]="context.transitionPending()" (organizationChanged)="changeOrganization($event)" (farmChanged)="changeFarm($event)" /></div></div>
        <div class="topbar-actions"><gr-popover label="Abrir menu da conta"><span popover-trigger class="account-trigger"><gr-avatar [name]="displayName"/><span><strong>{{displayName}}</strong><small>{{roleLabel}}</small></span><svg lucideIcon="chevron-down"></svg></span><gr-menu><div class="account-identity"><strong>{{displayName}}</strong><span>{{accountEmail}}</span></div><button type="button" (click)="logout()"><svg lucideIcon="log-out"></svg>Sair</button></gr-menu></gr-popover></div>
      </header>
      <main class="content" [attr.aria-busy]="context.transitionPending()"><div class="route-content" [class.context-hidden]="context.transitionPending()"><router-outlet /></div>@if(context.transitionPending()){<div class="context-transition" role="status"><span class="transition-indicator" aria-hidden="true"><i></i></span><span>Atualizando contexto</span><p>Validando seu acesso à nova fazenda ou organização...</p><div class="transition-lines" aria-hidden="true"><span></span><span></span></div></div>}</main>
    </div>
    <gr-toast-region />
  </div>`,
  styles:[`
    .shell{min-height:100dvh}.sidebar{position:fixed;z-index:40;inset:0 auto 0 0;width:var(--sidebar-width);display:grid;grid-template-rows:auto 1fr auto;border-right:1px solid var(--color-border);background:#f9faf9;transition:width var(--duration-context) var(--ease-standard),transform var(--duration-context) var(--ease-standard)}
    .brand{height:var(--topbar-height);display:flex;align-items:center;gap:var(--space-3);padding:0 var(--space-4);border-bottom:1px solid var(--color-border)}.brand strong{font-size:.8125rem;line-height:1.05;letter-spacing:-.02em}.brand-mark{width:2rem;height:2rem;display:grid;place-items:center;flex:0 0 auto;border-radius:var(--radius-sm);color:#fff;background:var(--color-primary)}.brand-mark i{width:1rem;height:.7rem;border:1.5px solid currentColor;border-radius:60% 40% 55% 45%;transform:rotate(-12deg)}.close-mobile{display:none;margin-left:auto;border:0;background:transparent;color:var(--color-text-secondary)}.mobile-contexts{display:none}
    nav{overflow-y:auto;padding:var(--space-4) var(--space-3)}nav section+section{margin-top:var(--space-5)}nav h2{height:1.25rem;margin:0 var(--space-3) var(--space-1);font-size:.6875rem;line-height:1.25rem;letter-spacing:.075em;color:var(--color-text-muted)}ul{display:grid;gap:2px;margin:0;padding:0;list-style:none}a{position:relative;min-height:var(--control-height-small);display:flex;align-items:center;gap:var(--space-3);padding:0 var(--space-3);border-radius:var(--radius-sm);color:var(--color-text-secondary);font-size:.875rem;text-decoration:none;transition:color var(--duration-fast),background var(--duration-fast)}a:hover{color:var(--color-text);background:var(--color-surface-soft)}a.active{color:var(--color-primary);background:var(--color-primary-subtle);font-weight:650}a.active:before{content:'';position:absolute;left:-.75rem;width:3px;height:1.25rem;border-radius:0 2px 2px 0;background:var(--color-primary)}a.active svg{stroke-width:2.1}a svg,.sidebar-footer svg{width:1rem;height:1rem;flex:0 0 auto;stroke-width:1.8}
    .sidebar-footer{position:relative;padding:var(--space-3);border-top:1px solid var(--color-border)}.sidebar-footer:before{content:'';position:absolute;top:-2px;left:var(--space-6);width:1.5rem;height:2px;background:var(--color-accent)}.sidebar-footer button{width:100%;min-height:var(--control-height-small);display:flex;align-items:center;gap:var(--space-3);padding:0 var(--space-3);border:0;border-radius:var(--radius-sm);color:var(--color-text-muted);background:transparent;cursor:pointer}.sidebar-footer button:hover{background:var(--color-surface-soft)}kbd{margin-left:auto;padding:1px 5px;border:1px solid var(--color-border);border-radius:4px;color:var(--color-text-muted);background:var(--color-surface);font:inherit;font-size:.6875rem}
    .workspace{min-height:100dvh;margin-left:var(--sidebar-width);transition:margin-left var(--duration-context) var(--ease-standard)}.topbar{position:sticky;z-index:20;top:0;height:var(--topbar-height);display:flex;align-items:center;justify-content:space-between;gap:var(--space-4);padding:0 var(--space-5);border-bottom:1px solid var(--color-border);background:rgb(249 251 249 / 94%);backdrop-filter:blur(12px)}.topbar-start,.topbar-actions,.contexts,.account-trigger{display:flex;align-items:center;min-width:0}.menu-button{display:none}.contexts{min-width:0;transition:opacity var(--duration-standard)}.contexts.pending{opacity:.55;pointer-events:none}.topbar-actions{flex:0 0 auto}.account-trigger{gap:var(--space-2);margin-left:var(--space-2);padding:2px var(--space-2) 2px 2px;border:1px solid transparent;border-radius:var(--radius-md);background:transparent;cursor:pointer}.account-trigger:hover{border-color:var(--color-border);background:var(--color-surface-soft)}.account-trigger>span{display:grid;text-align:left}.account-trigger strong{max-width:8rem;overflow:hidden;font-size:.8125rem;text-overflow:ellipsis;white-space:nowrap}.account-trigger small{font-size:.75rem;color:var(--color-text-muted)}.account-trigger>svg{width:.75rem}
    gr-menu svg{width:1rem;height:1rem}.account-identity{display:grid;gap:2px;min-width:13rem;padding:var(--space-2) var(--space-3) var(--space-3);border-bottom:1px solid var(--color-border)}.account-identity strong{font-size:.875rem}.account-identity span{overflow:hidden;color:var(--color-text-secondary);font-size:.8125rem;text-overflow:ellipsis}.content{max-width:var(--content-max);min-height:calc(100dvh - var(--topbar-height));margin:0 auto;padding:var(--space-8)}.route-content{animation:context-content-in var(--duration-context) var(--ease-emphasized)}.route-content.context-hidden{display:none}.context-transition{min-height:18rem;display:grid;align-content:center;justify-items:center;border-top:1px solid var(--color-border);text-align:center;animation:context-content-in var(--duration-context) var(--ease-standard)}.context-transition>span:not(.transition-indicator){font-size:.8125rem;font-weight:680;color:var(--color-primary)}.context-transition p{margin:var(--space-2) 0 0}.transition-indicator{position:relative;width:2.5rem;height:2.5rem;display:grid;place-items:center;margin-bottom:var(--space-4);border:1px solid var(--color-border-strong);border-radius:50%;background:var(--color-primary-subtle)}.transition-indicator:before{content:'';position:absolute;inset:.5rem;border:1px solid var(--color-accent);border-radius:55% 45% 60% 40%;transform:rotate(-25deg)}.transition-indicator i{position:relative;width:.375rem;height:.375rem;border-radius:50%;background:var(--color-primary)}.transition-lines{width:min(15rem,100%);display:grid;gap:var(--space-2);margin-top:var(--space-6)}.transition-lines span{height:.5rem;border-radius:var(--radius-sm);background:var(--color-surface-soft);animation:loading-pulse var(--duration-context) var(--ease-standard) infinite alternate}.transition-lines span+span{width:68%;justify-self:center;animation-delay:var(--duration-fast)}@keyframes context-content-in{from{opacity:0;transform:translateY(4px)}}@keyframes loading-pulse{to{background:var(--color-primary-subtle)}}
    .collapsed .sidebar{width:4.25rem}.collapsed .workspace{margin-left:4.25rem}.collapsed .brand{justify-content:center}.collapsed .brand strong,.collapsed nav h2,.collapsed nav a span,.collapsed .sidebar-footer span,.collapsed .sidebar-footer kbd{display:none}.collapsed nav{padding-inline:var(--space-2)}.collapsed nav section+section{margin-top:var(--space-3)}.collapsed nav a,.collapsed .sidebar-footer button{justify-content:center;padding:0}.collapsed nav a.active:before{left:-.5rem}
    .mobile-backdrop{position:fixed;z-index:35;inset:0;border:0;background:rgb(18 27 22 / 35%)}
    @media(max-width:64rem){.sidebar{transform:translateX(-100%);width:min(var(--sidebar-width),88vw)}.sidebar.mobile-open{transform:translateX(0)}.workspace,.collapsed .workspace{margin-left:0}.menu-button{display:inline-flex}.close-mobile{display:grid}.collapsed .sidebar{width:min(var(--sidebar-width),88vw)}.collapsed .brand{justify-content:flex-start}.collapsed .brand strong,.collapsed nav h2,.collapsed nav a span,.collapsed .sidebar-footer span,.collapsed .sidebar-footer kbd{display:initial}.collapsed nav{padding:var(--space-4) var(--space-3)}.collapsed nav a,.collapsed .sidebar-footer button{justify-content:flex-start;padding:0 var(--space-3)}}
    @media(max-width:46rem){.sidebar{grid-template-rows:auto auto 1fr auto}.mobile-contexts{display:block;padding:var(--space-3);border-bottom:1px solid var(--color-border)}.topbar{padding:0 var(--space-3)}.account-trigger>span,.account-trigger>svg{display:none}.account-trigger{margin-left:0}.content{padding:var(--space-5) var(--space-4)}}
    @media(max-width:64rem){.topbar-start{flex:1;min-width:0}.contexts{flex:1;min-width:0}.contexts gr-context-navigator{width:100%}}
  `],
  changeDetection:ChangeDetectionStrategy.OnPush,
})
export class AppShellComponent {
  readonly collapsed=signal(false);readonly mobileOpen=signal(false);private readonly manualLogout=signal(false);
  readonly navigation:NavSection[]=[
    {items:[{label:'Visão geral',icon:'house',route:'/visao-geral'}]},
    {label:'REBANHO',items:[{label:'Animais',icon:'beef',route:'/rebanho/animais'},{label:'Movimentações',icon:'land-plot',route:'/rebanho/movimentacoes'},{label:'Saúde',icon:'heart-pulse',route:'/rebanho/saude'},{label:'Reprodução',icon:'sprout',route:'/rebanho/reproducao'},{label:'Agenda',icon:'calendar-days',route:'/rebanho/agenda'}]},
    {label:'OPERAÇÃO',items:[{label:'Estoque',icon:'boxes',route:'/operacao/estoque'},{label:'Financeiro',icon:'credit-card',route:'/operacao/financeiro'}]},
    {label:'GESTÃO',items:[{label:'Fazendas',icon:'building-2',route:'/gestao/fazendas'},{label:'Usuários',icon:'users',route:'/gestao/usuarios',permission:'manageUsers'},{label:'Configurações',icon:'settings',route:'/gestao/configuracoes'}]},
  ];
  constructor(readonly context:ContextStore,readonly permissions:PermissionService,private readonly auth:AuthStore,private readonly router:Router,private readonly toast:ToastService){effect(()=>{if(this.auth.status()==='anonymous'&&!this.manualLogout()){this.context.clear();void this.router.navigate(['/entrar'],{queryParams:{motivo:'sessao-expirada'}});}});}
  get displayName():string{return this.context.user()?.displayName?.trim()||this.accountEmail||'Usuário';}
  get accountEmail():string{return this.context.user()?.email||this.auth.userEmail()||'';}
  get roleLabel():string{return {OWNER:'Proprietário',ADMIN:'Administrador',MANAGER:'Gerente',OPERATOR:'Operador',VIEWER:'Visualizador'}[this.context.role()||'VIEWER'];}
  async changeOrganization(id:string):Promise<void>{try{await this.context.selectOrganization(id);}catch{this.toast.show('error','Não foi possível trocar a organização','O contexto anterior foi preservado quando possível.');}}
  async changeFarm(id:string):Promise<void>{try{await this.context.selectFarm(id);}catch{this.toast.show('error','Não foi possível trocar a fazenda','Atualize a página e tente novamente.');}}
  async logout():Promise<void>{this.manualLogout.set(true);try{await this.auth.signOut();this.context.clear();await this.router.navigate(['/entrar']);}catch{this.manualLogout.set(false);this.toast.show('error','Não foi possível sair','Tente novamente.');}}
}
