import { TestBed } from '@angular/core/testing';
import { By } from '@angular/platform-browser';
import { provideRouter } from '@angular/router';
import { provideLucideIcons, LucideBeef, LucideCalendarDays, LucideLandPlot, LucideMapPinOff, LucideTriangleAlert } from '@lucide/angular';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { of } from 'rxjs';
import { dashboardShowcaseProviders } from './dashboard-showcase';
import { HomePageComponent } from './home-page.component';
import { ParityApi } from '../herd/parity-api.service';
import { HerdApi } from '../herd/herd-api.service';
import { ContextStore } from '../../core/context/context.store';
import { HomeHealthSectionComponent } from './home-health-section.component';

describe('Home operacional', () => {
  let element: HTMLElement;
  let fixture: ReturnType<typeof TestBed.createComponent<HomePageComponent>>;
  const pendingWork = vi.fn(() => of({items:[],page:0,size:20,totalElements:0,totalPages:1}));
  beforeEach(() => {
    HTMLDialogElement.prototype.showModal ??= function () { this.setAttribute('open', ''); };
    HTMLDialogElement.prototype.close ??= function () { this.removeAttribute('open'); };
    TestBed.configureTestingModule({imports:[HomePageComponent],providers:[provideRouter([]),provideLucideIcons(LucideBeef,LucideCalendarDays,LucideLandPlot,LucideMapPinOff,LucideTriangleAlert),...dashboardShowcaseProviders,{provide:ParityApi,useValue:{coverage:()=>of({totalActiveAnimals:428,unknownBirthDate:0,withRecordedTreatment:214})}},{provide:HerdApi,useValue:{pendingWork,animals:()=>of({items:[],totalPages:1}),plannerItem:()=>of({}),pregnancy:()=>of({})}}]});
    fixture=TestBed.createComponent(HomePageComponent);TestBed.tick();fixture.detectChanges();element=fixture.nativeElement;
  });
  it('usa Home Operacional como título e mostra a fazenda',()=>{expect(element.querySelector('h1')?.textContent).toContain('Home Operacional');expect(element.querySelector('.operation-standfirst')?.textContent).toContain('Fazenda Santa Helena');});
  it('preserva os quatro períodos com aria-pressed',()=>{const buttons=Array.from(element.querySelectorAll<HTMLButtonElement>('.period-pills button'));expect(buttons.length).toBe(4);buttons[0].click();fixture.detectChanges();expect(buttons[0].getAttribute('aria-pressed')).toBe('true');});
  it('abre o formulário de período personalizado',()=>{element.querySelectorAll<HTMLButtonElement>('.period-pills button')[3].click();fixture.detectChanges();expect(element.querySelectorAll('input[type=date]').length).toBe(2);});
  it('rejeita intervalo personalizado inválido',()=>{element.querySelectorAll<HTMLButtonElement>('.period-pills button')[3].click();fixture.detectChanges();fixture.componentInstance.customFrom.set('2026-09-16');fixture.componentInstance.customTo.set('2026-09-15');element.querySelector<HTMLFormElement>('form')?.dispatchEvent(new Event('submit',{cancelable:true}));fixture.detectChanges();expect(element.querySelector('[role=alert]')?.textContent).toContain('datas válidas');});
  it('mantém acessos de gestão em menu discreto',()=>{expect(Array.from(element.querySelectorAll('.quick-links a')).map(a=>a.getAttribute('href'))).toEqual(['/gestao/insumos','/gestao/financeiro','/administracao']);});
  it('mostra as cinco áreas operacionais',()=>{for(const selector of ['.home-summary-section','.focus','.agenda-section','.health-section','.indicators-section'])expect(element.querySelector(selector)).not.toBeNull();});
  it('usa quatro botões sem interativos aninhados no resumo',()=>{const cards=element.querySelectorAll('gr-metric-deck button.object');expect(cards.length).toBe(4);for(const card of cards)expect(card.querySelector('a,button')).toBeNull();});
  it('mostra rebanho real no resumo',()=>{expect(element.querySelector('.obj-herd')?.textContent).toContain('428');});
  it('mostra piquetes e ocupação reais',()=>{expect(element.querySelector('.obj-territory')?.textContent).toContain('6');expect(element.querySelector('.obj-territory')?.textContent).toContain('4 ocupados');});
  it('mostra percentual derivado de localização sem alegar rastreamento online',()=>{expect(element.querySelector('.obj-location')?.textContent).toContain('99,3%');expect(element.querySelector('.obj-location')?.textContent).not.toContain('online');});
  it('mostra atenção como situações identificadas',()=>{expect(element.querySelector('.obj-attention')?.textContent).toContain('62');expect(element.querySelector('.obj-attention')?.textContent).toContain('situações identificadas');});
  it('não fabrica piquetes quando a consulta falha',()=>{fixture.componentInstance.store.paddocks.set({status:'error',value:null,error:null});fixture.detectChanges();expect(element.querySelector('.obj-territory')?.textContent).toContain('Consulta indisponível');expect(element.textContent).toContain('Não foi possível consultar os piquetes');});
  it('oferece nova tentativa quando falha o resumo',()=>{fixture.componentInstance.store.overview.set({status:'error',value:null,error:null});fixture.detectChanges();expect(element.textContent).toContain('Não foi possível carregar o resumo');expect(element.querySelector('.metric-loading')).toBeNull();});
  it('abre um modal ao selecionar rebanho',()=>{element.querySelector<HTMLButtonElement>('.obj-herd')?.click();fixture.detectChanges();expect(element.querySelector('gr-dialog')).not.toBeNull();expect(element.textContent).toContain('Ver rebanho completo');});
  it('fecha o modal pelo botão nativo',()=>{element.querySelector<HTMLButtonElement>('.obj-herd')?.click();fixture.detectChanges();element.querySelector<HTMLButtonElement>('gr-dialog button[aria-label="Fechar janela"]')?.click();fixture.detectChanges();expect(element.querySelector('gr-dialog')).toBeNull();});
  it('fecha o modal ao trocar o contexto',()=>{element.querySelector<HTMLButtonElement>('.obj-herd')?.click();fixture.detectChanges();const context=TestBed.inject(ContextStore);context.contextVersion.set(2);TestBed.tick();fixture.detectChanges();expect(element.querySelector('gr-dialog')).toBeNull();});
  it('abre detalhe de localização com dados sob demanda',()=>{element.querySelector<HTMLButtonElement>('.obj-location')?.click();fixture.detectChanges();expect(element.textContent).toContain('animais sem piquete');});
  it('apresenta foco da operação com evento principal',()=>{expect(element.querySelector('.focus .hero')?.textContent).toContain('Vacinação do lote Norte');});
  it('abre detalhe da prioridade em modal',()=>{element.querySelector<HTMLButtonElement>('.focus .hero')?.click();fixture.detectChanges();expect(element.querySelector('gr-dialog')).not.toBeNull();});
  it('mostra sete dias na agenda',()=>{expect(element.querySelectorAll('.agenda-section .day').length).toBe(7);});
  it('abre agenda do dia sem navegar',()=>{element.querySelector<HTMLButtonElement>('.agenda-section .day')?.click();fixture.detectChanges();expect(element.querySelector('gr-dialog')?.textContent).toContain('Agenda do dia');});
  it('não mostra horário inventado na agenda',()=>{expect(element.querySelector('.agenda-section')?.textContent).not.toMatch(/09:00|11:00|14:00/);});
  it('mostra números reais na seção sanitária',()=>{expect(element.querySelector('.health-section')?.textContent).toContain('24');expect(element.querySelector('.health-section')?.textContent).toContain('Brucelose');});
  it('rotula aftosa como registro histórico',()=>{expect(element.querySelector('.coverage')?.textContent).toContain('registro histórico');expect(element.querySelector('.coverage')?.textContent).not.toContain('em dia');});
  it('mantém os demais cards quando a cobertura está indisponível',()=>{const health=fixture.debugElement.query(By.directive(HomeHealthSectionComponent)).componentInstance as HomeHealthSectionComponent;health.coverageStatus.set('error');fixture.detectChanges();expect(element.querySelector('.coverage')?.textContent).toContain('Consulta indisponível');expect(element.querySelectorAll('.health-card').length).toBe(5);});
  it('abre pendências de vacinação no modal',()=>{element.querySelector<HTMLButtonElement>('.health-card')?.click();fixture.detectChanges();expect(pendingWork).toHaveBeenCalledWith({type:'VACCINATION_DUE',page:0});});
  it('mostra seis indicadores do período sem deltas falsos',()=>{expect(element.querySelectorAll('.indicator').length).toBe(6);expect(element.querySelector('.indicators-section')?.textContent).not.toContain('+12%');});
  it('abre detalhes dos indicadores com gráfico acessível',()=>{element.querySelector<HTMLButtonElement>('.indicator')?.click();fixture.detectChanges();expect(element.querySelector('gr-dialog app-activity-chart')).not.toBeNull();});
  it('mantém os minigráficos redundantes fora da árvore acessível',()=>{for(const svg of element.querySelectorAll('app-home-mini-series svg'))expect(svg.getAttribute('aria-hidden')).toBe('true');});
});
