import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { AlertComponent, EmptyStateComponent, ErrorStateComponent, ProgressComponent, SkeletonComponent, ToastRegionComponent, ToastService } from '../../design-system/feedback/feedback';
import { AvatarComponent, FilterBarComponent, MetricComponent, PaginationComponent, StatusIndicatorComponent, TableComponent } from '../../design-system/data-display/data-display';
import { BreadcrumbComponent, TabsComponent } from '../../design-system/navigation/navigation';
import { BadgeComponent, ButtonComponent, CheckboxComponent, ChipComponent, DividerComponent, IconButtonComponent, InputComponent, RadioComponent, SelectComponent, SwitchComponent, TextareaComponent, TooltipDirective } from '../../design-system/primitives/primitives';
import { CardComponent, DialogComponent, DrawerComponent, MenuComponent, PanelComponent, PopoverComponent } from '../../design-system/surfaces/surfaces';

@Component({
  selector:'app-design-system-page',
  imports:[ReactiveFormsModule,AlertComponent,EmptyStateComponent,ErrorStateComponent,ProgressComponent,SkeletonComponent,ToastRegionComponent,AvatarComponent,FilterBarComponent,MetricComponent,PaginationComponent,StatusIndicatorComponent,TableComponent,BreadcrumbComponent,TabsComponent,BadgeComponent,ButtonComponent,CheckboxComponent,ChipComponent,DividerComponent,IconButtonComponent,InputComponent,RadioComponent,SelectComponent,SwitchComponent,TextareaComponent,TooltipDirective,CardComponent,DialogComponent,DrawerComponent,MenuComponent,PanelComponent,PopoverComponent],
  template:`<main><header><span>Ambiente de desenvolvimento</span><h1>Design System v1</h1><p>Fundação visual e comportamental do Gerenciador Rural.</p></header>
    <section><h2>Tokens</h2><div class="swatches">@for(color of colors;track color.name){<div><i [style.background]="color.value"></i><strong>{{color.name}}</strong><code>{{color.value}}</code></div>}</div></section>
    <section><h2>Ações e indicadores</h2><div class="row"><gr-button>Salvar alterações</gr-button><gr-button variant="secondary">Cancelar</gr-button><gr-button variant="ghost">Ver detalhes</gr-button><gr-button variant="danger">Excluir</gr-button><gr-button [loading]="true">Salvando</gr-button><gr-icon-button label="Mais informações">?</gr-icon-button></div><gr-divider/><div class="row"><gr-badge tone="success">Ativo</gr-badge><gr-badge tone="warning">Pendente</gr-badge><gr-badge tone="danger">Atenção</gr-badge><gr-chip [removable]="true">Nelore</gr-chip><gr-status-indicator tone="success">Operação normal</gr-status-indicator><gr-avatar name="Marina Oliveira" /></div></section>
    <section><h2>Formulários</h2><div class="form-grid"><gr-input label="Nome da fazenda" description="Use o nome conhecido pela equipe." placeholder="Fazenda Santa Clara" [formControl]="text"/><gr-select label="Categoria" [options]="[{value:'gado',label:'Gado de corte'},{value:'leite',label:'Gado leiteiro'}]" [formControl]="select"/><gr-textarea label="Observações" placeholder="Adicione informações importantes" [formControl]="notes"/><div class="checks"><gr-checkbox [formControl]="checked">Receber alertas operacionais</gr-checkbox><gr-radio name="period" optionValue="month" [formControl]="period">Este mês</gr-radio><gr-radio name="period" optionValue="year" [formControl]="period">Este ano</gr-radio><gr-switch [formControl]="enabled">Fazenda ativa</gr-switch></div></div></section>
    <section><h2>Feedback</h2><div class="feedback"><gr-alert tone="success" title="Alteração concluída"><p>As informações foram atualizadas.</p></gr-alert><gr-alert tone="warning" title="Atenção necessária"><p>Há dados que precisam de revisão.</p></gr-alert><gr-progress [value]="64" label="Importação de dados"/><gr-skeleton /><gr-error-state title="Não foi possível carregar" description="Verifique sua conexão e tente novamente." /></div></section>
    <section><h2>Superfícies e navegação</h2><gr-breadcrumb [items]="[{label:'Gestão',url:'/'},{label:'Fazendas'}]"/><gr-tabs [tabs]="[{id:'geral',label:'Geral'},{id:'acesso',label:'Acesso'}]" [active]="activeTab()" (activeChange)="activeTab.set($event)"/><div class="row surface-actions"><gr-button variant="secondary" (pressed)="dialogOpen.set(true)">Abrir janela</gr-button><gr-button variant="secondary" (pressed)="drawerOpen.set(true)">Abrir painel</gr-button><gr-popover><gr-button popover-trigger variant="secondary">Mais ações</gr-button><gr-menu><button role="menuitem">Duplicar</button><button role="menuitem">Arquivar</button></gr-menu></gr-popover><button type="button" grTooltip="Ajuda contextual">Passe o cursor</button></div><gr-panel><strong panel-title>Resumo do território</strong><gr-metric label="Área acompanhada" value="1.284 ha" detail="Contexto demonstrativo"/></gr-panel></section>
    <section><h2>Dados</h2><gr-filter-bar><span>Filtros preparados para módulos futuros</span></gr-filter-bar><gr-table><thead><tr><th>Identificação</th><th>Status</th><th>Localização</th></tr></thead><tbody><tr><td>BR-001</td><td><gr-badge tone="success">Ativo</gr-badge></td><td>Piquete Norte</td></tr><tr><td>BR-002</td><td><gr-badge tone="warning">Revisão</gr-badge></td><td>Piquete Sul</td></tr></tbody></gr-table><gr-pagination [page]="0" [totalPages]="3"/></section>
    <section><h2>Estado vazio</h2><gr-card><gr-empty-state title="Nenhum registro encontrado" description="Ajuste os filtros ou cadastre o primeiro item." /></gr-card></section>
    <gr-dialog [open]="dialogOpen()" (closed)="dialogOpen.set(false)"><strong dialog-title>Confirmar alteração</strong><p>A janela usa o elemento dialog nativo, com foco modal e fechamento por Escape.</p><div dialog-actions><gr-button variant="secondary" (pressed)="dialogOpen.set(false)">Cancelar</gr-button><gr-button (pressed)="dialogOpen.set(false)">Confirmar</gr-button></div></gr-dialog>
    <gr-drawer label="Detalhes da fazenda" [open]="drawerOpen()" (closed)="drawerOpen.set(false)"><p>Conteúdo contextual sem perder a página atual.</p></gr-drawer><gr-toast-region />
  </main>`,
  styles:[`main{max-width:78rem;margin:0 auto;padding:var(--space-10)}header{margin-bottom:var(--space-10)}header>span{font-size:.6875rem;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:var(--color-primary)}header h1{margin-top:var(--space-2)}section{display:grid;gap:var(--space-5);padding:var(--space-8) 0;border-top:1px solid var(--color-border)}section h2{margin:0}.row{display:flex;align-items:center;flex-wrap:wrap;gap:var(--space-3)}.swatches{display:grid;grid-template-columns:repeat(auto-fit,minmax(9rem,1fr));gap:var(--space-3)}.swatches div{display:grid;gap:var(--space-1)}.swatches i{height:4rem;border:1px solid var(--color-border);border-radius:var(--radius-md)}.swatches strong{font-size:.75rem}.swatches code{color:var(--color-text-muted);font-size:.6875rem}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--space-5)}.checks{display:grid;align-content:start;gap:var(--space-4)}.feedback{display:grid;gap:var(--space-4)}.surface-actions>button{min-height:2.5rem;padding:0 var(--space-3);border:1px solid var(--color-border);border-radius:var(--radius-md);background:var(--color-surface)}gr-panel gr-metric{max-width:13rem}gr-table+gr-pagination{margin-top:var(--space-2)}@media(max-width:42rem){main{padding:var(--space-6) var(--space-4)}.form-grid{grid-template-columns:1fr}}`],
  changeDetection:ChangeDetectionStrategy.OnPush,
})
export class DesignSystemPageComponent {
  readonly text=new FormControl('');readonly select=new FormControl('');readonly notes=new FormControl('');readonly checked=new FormControl(false);readonly period=new FormControl('month');readonly enabled=new FormControl(true);readonly activeTab=signal('geral');readonly dialogOpen=signal(false);readonly drawerOpen=signal(false);
  readonly colors=[{name:'Fundo',value:'#f5f7f5'},{name:'Superfície',value:'#ffffff'},{name:'Texto',value:'#17211b'},{name:'Primária',value:'#1f563d'},{name:'Atenção',value:'#a15f0b'},{name:'Perigo',value:'#b23a3a'}];
  constructor(readonly toast:ToastService){}
}
