import { ChangeDetectionStrategy, Component, computed, signal } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { AlertComponent, EmptyStateComponent, ErrorStateComponent, ProgressComponent, SkeletonComponent, ToastRegionComponent, ToastService } from '../../design-system/feedback/feedback';
import { AttentionItemComponent, AvatarComponent, FilterBarComponent, MetricComponent, PaginationComponent, StatusIndicatorComponent, TableComponent } from '../../design-system/data-display/data-display';
import { BreadcrumbComponent, ContextNavigatorComponent, TabsComponent } from '../../design-system/navigation/navigation';
import { FarmOption, OrganizationOption } from '../../core/api/api.models';
import { BadgeComponent, ButtonComponent, CheckboxComponent, ChipComponent, DividerComponent, IconButtonComponent, InputComponent, RadioComponent, SelectComponent, SwitchComponent, TextareaComponent, TooltipDirective } from '../../design-system/primitives/primitives';
import { CardComponent, DialogComponent, DrawerComponent, MenuComponent, PanelComponent, PopoverComponent } from '../../design-system/surfaces/surfaces';

@Component({
  selector:'app-design-system-page',
  imports:[ReactiveFormsModule,AlertComponent,EmptyStateComponent,ErrorStateComponent,ProgressComponent,SkeletonComponent,ToastRegionComponent,AttentionItemComponent,AvatarComponent,FilterBarComponent,MetricComponent,PaginationComponent,StatusIndicatorComponent,TableComponent,BreadcrumbComponent,ContextNavigatorComponent,TabsComponent,BadgeComponent,ButtonComponent,CheckboxComponent,ChipComponent,DividerComponent,IconButtonComponent,InputComponent,RadioComponent,SelectComponent,SwitchComponent,TextareaComponent,TooltipDirective,CardComponent,DialogComponent,DrawerComponent,MenuComponent,PanelComponent,PopoverComponent],
  template:`<main><header><span>Ambiente de desenvolvimento</span><h1>Design System v1</h1><p>Fundação visual e comportamental do BovNex.</p></header>
    <section><h2>Tokens</h2><div class="swatches">@for(color of colors;track color.name){<div><i [style.background]="color.value"></i><strong>{{color.name}}</strong><code>{{color.value}}</code></div>}</div></section>
    <section><h2>Ações e indicadores</h2><div class="row"><gr-button>Salvar alterações</gr-button><gr-button variant="secondary">Cancelar</gr-button><gr-button variant="ghost">Ver detalhes</gr-button><gr-button variant="danger">Excluir</gr-button><gr-button [disabled]="true">Indisponível</gr-button><gr-button [loading]="true">Salvando</gr-button><gr-icon-button label="Mais informações">?</gr-icon-button></div><p class="demo-note">Passe o cursor ou use Tab para verificar hover e foco. Botões desabilitados e em carregamento mantêm a largura.</p><gr-divider/><div class="row"><gr-badge tone="success">Ativo</gr-badge><gr-badge tone="warning">Pendente</gr-badge><gr-badge tone="danger">Atenção</gr-badge><gr-chip [removable]="true">Nelore</gr-chip><gr-status-indicator tone="success">Operação normal</gr-status-indicator><gr-avatar name="Marina Oliveira" /></div></section>
    <section><h2>Formulários</h2><div class="form-grid"><gr-input label="Nome da fazenda" description="Use o nome conhecido pela equipe." placeholder="Fazenda Santa Clara" [formControl]="text"/><gr-select label="Categoria" [options]="[{value:'gado',label:'Gado de corte'},{value:'leite',label:'Gado leiteiro'}]" [formControl]="select"/><gr-textarea label="Observações" placeholder="Adicione informações importantes" [formControl]="notes"/><gr-input label="Campo com erro" error="Informe um nome válido." [formControl]="invalidText"/><gr-input label="Campo desabilitado" [formControl]="disabledText"/><gr-input label="Campo somente leitura" [readonly]="true" [formControl]="readonlyText"/><div class="checks"><gr-checkbox [formControl]="checked">Receber alertas operacionais</gr-checkbox><gr-radio name="period" optionValue="month" [formControl]="period">Este mês</gr-radio><gr-radio name="period" optionValue="year" [formControl]="period">Este ano</gr-radio><gr-switch [formControl]="enabled">Fazenda ativa</gr-switch></div></div></section>
    <section><h2>Feedback</h2><div class="feedback"><gr-alert tone="success" title="Alteração concluída"><p>As informações foram atualizadas.</p></gr-alert><gr-alert tone="warning" title="Atenção necessária"><p>Há dados que precisam de revisão.</p></gr-alert><gr-alert tone="error" title="Não foi possível salvar"><p>Revise os dados e tente novamente.</p></gr-alert><gr-alert tone="info" title="Informação disponível"><p>Consulte os detalhes antes de continuar.</p></gr-alert><gr-progress [value]="64" label="Importação de dados"/><gr-skeleton /><gr-error-state title="Não foi possível carregar" description="Verifique sua conexão e tente novamente." /></div></section>
    <section><h2>Superfícies e navegação</h2><gr-breadcrumb [items]="[{label:'Gestão',url:'/'},{label:'Fazendas'}]"/><gr-tabs [tabs]="[{id:'geral',label:'Geral'},{id:'acesso',label:'Acesso'}]" [active]="activeTab()" (activeChange)="activeTab.set($event)"/><div class="row surface-actions"><gr-button variant="secondary" (pressed)="dialogOpen.set(true)">Abrir janela</gr-button><gr-button variant="secondary" (pressed)="drawerOpen.set(true)">Abrir painel</gr-button><gr-popover><span popover-trigger class="demo-popover-trigger">Mais ações</span><gr-menu><button type="button">Duplicar</button><button type="button">Arquivar</button></gr-menu></gr-popover><button type="button" grTooltip="Ajuda contextual">Passe o cursor</button></div><gr-panel><strong panel-title>Resumo do território</strong><gr-metric label="Área acompanhada" value="1.284 ha" detail="Contexto demonstrativo"/></gr-panel></section>
    <section><h2>Dados</h2><gr-filter-bar><span>Filtros preparados para módulos futuros</span></gr-filter-bar><gr-table><thead><tr><th>Identificação</th><th>Status</th><th>Localização</th><th>Ações</th></tr></thead><tbody><tr aria-selected="true"><td>BR-001</td><td><gr-badge tone="success">Ativo</gr-badge></td><td>Piquete Norte</td><td><button type="button">Detalhes</button></td></tr><tr><td>BR-002</td><td><gr-badge tone="warning">Revisão</gr-badge></td><td>Piquete Sul</td><td><button type="button">Detalhes</button></td></tr></tbody></gr-table><gr-pagination [page]="0" [totalPages]="3"/><div class="form-grid"><gr-table [empty]="true"/><gr-table [loading]="true"/></div></section>
    <section><h2>Padrões do produto</h2><p class="demo-note">Exemplos isolados de linguagem visual, sem dados ou integrações reais.</p><div class="patterns"><div class="pattern"><strong>Navegador de contexto</strong><gr-context-navigator [organizations]="organizations" [farms]="availableFarms()" [organization]="selectedOrganization()" [farm]="selectedFarm()" (organizationChanged)="selectOrganization($event)" (farmChanged)="selectFarm($event)" /></div><div class="pattern"><strong>Status operacional</strong><gr-status-indicator tone="success">Operação normal</gr-status-indicator><gr-status-indicator tone="warning">Revisão necessária</gr-status-indicator></div><div class="pattern"><strong>Métrica</strong><gr-metric label="Área acompanhada" value="1.284 ha" detail="Exemplo demonstrativo" /></div><div class="pattern"><strong>Item de atenção</strong><gr-attention-item title="Revisar informações" description="Exemplo de mensagem operacional." meta="Hoje" /></div><div class="pattern"><strong>Navegação ativa</strong><span class="sidebar-pattern" aria-current="page"><i aria-hidden="true"></i>Visão geral</span></div><div class="pattern"><strong>Indicador territorial</strong><span class="territory-pattern" aria-hidden="true"><i></i></span></div></div></section>
    <section><h2>Estado vazio</h2><gr-card><gr-empty-state title="Nenhum registro encontrado" description="Ajuste os filtros ou cadastre o primeiro item." /></gr-card></section>
    <gr-dialog [open]="dialogOpen()" (closed)="dialogOpen.set(false)"><strong dialog-title>Confirmar alteração</strong><p>A janela usa o elemento dialog nativo, com foco modal e fechamento por Escape.</p><div dialog-actions><gr-button variant="secondary" (pressed)="dialogOpen.set(false)">Cancelar</gr-button><gr-button (pressed)="dialogOpen.set(false)">Confirmar</gr-button></div></gr-dialog>
    <gr-drawer label="Detalhes da fazenda" [open]="drawerOpen()" (closed)="drawerOpen.set(false)"><p>Conteúdo contextual sem perder a página atual.</p></gr-drawer><gr-toast-region />
  </main>`,
  styles:[`main{max-width:78rem;margin:0 auto;padding:var(--space-10)}header{margin-bottom:var(--space-10)}header>span{font-size:.8125rem;font-weight:700;color:var(--color-primary)}header h1{margin-top:var(--space-2)}section{display:grid;gap:var(--space-5);padding:var(--space-8) 0;border-top:1px solid var(--color-border)}section h2{margin:0}.row{display:flex;align-items:center;flex-wrap:wrap;gap:var(--space-3)}.demo-note{margin:0;font-size:.8125rem}.swatches{display:grid;grid-template-columns:repeat(auto-fit,minmax(9rem,1fr));gap:var(--space-3)}.swatches div{display:grid;gap:var(--space-1)}.swatches i{height:4rem;border:1px solid var(--color-border);border-radius:var(--radius-md)}.swatches strong{font-size:.8125rem}.swatches code{color:var(--color-text-muted);font-size:.75rem}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--space-5)}.checks{display:grid;align-content:start;gap:var(--space-4)}.feedback{display:grid;gap:var(--space-4)}.surface-actions>button,.demo-popover-trigger{min-height:var(--control-height);display:inline-flex;align-items:center;padding:0 var(--space-3);border:1px solid var(--color-border);border-radius:var(--radius-md);background:var(--color-surface)}gr-panel gr-metric{max-width:13rem}gr-table+gr-pagination{margin-top:var(--space-2)}.patterns{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--space-6) var(--space-8)}.pattern{min-width:0;display:grid;align-content:start;justify-items:start;gap:var(--space-3);padding:var(--space-4) 0;border-top:1px solid var(--color-border)}.pattern>strong{font-size:.8125rem;color:var(--color-text-secondary)}.sidebar-pattern{position:relative;min-height:var(--control-height-small);display:flex;align-items:center;padding:0 var(--space-4);border-radius:var(--radius-sm);color:var(--color-primary);background:var(--color-primary-subtle);font-size:.875rem;font-weight:650}.sidebar-pattern:before{content:'';position:absolute;left:-.5rem;width:3px;height:1.25rem;border-radius:2px;background:var(--color-primary)}.sidebar-pattern i{width:.5rem;height:.5rem;margin-right:var(--space-3);border-radius:50%;background:var(--color-primary)}.territory-pattern{position:relative;width:2.5rem;height:2.5rem;display:grid;place-items:center;border:1px solid var(--color-border-strong);border-radius:50%;background:var(--color-primary-subtle)}.territory-pattern:before{content:'';position:absolute;inset:.5rem;border:1px solid var(--color-accent);border-radius:55% 45% 60% 40%;transform:rotate(-25deg)}.territory-pattern i{position:relative;width:.375rem;height:.375rem;border-radius:50%;background:var(--color-primary)}@media(max-width:42rem){main{padding:var(--space-6) var(--space-4)}.form-grid,.patterns{grid-template-columns:1fr}}`],
  changeDetection:ChangeDetectionStrategy.OnPush,
})
export class DesignSystemPageComponent {
  readonly text=new FormControl('');readonly select=new FormControl('');readonly notes=new FormControl('');readonly invalidText=new FormControl('');readonly disabledText=new FormControl({value:'Indisponível',disabled:true});readonly readonlyText=new FormControl('Somente leitura');readonly checked=new FormControl(false);readonly period=new FormControl('month');readonly enabled=new FormControl(true);readonly activeTab=signal('geral');readonly dialogOpen=signal(false);readonly drawerOpen=signal(false);
  readonly organizations:OrganizationOption[]=[{organizationId:'org-1',organizationName:'Grupo Santa Clara',membershipId:'m-1',role:'OWNER',farmScopeMode:'ALL'},{organizationId:'org-2',organizationName:'Grupo Horizonte',membershipId:'m-2',role:'MANAGER',farmScopeMode:'ALL'}];
  readonly farmsByOrganization:Record<string,FarmOption[]>={'org-1':[{farmId:'farm-1',farmName:'Fazenda Santa Clara'},{farmId:'farm-2',farmName:'Fazenda Boa Vista'}],'org-2':[{farmId:'farm-3',farmName:'Fazenda Horizonte'}]};
  readonly selectedOrganization=signal<OrganizationOption>(this.organizations[0]);
  readonly selectedFarm=signal<FarmOption|null>(this.farmsByOrganization['org-1'][0]);
  readonly availableFarms=computed(()=>this.farmsByOrganization[this.selectedOrganization().organizationId]||[]);
  selectOrganization(id:string):void{const option=this.organizations.find(item=>item.organizationId===id);if(option){this.selectedOrganization.set(option);this.selectedFarm.set(this.availableFarms()[0]||null);}}
  selectFarm(id:string):void{const option=this.availableFarms().find(item=>item.farmId===id);if(option)this.selectedFarm.set(option);}
  readonly colors=[{name:'Fundo',value:'#f5f7f5'},{name:'Superfície',value:'#ffffff'},{name:'Texto',value:'#17211b'},{name:'Primária',value:'#1f563d'},{name:'Atenção',value:'#a15f0b'},{name:'Perigo',value:'#b23a3a'}];
  constructor(readonly toast:ToastService){}
}
